-- ============================================================
-- Day 7 — Market Management: SQL Migration
--
-- !! TWO SEPARATE RUNS REQUIRED !!
--
-- STEP 1: Copy ONLY the single ALTER TYPE line below into the
--         Supabase SQL Editor and click RUN. Do not include any
--         other statements. ALTER TYPE ADD VALUE cannot run inside
--         a transaction — Supabase wraps multi-statement pastes in
--         one transaction, which breaks it and corrupts enum state.
--
-- STEP 2: After Step 1 succeeds, come back here, copy everything
--         from "STEP 2 START" to the end of the file, paste it
--         into a fresh SQL Editor tab, and click RUN.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- STEP 1 — paste and run THIS LINE ALONE, nothing else
-- ══════════════════════════════════════════════════════════════
ALTER TYPE market_status ADD VALUE IF NOT EXISTS 'waiting';
-- ══════════════════════════════════════════════════════════════
-- STEP 1 END — stop here; run the above, then continue to Step 2
-- ══════════════════════════════════════════════════════════════


-- ══════════════════════════════════════════════════════════════
-- STEP 2 START — paste everything below into a new SQL Editor run
-- ══════════════════════════════════════════════════════════════

-- 2. Add invite_token column to markets
--    Admin generates an invite link; the token is the last path segment.
--    Token is a UUID generated by the admin at invite time.
ALTER TABLE markets ADD COLUMN IF NOT EXISTS invite_token UUID DEFAULT NULL;

-- 3. Ensure new markets default to 'waiting' status
--    Note: no explicit cast — Postgres coerces the string to the enum automatically.
ALTER TABLE markets ALTER COLUMN status SET DEFAULT 'waiting';

-- 4. Update any existing markets that have no status to 'waiting'
UPDATE markets SET status = 'waiting' WHERE status IS NULL;

-- ============================================================
-- RLS Policies
-- ============================================================

-- 5. Allow any authenticated user to read a market by invite_token
--    (used by the /join/:token page to look up the market before joining)
DROP POLICY IF EXISTS "Anyone can read market by invite_token" ON markets;
CREATE POLICY "Anyone can read market by invite_token"
  ON markets FOR SELECT
  USING (auth.role() = 'authenticated');

-- 6. Only the admin (is_admin = true) can insert or update markets
DROP POLICY IF EXISTS "Admin can insert markets" ON markets;
CREATE POLICY "Admin can insert markets"
  ON markets FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

DROP POLICY IF EXISTS "Admin can update markets" ON markets;
CREATE POLICY "Admin can update markets"
  ON markets FOR UPDATE
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

-- 7. market_members insert: authenticated users can join a market they have been invited to
--    (client enforces invite_token check; RLS allows any auth user to insert their own row)
DROP POLICY IF EXISTS "Users can join a market" ON market_members;
CREATE POLICY "Users can join a market"
  ON market_members FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 8. market_members select: users see only their own memberships
DROP POLICY IF EXISTS "Users see own market memberships" ON market_members;
CREATE POLICY "Users see own market memberships"
  ON market_members FOR SELECT
  USING (auth.uid() = user_id);

-- Admin can see all memberships
DROP POLICY IF EXISTS "Admin can read all market_members" ON market_members;
CREATE POLICY "Admin can read all market_members"
  ON market_members FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

-- Admin can insert market_members (for add-by-email flow)
DROP POLICY IF EXISTS "Admin can insert market_members" ON market_members;
CREATE POLICY "Admin can insert market_members"
  ON market_members FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

-- Admin can delete market_members (remove user from market)
DROP POLICY IF EXISTS "Admin can delete market_members" ON market_members;
CREATE POLICY "Admin can delete market_members"
  ON market_members FOR DELETE
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

-- 9. portfolios: users can insert their own row (for join flow)
DROP POLICY IF EXISTS "Users can create own portfolio" ON portfolios;
CREATE POLICY "Users can create own portfolio"
  ON portfolios FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admin can also read all portfolios (for leaderboard / admin view)
DROP POLICY IF EXISTS "Admin can read all portfolios" ON portfolios;
CREATE POLICY "Admin can read all portfolios"
  ON portfolios FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

-- 10. Allow admin to read all users (needed for add-by-email lookup)
DROP POLICY IF EXISTS "Admin can read all users" ON users;
CREATE POLICY "Admin can read all users"
  ON users FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true)
  );

-- ============================================================
-- Done. Verify in the Supabase Table Editor:
--   markets.status now accepts 'waiting'
--   markets.invite_token column exists
-- ============================================================
