-- ============================================================
-- Day 7 — Market Management: SQL Migration
--
-- !! TWO SEPARATE RUNS REQUIRED !!
--
-- STEP 1: Copy ONLY the single ALTER TYPE line below into the
--         Supabase SQL Editor and click RUN. Do not include any
--         other statements. ALTER TYPE ADD VALUE cannot run inside
--         a transaction — Supabase wraps multi-statement pastes in
--         one transaction, which breaks it and corrupts enum state.
--
-- STEP 2: After Step 1 succeeds, come back here, copy everything
--         from "STEP 2 START" to the end of the file, paste it
--         into a fresh SQL Editor tab, and click RUN.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- STEP 1 — paste and run THIS LINE ALONE, nothing else
-- ══════════════════════════════════════════════════════════════
ALTER TYPE market_status ADD VALUE IF NOT EXISTS 'waiting';
-- ══════════════════════════════════════════════════════════════
-- STEP 1 END — stop here; run the above, then continue to Step 2
-- ══════════════════════════════════════════════════════════════


-- ══════════════════════════════════════════════════════════════
-- STEP 2 START — paste everything below into a new SQL Editor run
-- ══════════════════════════════════════════════════════════════

-- 2. Add invite_token column to markets
--    Admin generates an invite link; the token is the last path segment.
--    Token is a UUID generated by the admin at invite time.
ALTER TABLE markets ADD COLUMN IF NOT EXISTS invite_token UUID DEFAULT NULL;

-- 3. Ensure new markets default to 'waiting' status
--    Note: no explicit cast — Postgres coerces the string to the enum automatically.
ALTER TABLE markets ALTER COLUMN status SET DEFAULT 'waiting';

-- 4. Update any existing markets that have no status to 'waiting'
UPDATE markets SET status = 'waiting' WHERE status IS NULL;

-- ============================================================
-- RLS Policies
-- ============================================================

-- 5. Security definer function to check admin status without triggering RLS recursion.
--    All admin policies below use this function instead of inline EXISTS subqueries,
--    which would cause infinite recursion on the users table.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users WHERE id = auth.uid() AND is_admin = true
  );
$$;

-- 6. Allow any authenticated user to read a market by invite_token
--    (used by the /join/:token page to look up the market before joining)
DROP POLICY IF EXISTS "Anyone can read market by invite_token" ON markets;
CREATE POLICY "Anyone can read market by invite_token"
  ON markets FOR SELECT
  USING (auth.role() = 'authenticated');

-- 7. Only the admin can insert or update markets
DROP POLICY IF EXISTS "Admin can insert markets" ON markets;
CREATE POLICY "Admin can insert markets"
  ON markets FOR INSERT
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin can update markets" ON markets;
CREATE POLICY "Admin can update markets"
  ON markets FOR UPDATE
  USING (public.is_admin());

-- 8. market_members insert: authenticated users can join a market they have been invited to
DROP POLICY IF EXISTS "Users can join a market" ON market_members;
CREATE POLICY "Users can join a market"
  ON market_members FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 9. market_members select: users see only their own memberships
DROP POLICY IF EXISTS "Users see own market memberships" ON market_members;
CREATE POLICY "Users see own market memberships"
  ON market_members FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin can read all market_members" ON market_members;
CREATE POLICY "Admin can read all market_members"
  ON market_members FOR SELECT
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admin can insert market_me