// season2014.js — 2013-14 college basketball season
// Champion: UConn (defeated Kentucky 60-54) — 7-seed run, 3rd-lowest-seeded champ ever
// Final Four: UConn, Kentucky, Florida, Wisconsin
// Notable: Wichita State 35-0 in regular season (lost to Kentucky in R32)
//          Mercer over Duke (R64), Dayton's 11-seed Elite Eight run
//          Stanford as a 10-seed beat Kansas in R32 then made S16
//          Florida 18-0 in SEC regular season (#1 overall seed)
//          Doug McDermott (Creighton) National POY
//          Shabazz Napier MOP, Kevin Ollie's 2nd year as UConn HC
//
// AdjEM values are season-accurate approximations based on published KenPom
// end/mid-season ratings. Weekly values use smooth trajectories with seeded variance.

function traj(start, end, seed) {
  const n = 20;
  const out = [];
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1);
    const base = start + (end - start) * t;
    const noise = (Math.sin(i * seed * 2.3 + seed) + Math.cos(i * seed * 1.7)) * 0.35;
    out.push(Math.round((base + noise) * 100) / 100);
  }
  out[n - 1] = end;
  return out;
}

function rec(w, l) {
  const n = 20;
  return Array.from({ length: n }, (_, i) => {
    const t = i / (n - 1);
    return `${Math.round(w * t)}-${Math.round(l * t)}`;
  });
}

const WEEKS = [
  "Week 1 (Nov 11)", "Week 2 (Nov 18)", "Week 3 (Nov 25)", "Week 4 (Dec 2)",
  "Week 5 (Dec 9)",  "Week 6 (Dec 16)", "Week 7 (Dec 23)", "Week 8 (Dec 30)",
  "Week 9 (Jan 6)",  "Week 10 (Jan 13)","Week 11 (Jan 20)","Week 12 (Jan 27)",
  "Week 13 (Feb 3)", "Week 14 (Feb 10)","Week 15 (Feb 17)","Week 16 (Feb 24)",
  "Week 17 (Mar 3)", "Week 18 (Mar 10)","Week 19 (Mar 17)","Week 20 (Mar 24)",
];

// [team, conference, startAdjEM, endAdjEM, wins, losses, seed]
const RAW = [
  // ── Power conferences — elite ─────────────────────────────────────────────
  ["Arizona",         "Pac-12",         24.0,  28.0,  33,  5,  1],
  ["Florida",         "SEC",            22.5,  27.5,  36,  3,  2],
  ["Louisville",      "American",       24.5,  26.5,  31,  6,  3],
  ["Wisconsin",       "Big Ten",        22.0,  25.5,  30,  8,  4],
  ["Wichita St.",     "Missouri Valley",21.5,  24.0,  35,  1,  5],
  ["Virginia",        "ACC",            19.0,  23.0,  30,  7,  6],
  ["Kansas",          "Big 12",         22.0,  23.0,  25, 10,  7],
  ["Michigan St.",    "Big Ten",        22.0,  23.0,  29,  9,  8],
  ["Duke",            "ACC",            21.5,  22.5,  26,  9,  9],
  ["North Carolina",  "ACC",            19.0,  22.5,  24, 10, 10],
  ["Iowa St.",        "Big 12",         19.5,  22.0,  28,  8, 11],
  ["Creighton",       "Big East",       20.0,  22.0,  27,  8, 12],
  ["Michigan",        "Big Ten",        18.0,  22.0,  28,  9, 13],
  ["Kentucky",        "SEC",            22.5,  22.0,  29, 11, 14],
  ["Iowa",            "Big Ten",        19.0,  21.5,  20, 13, 15],
  ["Cincinnati",      "American",       20.0,  21.5,  27,  7, 16],
  ["Saint Louis",     "Atlantic 10",    19.5,  21.0,  27,  7, 17],
  ["Texas",           "Big 12",         18.0,  20.5,  24, 11, 18],
  ["Memphis",         "American",       18.5,  20.0,  24, 10, 19],
  ["Ohio St.",        "Big Ten",        19.0,  20.0,  25, 10, 20],
  ["Pittsburgh",      "ACC",            18.5,  19.5,  26, 10, 21],
  ["UCLA",            "Pac-12",         17.5,  19.5,  28,  9, 22],
  ["UConn",           "American",       17.5,  19.5,  32,  8, 23],
  ["Oklahoma",        "Big 12",         17.0,  19.0,  23, 10, 24],
  ["SMU",             "American",       16.0,  19.0,  27, 10, 25],
  ["Syracuse",        "ACC",            21.0,  20.5,  28,  6, 26],
  ["San Diego St.",   "Mountain West",  18.0,  20.0,  31,  5, 27],
  ["Villanova",       "Big East",       19.5,  20.5,  29,  5, 28],
  ["Oklahoma St.",    "Big 12",         17.5,  19.0,  21, 13, 29],
  ["VCU",             "Atlantic 10",    16.5,  18.5,  26,  9, 30],
  ["Gonzaga",         "WCC",            17.0,  18.5,  29,  7, 31],
  ["BYU",             "WCC",            14.5,  17.0,  23, 12, 32],
  ["New Mexico",      "Mountain West",  16.5,  18.0,  27,  7, 33],
  ["Tennessee",       "SEC",            14.0,  17.5,  24, 13, 34],
  ["Stanford",        "Pac-12",         13.5,  17.0,  23, 13, 35],
  ["Colorado",        "Pac-12",         15.0,  16.5,  23, 12, 36],
  ["Arizona St.",     "Pac-12",         15.5,  17.0,  21, 12, 37],
  ["Texas A&M",       "SEC",            12.0,  14.5,  18, 16, 38],
  ["Saint Joseph's",  "Atlantic 10",    14.5,  16.5,  24, 10, 39],
  ["Baylor",          "Big 12",         15.5,  17.5,  26, 12, 40],
  ["George Washington","Atlantic 10",   13.0,  15.5,  24,  9, 41],
  ["UMass",           "Atlantic 10",    13.5,  15.5,  24,  9, 42],
  ["Tulsa",           "C-USA",          13.0,  15.0,  21, 13, 43],
  ["Dayton",          "Atlantic 10",    13.5,  16.5,  26, 11, 44],
  ["Harvard",         "Ivy",            13.0,  15.0,  27,  5, 45],
  ["Stephen F. Austin","Southland",     12.5,  15.0,  32,  3, 46],
  ["NC State",        "ACC",            13.0,  15.0,  22, 14, 47],
  ["Mercer",          "Atlantic Sun",   11.0,  13.5,  27,  9, 48],
  ["Manhattan",       "MAAC",           10.5,  13.0,  25,  8, 49],
  ["North Dakota St.","Summit",         11.0,  13.5,  26,  7, 50],
  ["Florida St.",     "ACC",            14.5,  16.5,  22, 14, 51],
  ["Providence",      "Big East",       15.0,  17.5,  23, 12, 52],
  ["Marquette",       "Big East",       13.5,  15.5,  17, 15, 53],
  ["Xavier",          "Big East",       13.5,  16.0,  21, 13, 54],
  ["Georgetown",      "Big East",       13.0,  15.5,  18, 15, 55],

  // ── Other tournament/notable teams ───────────────────────────────────────
  ["Kansas St.",      "Big 12",         13.5,  15.5,  20, 13, 56],
  ["West Virginia",   "Big 12",         12.5,  14.5,  17, 16, 57],
  ["TCU",             "Big 12",          7.0,   9.5,   9, 22, 58],
  ["Texas Tech",      "Big 12",         10.0,  12.5,  14, 18, 59],
  ["Indiana",         "Big Ten",        13.0,  15.5,  17, 15, 60],
  ["Minnesota",       "Big Ten",        13.5,  15.5,  25, 13, 61],
  ["Nebraska",        "Big Ten",        13.5,  15.5,  19, 13, 62],
  ["Illinois",        "Big Ten",        12.0,  14.5,  20, 15, 63],
  ["Northwestern",    "Big Ten",         9.5,  11.5,  14, 19, 64],
  ["Penn St.",        "Big Ten",        10.0,  12.5,  16, 18, 65],
  ["Purdue",          "Big Ten",        10.5,  12.5,  15, 17, 66],
  ["Boston College",  "ACC",             9.5,  11.5,   8, 24, 67],
  ["Clemson",         "ACC",            12.0,  14.5,  23, 13, 68],
  ["Georgia Tech",    "ACC",             9.5,  11.5,  16, 17, 69],
  ["Maryland",        "ACC",            11.0,  13.0,  17, 15, 70],
  ["Miami (FL)",      "ACC",             7.5,   9.5,  17, 16, 71],
  ["Notre Dame",      "ACC",            10.5,  12.5,  15, 17, 72],
  ["Virginia Tech",   "ACC",             8.0,  10.0,   9, 22, 73],
  ["Wake Forest",     "ACC",            10.0,  12.0,  17, 16, 74],
  ["Alabama",         "SEC",            11.5,  13.5,  13, 19, 75],
  ["Arkansas",        "SEC",            12.5,  14.5,  22, 12, 76],
  ["Auburn",          "SEC",             9.0,  11.0,  14, 16, 77],
  ["Georgia",         "SEC",            10.5,  12.5,  20, 14, 78],
  ["LSU",             "SEC",            12.0,  14.0,  20, 14, 79],
  ["Mississippi St.", "SEC",             8.5,  10.5,  14, 19, 80],
  ["Missouri",        "SEC",            13.5,  15.5,  23, 12, 81],
  ["Ole Miss",        "SEC",            12.0,  14.0,  19, 14, 82],
  ["South Carolina",  "SEC",             7.5,   9.5,  14, 20, 83],
  ["Vanderbilt",      "SEC",            10.0,  12.0,  15, 16, 84],
  ["Oregon",          "Pac-12",         15.0,  17.0,  24, 10, 85],
  ["Washington",      "Pac-12",         12.0,  14.0,  17, 15, 86],
  ["California",      "Pac-12",         12.0,  14.0,  21, 14, 87],
  ["USC",             "Pac-12",          7.5,   9.5,  11, 21, 88],
  ["Utah",            "Pac-12",         13.0,  15.0,  21, 12, 89],
  ["Washington St.",  "Pac-12",          8.5,  10.5,  10, 21, 90],
  ["Oregon St.",      "Pac-12",          9.5,  11.5,  16, 16, 91],
  ["Houston",         "American",        9.0,  11.0,  17, 16, 92],
  ["UCF",             "American",        8.5,  10.5,  13, 18, 93],
  ["Rutgers",         "American",       11.0,  13.0,  12, 21, 94],
  ["South Florida",   "American",        7.5,   9.5,  12, 20, 95],
  ["Temple",          "American",       11.0,  13.0,   9, 22, 96],
  ["Saint Mary's",    "WCC",            14.5,  16.5,  23, 12, 97],
  ["San Francisco",   "WCC",            10.5,  12.5,  21, 12, 98],
  ["Pacific",         "WCC",             9.5,  11.5,  18, 16, 99],
  ["UNLV",            "Mountain West",  13.0,  15.0,  20, 13,100],
  ["Boise St.",       "Mountain West",  12.0,  14.0,  21, 13,101],
  ["Colorado St.",    "Mountain West",  11.0,  13.0,  16, 16,102],
  ["Fresno St.",      "Mountain West",   8.5,  10.5,  21, 11,103],
  ["Wyoming",         "Mountain West",   9.5,  11.5,  18, 15,104],
  ["Nevada",          "Mountain West",   8.5,  10.5,  15, 17,105],
  ["Air Force",       "Mountain West",   9.5,  11.5,  12, 18,106],
  ["Utah St.",        "Mountain West",   8.5,  10.5,  18, 14,107],
  ["Seton Hall",      "Big East",       10.5,  12.5,  17, 17,108],
  ["DePaul",          "Big East",        7.5,   9.5,  12, 21,109],
  ["Butler",          "Big East",       11.0,  13.0,  14, 17,110],
  ["St. John's",      "Big East",       12.0,  14.0,  20, 13,111],

  // ── Mid-major auto-bids & notables ───────────────────────────────────────
  ["Coastal Carolina","Big South",       9.5,  11.5,  21, 13,112],
  ["Albany",          "America East",    8.0,  10.0,  19, 15,113],
  ["Vermont",         "America East",    9.5,  11.5,  21, 12,114],
  ["Cal Poly",        "Big West",        7.0,   9.0,  14, 20,115],
  ["UC Santa Barbara","Big West",        9.0,  11.0,  21, 10,116],
  ["UC Irvine",       "Big West",        8.5,  10.5,  23, 12,117],
  ["Delaware",        "CAA",             9.0,  11.0,  25, 10,118],
  ["Drexel",          "CAA",             8.5,  10.5,  16, 14,119],
  ["Towson",          "CAA",             8.5,  10.5,  25, 11,120],
  ["Charleston",      "Southern",        9.5,  11.5,  14, 18,121],
  ["Davidson",        "Southern",       10.0,  12.5,  20, 13,122],
  ["Wofford",         "Southern",       11.0,  13.0,  20, 13,123],
  ["UNCG",            "Southern",        7.5,   9.5,  16, 16,124],
  ["Western Mich.",   "MAC",             9.0,  11.0,  23, 10,125],
  ["Toledo",          "MAC",            10.5,  12.5,  27,  7,126],
  ["Akron",           "MAC",             9.5,  11.5,  23, 13,127],
  ["Eastern Kentucky","OVC",             9.0,  11.0,  24, 10,128],
  ["Murray St.",      "OVC",             8.5,  10.5,  23,  9,129],
  ["Belmont",         "OVC",             9.5,  11.5,  26, 10,130],
  ["Weber St.",       "Big Sky",         8.5,  10.5,  19, 12,131],
  ["Eastern Wash.",   "Big Sky",         9.5,  11.5,  22, 12,132],
  ["Montana",         "Big Sky",         8.0,  10.0,  16, 14,133],
  ["NC Central",      "MEAC",            7.5,   9.5,  28,  6,134],
  ["Hampton",         "MEAC",            5.0,   7.0,  18, 14,135],
  ["Norfolk St.",     "MEAC",            5.5,   7.5,  20, 13,136],
  ["Texas Southern",  "SWAC",            6.5,   8.5,  19, 15,137],
  ["Mt. St. Mary's",  "NEC",             5.5,   7.5,  16, 17,138],
  ["Robert Morris",   "NEC",             7.0,   9.0,  22, 13,139],
  ["Wagner",          "NEC",             7.5,   9.5,  17, 14,140],
  ["Western Kentucky","Sun Belt",        9.5,  11.5,  20, 12,141],
  ["Louisiana",       "Sun Belt",        9.0,  11.0,  23, 12,142],
  ["Georgia St.",     "Sun Belt",        9.0,  11.0,  25,  9,143],
  ["American",        "Patriot",         8.5,  10.5,  20, 13,144],
  ["Boston U.",       "Patriot",         7.5,   9.5,  24, 11,145],
  ["Lehigh",          "Patriot",         9.0,  11.0,  20, 11,146],
  ["Bucknell",        "Patriot",         8.0,  10.0,  17, 14,147],
  ["Iona",            "MAAC",            9.5,  11.5,  18, 14,148],
  ["Quinnipiac",      "MAAC",            7.0,   9.0,  20, 12,149],
  ["Canisius",        "MAAC",            7.5,   9.5,  21, 13,150],
  ["Tulane",          "C-USA",           9.0,  11.0,  17, 16,151],
  ["UAB",             "C-USA",           9.0,  11.0,  18, 13,152],
  ["Louisiana Tech",  "C-USA",          11.5,  13.5,  29,  8,153],
  ["Old Dominion",    "C-USA",           9.0,  11.0,  18, 18,154],
  ["UTEP",            "C-USA",           9.0,  11.0,  23, 11,155],
  ["Southern Miss.",  "C-USA",           9.5,  11.5,  29,  7,156],
  ["FAU",             "C-USA",           5.0,   7.0,  10, 22,157],
  ["Marshall",        "C-USA",           7.5,   9.5,  11, 22,158],
  ["FIU",             "C-USA",           6.0,   8.0,  17, 16,159],
  ["Indiana St.",     "Missouri Valley", 9.0,  11.0,  23, 11,160],
  ["Missouri St.",    "Missouri Valley", 8.5,  10.5,  20, 13,161],
  ["Northern Iowa",   "Missouri Valley", 8.5,  10.5,  16, 15,162],
  ["Loyola Chicago",  "Missouri Valley", 6.0,   8.0,  10, 22,163],
  ["Bradley",         "Missouri Valley", 6.5,   8.5,  12, 20,164],
  ["Illinois St.",    "Missouri Valley", 9.0,  11.0,  18, 16,165],
  ["S. Illinois",     "Missouri Valley", 6.5,   8.5,  11, 21,166],
  ["Drake",           "Missouri Valley", 6.0,   8.0,  15, 16,167],
  ["Evansville",      "Missouri Valley", 9.0,  11.0,  14, 20,168],
  ["Yale",            "Ivy",             8.0,  10.0,  18, 11,169],
  ["Princeton",       "Ivy",             7.5,   9.5,  21,  9,170],
  ["Columbia",        "Ivy",             7.0,   9.0,  21, 13,171],
  ["Cornell",         "Ivy",             5.5,   7.5,   2, 26,172],
  ["Brown",           "Ivy",             6.0,   8.0,  16, 13,173],
  ["Penn",            "Ivy",             5.5,   7.5,   8, 20,174],
  ["Dartmouth",       "Ivy",             4.5,   6.5,  13, 14,175],
  ["Lipscomb",        "Atlantic Sun",    7.0,   9.0,  16, 15,176],
  ["FGCU",            "Atlantic Sun",    8.0,  10.0,  22, 13,177],
  ["High Point",      "Big South",       6.5,   8.5,  11, 19,178],
  ["Liberty",         "Big South",       6.0,   8.0,  18, 16,179],
  ["UNC Asheville",   "Big South",       7.5,   9.5,  19, 14,180],
  ["Winthrop",        "Big South",       6.5,   8.5,  17, 19,181],
  ["Radford",         "Big South",       5.5,   7.5,  10, 19,182],
  ["Long Beach St.",  "Big West",        7.5,   9.5,  15, 17,183],
  ["Hawaii",          "Big West",        7.0,   9.0,  20, 11,184],
  ["UC Davis",        "Big West",        6.0,   8.0,  16, 16,185],
  ["UC Riverside",    "Big West",        4.0,   6.0,   8, 21,186],
  ["New Mexico St.",  "WAC",            10.0,  12.0,  26, 10,187],
  ["Idaho",           "WAC",             7.5,   9.5,  16, 14,188],
  ["Seattle",         "WAC",             6.5,   8.5,  13, 17,189],
  ["UT-Pan American", "WAC",             5.0,   7.0,  18, 14,190],
  ["Nicholls St.",    "Southland",       4.5,   6.5,  10, 19,191],
  ["McNeese",         "Southland",       6.0,   8.0,  18, 11,192],
  ["Sam Houston St.", "Southland",       6.5,   8.5,  16, 14,193],
  ["S. Dakota St.",   "Summit",          7.5,   9.5,  19, 12,194],
  ["IPFW",            "Summit",          6.5,   8.5,  25, 11,195],
  ["IUPUI",           "Summit",          5.0,   7.0,   8, 22,196],
  ["Oakland",         "Horizon",         9.0,  11.0,  18, 14,197],
  ["Green Bay",       "Horizon",         9.5,  11.5,  24,  7,198],
  ["Wright St.",      "Horizon",         8.5,  10.5,  21, 13,199],
  ["Cleveland St.",   "Horizon",         7.5,   9.5,  21, 12,200],
];

const seen = new Set();
const DEDUPLICATED = RAW.filter(([team]) => {
  if (seen.has(team)) return false;
  seen.add(team);
  return true;
});

const TEAM_HISTORY = DEDUPLICATED.map(([team, conference, start, end, wins, losses, seed]) => ({
  team,
  conference,
  weeklyAdjEM: traj(start, end, seed),
  weeklyRecord: rec(wins, losses),
}));

// ── Schedules ─────────────────────────────────────────────────────────────
// HAND_CURATED is our hand-written set for top contenders. GENERATED_SCHEDULES
// is auto-pulled from KenPom for every D-I team. Hand-curated overrides win.
import { GENERATED_SCHEDULES } from "./generated/season2014.schedules";

const HAND_CURATED = {
  "UConn": [
    { week:1,  opponent:"Maryland",            opponentAdjEM:13.0, result:"W", score:"78-77",  location:"H" },
    { week:1,  opponent:"Yale",                opponentAdjEM:10.0, result:"W", score:"77-65",  location:"H" },
    { week:2,  opponent:"Detroit Mercy",       opponentAdjEM:8.0,  result:"W", score:"101-55", location:"H" },
    { week:2,  opponent:"Boston U.",           opponentAdjEM:9.5,  result:"W", score:"86-59",  location:"H" },
    { week:2,  opponent:"Indiana",             opponentAdjEM:15.5, result:"W", score:"82-59",  location:"N" },
    { week:3,  opponent:"Boston College",      opponentAdjEM:11.5, result:"W", score:"72-66",  location:"N" },
    { week:3,  opponent:"Florida",             opponentAdjEM:27.5, result:"L", score:"63-65",  location:"N" },
    { week:4,  opponent:"Stanford",            opponentAdjEM:17.0, result:"W", score:"65-64",  location:"H" },
    { week:4,  opponent:"Stony Brook",         opponentAdjEM:7.5,  result:"W", score:"79-58",  location:"H" },
    { week:5,  opponent:"Eastern Wash.",       opponentAdjEM:11.5, result:"W", score:"96-89",  location:"H" },
    { week:5,  opponent:"Washington",          opponentAdjEM:14.0, result:"L", score:"79-86",  location:"N" },
    { week:6,  opponent:"New Mexico",          opponentAdjEM:18.0, result:"W", score:"63-58",  location:"N" },
    { week:7,  opponent:"Houston",             opponentAdjEM:11.0, result:"W", score:"80-43",  location:"H" },
    { week:7,  opponent:"Harvard",             opponentAdjEM:15.0, result:"W", score:"61-56",  location:"N" },
    { week:8,  opponent:"SMU",                 opponentAdjEM:19.0, result:"L", score:"64-74",  location:"A" },
    { week:8,  opponent:"South Florida",       opponentAdjEM:9.5,  result:"W", score:"83-40",  location:"H" },
    { week:9,  opponent:"Memphis",             opponentAdjEM:20.0, result:"L", score:"75-83",  location:"A" },
    { week:9,  opponent:"Temple",              opponentAdjEM:13.0, result:"W", score:"61-46",  location:"H" },
    { week:10, opponent:"Houston",             opponentAdjEM:11.0, result:"W", score:"75-71",  location:"A" },
    { week:10, opponent:"UCF",                 opponentAdjEM:10.5, result:"W", score:"57-54",  location:"A" },
    { week:11, opponent:"Louisville",          opponentAdjEM:26.5, result:"L", score:"33-81",  location:"A" },
    { week:11, opponent:"Cincinnati",          opponentAdjEM:21.5, result:"L", score:"54-63",  location:"H" },
    { week:12, opponent:"South Florida",       opponentAdjEM:9.5,  result:"W", score:"75-50",  location:"A" },
    { week:12, opponent:"SMU",                 opponentAdjEM:19.0, result:"W", score:"67-62",  location:"H" },
    { week:13, opponent:"Memphis",             opponentAdjEM:20.0, result:"W", score:"73-67",  location:"H" },
    { week:13, opponent:"Temple",              opponentAdjEM:13.0, result:"W", score:"64-49",  location:"A" },
    { week:14, opponent:"Cincinnati",          opponentAdjEM:21.5, result:"L", score:"50-51",  location:"A" },
    { week:14, opponent:"UCF",                 opponentAdjEM:10.5, result:"W", score:"71-60",  location:"H" },
    { week:15, opponent:"Rutgers",             opponentAdjEM:13.0, result:"W", score:"66-54",  location:"A" },
    { week:15, opponent:"Harvard",             opponentAdjEM:15.0, result:"W", score:"61-56",  location:"H" },
    { week:16, opponent:"Memphis",             opponentAdjEM:20.0, result:"L", score:"66-72",  location:"A" },
    { week:16, opponent:"Houston",             opponentAdjEM:11.0, result:"W", score:"80-43",  location:"H" },
    { week:17, opponent:"Rutgers",             opponentAdjEM:13.0, result:"W", score:"79-59",  location:"H" },
    { week:17, opponent:"Louisville",          opponentAdjEM:26.5, result:"L", score:"71-81",  location:"H" },
    { week:18, opponent:"Memphis",             opponentAdjEM:20.0, result:"W", score:"72-53",  location:"N" },
    { week:18, opponent:"Cincinnati",          opponentAdjEM:21.5, result:"W", score:"58-51",  location:"N" },
    { week:18, opponent:"Louisville",          opponentAdjEM:26.5, result:"L", score:"61-71",  location:"N" },
    { week:19, opponent:"Saint Joseph's",      opponentAdjEM:16.5, result:"W", score:"89-81",  location:"N" },
    { week:19, opponent:"Villanova",           opponentAdjEM:20.5, result:"W", score:"77-65",  location:"N" },
    { week:19, opponent:"Iowa St.",            opponentAdjEM:22.0, result:"W", score:"81-76",  location:"N" },
    { week:19, opponent:"Michigan St.",        opponentAdjEM:23.0, result:"W", score:"60-54",  location:"N" },
    { week:20, opponent:"Florida",             opponentAdjEM:27.5, result:"W", score:"63-53",  location:"N" },
    { week:20, opponent:"Kentucky",            opponentAdjEM:22.0, result:"W", score:"60-54",  location:"N" },
  ],
  "Kentucky": [
    { week:1,  opponent:"UNC Asheville",       opponentAdjEM:9.5,  result:"W", score:"89-57",  location:"H" },
    { week:1,  opponent:"Northern Kentucky",   opponentAdjEM:5.0,  result:"W", score:"93-63",  location:"H" },
    { week:2,  opponent:"Robert Morris",       opponentAdjEM:9.0,  result:"W", score:"87-49",  location:"H" },
    { week:2,  opponent:"Michigan St.",        opponentAdjEM:23.0, result:"L", score:"74-78",  location:"N" },
    { week:3,  opponent:"Cleveland St.",       opponentAdjEM:9.5,  result:"W", score:"68-61",  location:"H" },
    { week:3,  opponent:"Texas-Arlington",     opponentAdjEM:7.0,  result:"W", score:"105-76", location:"H" },
    { week:3,  opponent:"Providence",          opponentAdjEM:17.5, result:"W", score:"79-65",  location:"N" },
    { week:4,  opponent:"Boise St.",           opponentAdjEM:14.0, result:"W", score:"70-55",  location:"H" },
    { week:4,  opponent:"North Carolina",      opponentAdjEM:22.5, result:"L", score:"77-82",  location:"A" },
    { week:5,  opponent:"Belmont",             opponentAdjEM:11.5, result:"W", score:"93-80",  location:"H" },
    { week:5,  opponent:"Baylor",              opponentAdjEM:17.5, result:"W", score:"67-62",  location:"H" },
    { week:6,  opponent:"Eastern Michigan",    opponentAdjEM:7.0,  result:"W", score:"81-63",  location:"H" },
    { week:7,  opponent:"Louisville",          opponentAdjEM:26.5, result:"W", score:"73-66",  location:"H" },
    { week:8,  opponent:"Mississippi St.",     opponentAdjEM:10.5, result:"W", score:"85-63",  location:"A" },
    { week:8,  opponent:"Vanderbilt",          opponentAdjEM:12.0, result:"W", score:"71-62",  location:"H" },
    { week:9,  opponent:"Arkansas",            opponentAdjEM:14.5, result:"L", score:"85-87",  location:"A" },
    { week:9,  opponent:"Tennessee",           opponentAdjEM:17.5, result:"W", score:"74-66",  location:"H" },
    { week:10, opponent:"Texas A&M",           opponentAdjEM:14.5, result:"W", score:"68-51",  location:"H" },
    { week:10, opponent:"LSU",                 opponentAdjEM:14.0, result:"L", score:"82-87",  location:"A" },
    { week:11, opponent:"Florida",             opponentAdjEM:27.5, result:"L", score:"58-69",  location:"H" },
    { week:11, opponent:"Georgia",             opponentAdjEM:12.5, result:"W", score:"79-54",  location:"H" },
    { week:12, opponent:"Missouri",            opponentAdjEM:15.5, result:"W", score:"84-79",  location:"A" },
    { week:12, opponent:"Auburn",              opponentAdjEM:11.0, result:"W", score:"64-56",  location:"H" },
    { week:13, opponent:"Ole Miss",            opponentAdjEM:14.0, result:"W", score:"80-64",  location:"H" },
    { week:13, opponent:"South Carolina",      opponentAdjEM:9.5,  result:"L", score:"67-72",  location:"A" },
    { week:14, opponent:"Mississippi St.",     opponentAdjEM:10.5, result:"W", score:"69-59",  location:"H" },
    { week:14, opponent:"Florida",             opponentAdjEM:27.5, result:"L", score:"65-69",  location:"A" },
    { week:15, opponent:"Tennessee",           opponentAdjEM:17.5, result:"L", score:"49-52",  location:"A" },
    { week:15, opponent:"Auburn",              opponentAdjEM:11.0, result:"W", score:"70-55",  location:"A" },
    { week:16, opponent:"Arkansas",            opponentAdjEM:14.5, result:"W", score:"77-76",  location:"H" },
    { week:16, opponent:"LSU",                 opponentAdjEM:14.0, result:"W", score:"77-76",  location:"H" },
    { week:17, opponent:"Alabama",             opponentAdjEM:13.5, result:"W", score:"55-48",  location:"A" },
    { week:17, opponent:"Florida",             opponentAdjEM:27.5, result:"L", score:"61-84",  location:"H" },
    { week:18, opponent:"LSU",                 opponentAdjEM:14.0, result:"W", score:"85-67",  location:"N" },
    { week:18, opponent:"Georgia",             opponentAdjEM:12.5, result:"W", score:"70-58",  location:"N" },
    { week:18, opponent:"Florida",             opponentAdjEM:27.5, result:"L", score:"60-61",  location:"N" },
    { week:19, opponent:"Kansas St.",          opponentAdjEM:15.5, result:"W", score:"56-49",  location:"N" },
    { week:19, opponent:"Wichita St.",         opponentAdjEM:24.0, result:"W", score:"78-76",  location:"N" },
    { week:19, opponent:"Louisville",          opponentAdjEM:26.5, result:"W", score:"74-69",  location:"N" },
    { week:19, opponent:"Michigan",            opponentAdjEM:22.0, result:"W", score:"75-72",  location:"N" },
    { week:20, opponent:"Wisconsin",           opponentAdjEM:25.5, result:"W", score:"74-73",  location:"N" },
    { week:20, opponent:"UConn",               opponentAdjEM:19.5, result:"L", score:"54-60",  location:"N" },
  ],
  "Florida": [
    { week:1,  opponent:"NC Central",          opponentAdjEM:9.5,  result:"W", score:"82-52",  location:"H" },
    { week:1,  opponent:"Wisconsin",           opponentAdjEM:25.5, result:"L", score:"57-59",  location:"N" },
    { week:2,  opponent:"Florida St.",         opponentAdjEM:16.5, result:"W", score:"65-49",  location:"A" },
    { week:2,  opponent:"Southern",            opponentAdjEM:5.0,  result:"W", score:"79-49",  location:"H" },
    { week:2,  opponent:"Memphis",             opponentAdjEM:20.0, result:"L", score:"71-77",  location:"A" },
    { week:3,  opponent:"Jacksonville",        opponentAdjEM:5.5,  result:"W", score:"66-46",  location:"H" },
    { week:3,  opponent:"UConn",               opponentAdjEM:19.5, result:"W", score:"65-63",  location:"N" },
    { week:4,  opponent:"Kansas",              opponentAdjEM:23.0, result:"L", score:"61-67",  location:"N" },
    { week:4,  opponent:"Richmond",            opponentAdjEM:9.0,  result:"W", score:"69-49",  location:"H" },
    { week:5,  opponent:"Fresno St.",          opponentAdjEM:10.5, result:"W", score:"62-50",  location:"H" },
    { week:5,  opponent:"Memphis",             opponentAdjEM:20.0, result:"W", score:"77-75",  location:"H" },
    { week:6,  opponent:"Savannah St.",        opponentAdjEM:5.0,  result:"W", score:"75-44",  location:"H" },
    { week:6,  opponent:"Arkansas",            opponentAdjEM:14.5, result:"W", score:"84-82",  location:"H" },
    { week:7,  opponent:"Auburn",              opponentAdjEM:11.0, result:"W", score:"83-52",  location:"H" },
    { week:7,  opponent:"Mississippi St.",     opponentAdjEM:10.5, result:"W", score:"76-65",  location:"A" },
    { week:8,  opponent:"Tennessee",           opponentAdjEM:17.5, result:"W", score:"67-41",  location:"H" },
    { week:8,  opponent:"Vanderbilt",          opponentAdjEM:12.0, result:"W", score:"75-56",  location:"A" },
    { week:9,  opponent:"Texas A&M",           opponentAdjEM:14.5, result:"W", score:"69-58",  location:"H" },
    { week:9,  opponent:"Georgia",             opponentAdjEM:12.5, result:"W", score:"72-69",  location:"A" },
    { week:10, opponent:"Missouri",            opponentAdjEM:15.5, result:"W", score:"63-52",  location:"H" },
    { week:10, opponent:"Alabama",             opponentAdjEM:13.5, result:"W", score:"68-58",  location:"A" },
    { week:11, opponent:"Kentucky",            opponentAdjEM:22.0, result:"W", score:"69-58",  location:"A" },
    { week:11, opponent:"South Carolina",      opponentAdjEM:9.5,  result:"W", score:"72-46",  location:"H" },
    { week:12, opponent:"Ole Miss",            opponentAdjEM:14.0, result:"W", score:"75-71",  location:"H" },
    { week:12, opponent:"Mississippi St.",     opponentAdjEM:10.5, result:"W", score:"64-52",  location:"H" },
    { week:13, opponent:"LSU",                 opponentAdjEM:14.0, result:"W", score:"79-61",  location:"H" },
    { week:13, opponent:"Auburn",              opponentAdjEM:11.0, result:"W", score:"68-61",  location:"A" },
    { week:14, opponent:"Tennessee",           opponentAdjEM:17.5, result:"W", score:"61-60",  location:"A" },
    { week:14, opponent:"Kentucky",            opponentAdjEM:22.0, result:"W", score:"69-65",  location:"H" },
    { week:15, opponent:"Arkansas",            opponentAdjEM:14.5, result:"W", score:"84-65",  location:"A" },
    { week:15, opponent:"South Carolina",      opponentAdjEM:9.5,  result:"W", score:"77-66",  location:"A" },
    { week:16, opponent:"Vanderbilt",          opponentAdjEM:12.0, result:"W", score:"57-54",  location:"H" },
    { week:16, opponent:"Alabama",             opponentAdjEM:13.5, result:"W", score:"78-69",  location:"H" },
    { week:17, opponent:"Kentucky",            opponentAdjEM:22.0, result:"W", score:"84-65",  location:"A" },
    { week:18, opponent:"Missouri",            opponentAdjEM:15.5, result:"W", score:"72-49",  location:"N" },
    { week:18, opponent:"Tennessee",           opponentAdjEM:17.5, result:"W", score:"56-49",  location:"N" },
    { week:18, opponent:"Kentucky",            opponentAdjEM:22.0, result:"W", score:"61-60",  location:"N" },
    { week:19, opponent:"Albany",              opponentAdjEM:10.0, result:"W", score:"67-55",  location:"N" },
    { week:19, opponent:"Pittsburgh",          opponentAdjEM:19.5, result:"W", score:"61-45",  location:"N" },
    { week:19, opponent:"UCLA",                opponentAdjEM:19.5, result:"W", score:"79-68",  location:"N" },
    { week:19, opponent:"Dayton",              opponentAdjEM:16.5, result:"W", score:"62-52",  location:"N" },
    { week:20, opponent:"UConn",               opponentAdjEM:19.5, result:"L", score:"53-63",  location:"N" },
  ],
  "Wisconsin": [
    { week:1,  opponent:"St. John's",          opponentAdjEM:14.0, result:"W", score:"75-63",  location:"H" },
    { week:1,  opponent:"Florida",             opponentAdjEM:27.5, result:"W", score:"59-57",  location:"N" },
    { week:2,  opponent:"West Virginia",       opponentAdjEM:14.5, result:"W", score:"62-67",  location:"H" },
    { week:2,  opponent:"Saint Louis",         opponentAdjEM:21.0, result:"W", score:"70-53",  location:"H" },
    { week:3,  opponent:"Virginia",            opponentAdjEM:23.0, result:"W", score:"48-38",  location:"H" },
    { week:3,  opponent:"Bowling Green",       opponentAdjEM:7.0,  result:"W", score:"82-72",  location:"H" },
    { week:4,  opponent:"Marquette",           opponentAdjEM:15.5, result:"W", score:"76-69",  location:"N" },
    { week:4,  opponent:"Eastern Kentucky",    opponentAdjEM:11.0, result:"W", score:"82-64",  location:"H" },
    { week:5,  opponent:"Milwaukee",           opponentAdjEM:9.0,  result:"W", score:"68-49",  location:"H" },
    { week:5,  opponent:"Texas A&M",           opponentAdjEM:14.5, result:"W", score:"86-79",  location:"H" },
    { week:6,  opponent:"Loyola Chicago",      opponentAdjEM:8.0,  result:"W", score:"67-63",  location:"H" },
    { week:7,  opponent:"NC State",            opponentAdjEM:15.0, result:"W", score:"83-67",  location:"H" },
    { week:8,  opponent:"Penn St.",            opponentAdjEM:12.5, result:"L", score:"57-60",  location:"A" },
    { week:8,  opponent:"Northwestern",        opponentAdjEM:11.5, result:"W", score:"76-49",  location:"H" },
    { week:9,  opponent:"Indiana",             opponentAdjEM:15.5, result:"L", score:"69-75",  location:"A" },
    { week:9,  opponent:"Illinois",            opponentAdjEM:14.5, result:"W", score:"95-70",  location:"H" },
    { week:10, opponent:"Iowa",                opponentAdjEM:21.5, result:"W", score:"75-71",  location:"A" },
    { week:10, opponent:"Minnesota",           opponentAdjEM:15.5, result:"L", score:"67-81",  location:"A" },
    { week:11, opponent:"Michigan St.",        opponentAdjEM:23.0, result:"L", score:"56-60",  location:"H" },
    { week:11, opponent:"Northwestern",        opponentAdjEM:11.5, result:"W", score:"71-50",  location:"A" },
    { week:12, opponent:"Iowa",                opponentAdjEM:21.5, result:"W", score:"79-74",  location:"H" },
    { week:12, opponent:"Ohio St.",            opponentAdjEM:20.0, result:"W", score:"59-57",  location:"H" },
    { week:13, opponent:"Michigan",            opponentAdjEM:22.0, result:"L", score:"64-77",  location:"H" },
    { week:13, opponent:"Illinois",            opponentAdjEM:14.5, result:"W", score:"75-63",  location:"A" },
    { week:14, opponent:"Michigan",            opponentAdjEM:22.0, result:"W", score:"75-62",  location:"A" },
    { week:14, opponent:"Nebraska",            opponentAdjEM:15.5, result:"L", score:"60-77",  location:"A" },
    { week:15, opponent:"Indiana",             opponentAdjEM:15.5, result:"W", score:"69-58",  location:"H" },
    { week:15, opponent:"Michigan St.",        opponentAdjEM:23.0, result:"L", score:"54-65",  location:"A" },
    { week:16, opponent:"Penn St.",            opponentAdjEM:12.5, result:"W", score:"71-49",  location:"H" },
    { week:16, opponent:"Purdue",              opponentAdjEM:12.5, result:"W", score:"76-70",  location:"A" },
    { week:17, opponent:"Minnesota",           opponentAdjEM:15.5, result:"W", score:"73-65",  location:"H" },
    { week:17, opponent:"Nebraska",            opponentAdjEM:15.5, result:"W", score:"77-68",  location:"H" },
    { week:18, opponent:"Iowa",                opponentAdjEM:21.5, result:"W", score:"75-71",  location:"N" },
    { week:18, opponent:"Michigan St.",        opponentAdjEM:23.0, result:"L", score:"50-83",  location:"N" },
    { week:19, opponent:"American",            opponentAdjEM:10.5, result:"W", score:"75-35",  location:"N" },
    { week:19, opponent:"Oregon",              opponentAdjEM:17.0, result:"W", score:"85-77",  location:"N" },
    { week:19, opponent:"Baylor",              opponentAdjEM:17.5, result:"W", score:"69-52",  location:"N" },
    { week:19, opponent:"Arizona",             opponentAdjEM:28.0, result:"W", score:"64-63",  location:"N" },
    { week:20, opponent:"Kentucky",            opponentAdjEM:22.0, result:"L", score:"73-74",  location:"N" },
  ],
  "Wichita St.": [
    { week:1,  opponent:"Western Kentucky",    opponentAdjEM:11.5, result:"W", score:"65-63",  location:"H" },
    { week:1,  opponent:"Eastern Wash.",       opponentAdjEM:11.5, result:"W", score:"77-66",  location:"H" },
    { week:2,  opponent:"William & Mary",      opponentAdjEM:9.0,  result:"W", score:"75-65",  location:"H" },
    { week:2,  opponent:"DePaul",              opponentAdjEM:9.5,  result:"W", score:"77-61",  location:"H" },
    { week:2,  opponent:"BYU",                 opponentAdjEM:17.0, result:"W", score:"68-58",  location:"N" },
    { week:3,  opponent:"Saint Louis",         opponentAdjEM:21.0, result:"W", score:"70-65",  location:"N" },
    { week:3,  opponent:"Tulsa",               opponentAdjEM:15.0, result:"W", score:"86-72",  location:"H" },
    { week:4,  opponent:"Tennessee",           opponentAdjEM:17.5, result:"W", score:"70-61",  location:"H" },
    { week:4,  opponent:"Davidson",            opponentAdjEM:12.5, result:"W", score:"71-61",  location:"H" },
    { week:5,  opponent:"Alabama",             opponentAdjEM:13.5, result:"W", score:"61-57",  location:"H" },
    { week:5,  opponent:"Air Force",           opponentAdjEM:11.5, result:"W", score:"71-54",  location:"H" },
    { week:6,  opponent:"Bradley",             opponentAdjEM:8.5,  result:"W", score:"78-63",  location:"A" },
    { week:7,  opponent:"Drake",               opponentAdjEM:8.0,  result:"W", score:"69-56",  location:"H" },
    { week:7,  opponent:"Indiana St.",         opponentAdjEM:11.0, result:"W", score:"59-54",  location:"A" },
    { week:8,  opponent:"Northern Iowa",       opponentAdjEM:10.5, result:"W", score:"55-44",  location:"H" },
    { week:8,  opponent:"Loyola Chicago",      opponentAdjEM:8.0,  result:"W", score:"83-43",  location:"A" },
    { week:9,  opponent:"Evansville",          opponentAdjEM:11.0, result:"W", score:"60-58",  location:"H" },
    { week:9,  opponent:"Missouri St.",        opponentAdjEM:10.5, result:"W", score:"77-59",  location:"H" },
    { week:10, opponent:"S. Illinois",         opponentAdjEM:8.5,  result:"W", score:"72-58",  location:"A" },
    { week:10, opponent:"Illinois St.",        opponentAdjEM:11.0, result:"W", score:"73-65",  location:"A" },
    { week:11, opponent:"Loyola Chicago",      opponentAdjEM:8.0,  result:"W", score:"81-65",  location:"H" },
    { week:11, opponent:"Bradley",             opponentAdjEM:8.5,  result:"W", score:"77-62",  location:"H" },
    { week:12, opponent:"Drake",               opponentAdjEM:8.0,  result:"W", score:"78-61",  location:"A" },
    { week:12, opponent:"Indiana St.",         opponentAdjEM:11.0, result:"W", score:"66-50",  location:"H" },
    { week:13, opponent:"Evansville",          opponentAdjEM:11.0, result:"W", score:"67-51",  location:"A" },
    { week:13, opponent:"Northern Iowa",       opponentAdjEM:10.5, result:"W", score:"67-53",  location:"A" },
    { week:14, opponent:"Missouri St.",        opponentAdjEM:10.5, result:"W", score:"72-69",  location:"A" },
    { week:14, opponent:"S. Illinois",         opponentAdjEM:8.5,  result:"W", score:"86-75",  location:"H" },
    { week:15, opponent:"Illinois St.",        opponentAdjEM:11.0, result:"W", score:"68-59",  location:"H" },
    { week:15, opponent:"Loyola Chicago",      opponentAdjEM:8.0,  result:"W", score:"66-55",  location:"A" },
    { week:16, opponent:"Bradley",             opponentAdjEM:8.5,  result:"W", score:"71-69",  location:"A" },
    { week:16, opponent:"Missouri St.",        opponentAdjEM:10.5, result:"W", score:"68-45",  location:"H" },
    { week:17, opponent:"Evansville",          opponentAdjEM:11.0, result:"W", score:"81-67",  location:"A" },
    { week:18, opponent:"Drake",               opponentAdjEM:8.0,  result:"W", score:"78-61",  location:"N" },
    { week:18, opponent:"Missouri St.",        opponentAdjEM:10.5, result:"W", score:"71-68",  location:"N" },
    { week:18, opponent:"Indiana St.",         opponentAdjEM:11.0, result:"W", score:"83-69",  location:"N" },
    { week:19, opponent:"Cal Poly",            opponentAdjEM:9.0,  result:"W", score:"64-37",  location:"N" },
    { week:19, opponent:"Kentucky",            opponentAdjEM:22.0, result:"L", score:"76-78",  location:"N" },
  ],
  "Mercer": [
    { week:1,  opponent:"Tennessee Tech",      opponentAdjEM:7.5,  result:"W", score:"86-65",  location:"H" },
    { week:1,  opponent:"Texas A&M",           opponentAdjEM:14.5, result:"L", score:"73-79",  location:"A" },
    { week:2,  opponent:"Seton Hall",          opponentAdjEM:12.5, result:"L", score:"63-66",  location:"A" },
    { week:2,  opponent:"NJIT",                opponentAdjEM:5.5,  result:"W", score:"81-50",  location:"H" },
    { week:3,  opponent:"Old Dominion",        opponentAdjEM:11.0, result:"L", score:"60-67",  location:"A" },
    { week:3,  opponent:"Reinhardt",           opponentAdjEM:3.0,  result:"W", score:"80-44",  location:"H" },
    { week:4,  opponent:"Tennessee St.",       opponentAdjEM:8.0,  result:"W", score:"77-66",  location:"A" },
    { week:4,  opponent:"Wright St.",          opponentAdjEM:10.5, result:"W", score:"58-53",  location:"H" },
    { week:5,  opponent:"Florida Atlantic",    opponentAdjEM:7.0,  result:"W", score:"81-69",  location:"A" },
    { week:5,  opponent:"Texas Southern",      opponentAdjEM:8.5,  result:"L", score:"66-71",  location:"H" },
    { week:6,  opponent:"Lipscomb",            opponentAdjEM:9.0,  result:"W", score:"75-71",  location:"A" },
    { week:7,  opponent:"FGCU",                opponentAdjEM:10.0, result:"W", score:"81-65",  location:"A" },
    { week:8,  opponent:"Northern Kentucky",   opponentAdjEM:5.0,  result:"W", score:"78-60",  location:"H" },
    { week:8,  opponent:"Stetson",             opponentAdjEM:7.0,  result:"W", score:"76-72",  location:"H" },
    { week:9,  opponent:"East Tennessee St.",  opponentAdjEM:9.0,  result:"W", score:"70-59",  location:"A" },
    { week:9,  opponent:"Jacksonville",        opponentAdjEM:5.5,  result:"W", score:"75-67",  location:"H" },
    { week:10, opponent:"USC Upstate",         opponentAdjEM:6.0,  result:"W", score:"78-69",  location:"H" },
    { week:10, opponent:"Kennesaw St.",        opponentAdjEM:5.0,  result:"W", score:"79-66",  location:"A" },
    { week:11, opponent:"Lipscomb",            opponentAdjEM:9.0,  result:"W", score:"79-72",  location:"H" },
    { week:11, opponent:"FGCU",                opponentAdjEM:10.0, result:"L", score:"63-66",  location:"H" },
    { week:12, opponent:"North Florida",       opponentAdjEM:5.0,  result:"W", score:"75-66",  location:"A" },
    { week:13, opponent:"Stetson",             opponentAdjEM:7.0,  result:"W", score:"73-58",  location:"A" },
    { week:13, opponent:"East Tennessee St.",  opponentAdjEM:9.0,  result:"W", score:"86-72",  location:"H" },
    { week:14, opponent:"Northern Kentucky",   opponentAdjEM:5.0,  result:"W", score:"82-58",  location:"A" },
    { week:14, opponent:"Jacksonville",        opponentAdjEM:5.5,  result:"W", score:"75-58",  location:"A" },
    { week:15, opponent:"Kennesaw St.",        opponentAdjEM:5.0,  result:"W", score:"80-67",  location:"H" },
    { week:15, opponent:"USC Upstate",         opponentAdjEM:6.0,  result:"W", score:"79-66",  location:"A" },
    { week:16, opponent:"FGCU",                opponentAdjEM:10.0, result:"L", score:"68-72",  location:"A" },
    { week:16, opponent:"North Florida",       opponentAdjEM:5.0,  result:"W", score:"78-69",  location:"H" },
    { week:17, opponent:"Lipscomb",            opponentAdjEM:9.0,  result:"W", score:"73-58",  location:"H" },
    { week:18, opponent:"Stetson",             opponentAdjEM:7.0,  result:"W", score:"76-65",  location:"N" },
    { week:18, opponent:"East Tennessee St.",  opponentAdjEM:9.0,  result:"W", score:"72-60",  location:"N" },
    { week:18, opponent:"FGCU",                opponentAdjEM:10.0, result:"W", score:"68-60",  location:"N" },
    { week:19, opponent:"Duke",                opponentAdjEM:22.5, result:"W", score:"78-71",  location:"N" },
    { week:19, opponent:"Tennessee",           opponentAdjEM:17.5, result:"L", score:"63-83",  location:"N" },
  ],
  "Dayton": [
    { week:1,  opponent:"IPFW",                opponentAdjEM:8.5,  result:"W", score:"72-60",  location:"H" },
    { week:1,  opponent:"USC Upstate",         opponentAdjEM:6.0,  result:"W", score:"77-65",  location:"H" },
    { week:2,  opponent:"California",          opponentAdjEM:14.0, result:"L", score:"72-82",  location:"A" },
    { week:2,  opponent:"Gonzaga",             opponentAdjEM:18.5, result:"W", score:"84-79",  location:"N" },
    { week:3,  opponent:"Baylor",              opponentAdjEM:17.5, result:"L", score:"66-77",  location:"N" },
    { week:3,  opponent:"Akron",               opponentAdjEM:11.5, result:"W", score:"81-69",  location:"H" },
    { week:4,  opponent:"Murray St.",          opponentAdjEM:10.5, result:"W", score:"72-58",  location:"H" },
    { week:4,  opponent:"Auburn",              opponentAdjEM:11.0, result:"W", score:"73-58",  location:"H" },
    { week:5,  opponent:"IUPUI",               opponentAdjEM:7.0,  result:"W", score:"79-43",  location:"H" },
    { week:6,  opponent:"Ole Miss",            opponentAdjEM:14.0, result:"L", score:"72-75",  location:"N" },
    { week:6,  opponent:"Western Carolina",    opponentAdjEM:8.0,  result:"W", score:"79-65",  location:"H" },
    { week:7,  opponent:"Western Kentucky",    opponentAdjEM:11.5, result:"W", score:"82-72",  location:"H" },
    { week:7,  opponent:"Saint Louis",         opponentAdjEM:21.0, result:"L", score:"63-71",  location:"H" },
    { week:8,  opponent:"Massachusetts",       opponentAdjEM:15.5, result:"L", score:"60-70",  location:"A" },
    { week:8,  opponent:"Rhode Island",        opponentAdjEM:13.5, result:"W", score:"68-63",  location:"H" },
    { week:9,  opponent:"La Salle",            opponentAdjEM:13.0, result:"L", score:"66-68",  location:"A" },
    { week:9,  opponent:"Saint Joseph's",      opponentAdjEM:16.5, result:"L", score:"68-78",  location:"A" },
    { week:10, opponent:"VCU",                 opponentAdjEM:18.5, result:"L", score:"55-67",  location:"H" },
    { week:10, opponent:"Duquesne",            opponentAdjEM:9.0,  result:"W", score:"75-65",  location:"A" },
    { week:11, opponent:"Saint Louis",         opponentAdjEM:21.0, result:"L", score:"68-71",  location:"A" },
    { week:11, opponent:"Fordham",             opponentAdjEM:7.5,  result:"W", score:"82-65",  location:"H" },
    { week:12, opponent:"Saint Joseph's",      opponentAdjEM:16.5, result:"W", score:"68-58",  location:"H" },
    { week:12, opponent:"George Washington",   opponentAdjEM:15.5, result:"L", score:"72-79",  location:"H" },
    { week:13, opponent:"VCU",                 opponentAdjEM:18.5, result:"L", score:"63-69",  location:"A" },
    { week:13, opponent:"Saint Bonaventure",   opponentAdjEM:11.0, result:"W", score:"73-66",  location:"A" },
    { week:14, opponent:"Massachusetts",       opponentAdjEM:15.5, result:"W", score:"82-77",  location:"H" },
    { week:14, opponent:"Rhode Island",        opponentAdjEM:13.5, result:"W", score:"83-69",  location:"A" },
    { week:15, opponent:"George Washington",   opponentAdjEM:15.5, result:"L", score:"70-71",  location:"A" },
    { week:15, opponent:"Saint Joseph's",      opponentAdjEM:16.5, result:"W", score:"76-65",  location:"A" },
    { week:16, opponent:"Duquesne",            opponentAdjEM:9.0,  result:"W", score:"71-58",  location:"H" },
    { week:16, opponent:"La Salle",            opponentAdjEM:13.0, result:"W", score:"68-58",  location:"H" },
    { week:17, opponent:"Fordham",             opponentAdjEM:7.5,  result:"W", score:"78-61",  location:"A" },
    { week:17, opponent:"Saint Louis",         opponentAdjEM:21.0, result:"W", score:"65-56",  location:"H" },
    { week:18, opponent:"Saint Joseph's",      opponentAdjEM:16.5, result:"L", score:"58-70",  location:"N" },
    { week:19, opponent:"Ohio St.",            opponentAdjEM:20.0, result:"W", score:"60-59",  location:"N" },
    { week:19, opponent:"Syracuse",            opponentAdjEM:20.5, result:"W", score:"55-53",  location:"N" },
    { week:19, opponent:"Stanford",            opponentAdjEM:17.0, result:"W", score:"82-72",  location:"N" },
    { week:19, opponent:"Florida",             opponentAdjEM:27.5, result:"L", score:"52-62",  location:"N" },
  ],
  "Arizona": [
    { week:1,  opponent:"Cal Poly",            opponentAdjEM:9.0,  result:"W", score:"77-64",  location:"H" },
    { week:1,  opponent:"Long Beach St.",      opponentAdjEM:9.5,  result:"W", score:"86-52",  location:"H" },
    { week:2,  opponent:"Drexel",              opponentAdjEM:10.5, result:"W", score:"75-43",  location:"H" },
    { week:2,  opponent:"San Diego St.",       opponentAdjEM:20.0, result:"W", score:"69-60",  location:"H" },
    { week:2,  opponent:"Duke",                opponentAdjEM:22.5, result:"W", score:"72-66",  location:"N" },
    { week:3,  opponent:"Texas Tech",          opponentAdjEM:12.5, result:"W", score:"79-46",  location:"H" },
    { week:3,  opponent:"UTEP",                opponentAdjEM:11.0, result:"W", score:"69-60",  location:"H" },
    { week:4,  opponent:"Michigan",            opponentAdjEM:22.0, result:"W", score:"72-70",  location:"A" },
    { week:4,  opponent:"New Mexico St.",      opponentAdjEM:12.0, result:"W", score:"74-48",  location:"H" },
    { week:5,  opponent:"East Tennessee St.",  opponentAdjEM:9.0,  result:"W", score:"86-55",  location:"H" },
    { week:5,  opponent:"UNLV",                opponentAdjEM:15.0, result:"W", score:"63-58",  location:"H" },
    { week:6,  opponent:"Northern Arizona",    opponentAdjEM:5.5,  result:"W", score:"77-44",  location:"H" },
    { week:7,  opponent:"Washington St.",      opponentAdjEM:10.5, result:"W", score:"72-56",  location:"H" },
    { week:7,  opponent:"Washington",          opponentAdjEM:14.0, result:"W", score:"61-54",  location:"A" },
    { week:8,  opponent:"Oregon",              opponentAdjEM:17.0, result:"W", score:"67-65",  location:"H" },
    { week:8,  opponent:"Oregon St.",          opponentAdjEM:11.5, result:"W", score:"73-44",  location:"H" },
    { week:9,  opponent:"USC",                 opponentAdjEM:9.5,  result:"W", score:"79-50",  location:"A" },
    { week:9,  opponent:"UCLA",                opponentAdjEM:19.5, result:"W", score:"79-75",  location:"A" },
    { week:10, opponent:"Stanford",            opponentAdjEM:17.0, result:"W", score:"60-57",  location:"H" },
    { week:10, opponent:"California",          opponentAdjEM:14.0, result:"L", score:"58-60",  location:"A" },
    { week:11, opponent:"Colorado",            opponentAdjEM:16.5, result:"W", score:"69-57",  location:"H" },
    { week:11, opponent:"Utah",                opponentAdjEM:15.0, result:"W", score:"65-56",  location:"H" },
    { week:12, opponent:"Oregon",              opponentAdjEM:17.0, result:"W", score:"67-65",  location:"A" },
    { week:12, opponent:"Oregon St.",          opponentAdjEM:11.5, result:"W", score:"66-46",  location:"A" },
    { week:13, opponent:"USC",                 opponentAdjEM:9.5,  result:"W", score:"77-58",  location:"H" },
    { week:13, opponent:"UCLA",                opponentAdjEM:19.5, result:"W", score:"66-64",  location:"H" },
    { week:14, opponent:"California",          opponentAdjEM:14.0, result:"W", score:"87-59",  location:"H" },
    { week:14, opponent:"Stanford",            opponentAdjEM:17.0, result:"L", score:"57-58",  location:"A" },
    { week:15, opponent:"Colorado",            opponentAdjEM:16.5, result:"W", score:"88-61",  location:"A" },
    { week:15, opponent:"Utah",                opponentAdjEM:15.0, result:"W", score:"63-57",  location:"A" },
    { week:16, opponent:"Washington",          opponentAdjEM:14.0, result:"W", score:"69-66",  location:"H" },
    { week:16, opponent:"Washington St.",      opponentAdjEM:10.5, result:"W", score:"91-68",  location:"A" },
    { week:17, opponent:"Oregon",              opponentAdjEM:17.0, result:"L", score:"64-67",  location:"A" },
    { week:18, opponent:"Utah",                opponentAdjEM:15.0, result:"W", score:"71-39",  location:"N" },
    { week:18, opponent:"Colorado",            opponentAdjEM:16.5, result:"W", score:"63-43",  location:"N" },
    { week:18, opponent:"UCLA",                opponentAdjEM:19.5, result:"L", score:"75-66",  location:"N" },
    { week:19, opponent:"Weber St.",           opponentAdjEM:10.5, result:"W", score:"68-59",  location:"N" },
    { week:19, opponent:"Gonzaga",             opponentAdjEM:18.5, result:"W", score:"84-61",  location:"N" },
    { week:19, opponent:"San Diego St.",       opponentAdjEM:20.0, result:"W", score:"70-64",  location:"N" },
    { week:19, opponent:"Wisconsin",           opponentAdjEM:25.5, result:"L", score:"63-64",  location:"N" },
  ],
};

const SCHEDULES = { ...GENERATED_SCHEDULES, ...HAND_CURATED };

// ── Dividend events ────────────────────────────────────────────────────────
const DIVIDEND_EVENTS = [
  // UConn — National Champions (7-seed, 3rd-lowest ever)
  { team:"UConn", week:1,  event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:1,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:2,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:2,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:3,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:4,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:4,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:5,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:6,  event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:7,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:7,  event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:8,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:9,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:10, event:"Wins a game",                   value:1  },
  { team:"UConn", week:10, event:"Wins a game",                   value:1  },
  { team:"UConn", week:12, event:"Wins a game",                   value:1  },
  { team:"UConn", week:12, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:13, event:"Wins a game",                   value:1  },
  { team:"UConn", week:14, event:"Wins a game",                   value:1  },
  { team:"UConn", week:15, event:"Wins a game",                   value:1  },
  { team:"UConn", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:16, event:"Wins a game",                   value:1  },
  { team:"UConn", week:17, event:"Wins a game",                   value:1  },
  { team:"UConn", week:18, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:18, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:18, event:"Wins American tournament",      value:15 },
  { team:"UConn", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"UConn", week:19, event:"Wins a game",                   value:1  },
  { team:"UConn", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"UConn", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"UConn", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"UConn", week:20, event:"Reaches Final Four",             value:80 },
  { team:"UConn", week:20, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:20, event:"Wins NCAA Championship",         value:150},

  // Kentucky — Runner-up (8-seed, all freshmen)
  { team:"Kentucky", week:1,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:1,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:2,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:3,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:3,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:3,  event:"Wins a top-25 team",         value:5  },
  { team:"Kentucky", week:4,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:5,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:5,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:6,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:7,  event:"Wins a top-25 team",         value:5  },
  { team:"Kentucky", week:8,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:8,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:9,  event:"Wins a game",                value:1  },
  { team:"Kentucky", week:10, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:11, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:12, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:12, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:13, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:14, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:16, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:16, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:17, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:18, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:18, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"Kentucky", week:19, event:"Wins a game",                value:1  },
  { team:"Kentucky", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Kentucky", week:19, event:"Wins a top-25 team",         value:5  },
  { team:"Kentucky", week:19, event:"Reaches Sweet Sixteen",       value:20 },
  { team:"Kentucky", week:19, event:"Wins a top-25 team",         value:5  },
  { team:"Kentucky", week:19, event:"Reaches Elite Eight",         value:40 },
  { team:"Kentucky", week:19, event:"Wins a top-25 team",         value:5  },
  { team:"Kentucky", week:20, event:"Reaches Final Four",          value:80 },
  { team:"Kentucky", week:20, event:"Wins a top-25 team",         value:5  },
  { team:"Kentucky", week:20, event:"NCAA Championship runner-up", value:100},

  // Florida — Final Four (#1 overall seed, 18-0 SEC)
  { team:"Florida", week:1,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:2,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:2,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:3,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:3,  event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:4,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:5,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:5,  event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:6,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:6,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:7,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:7,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:8,  event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:8,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:9,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:9,  event:"Wins a game",                  value:1  },
  { team:"Florida", week:10, event:"Wins a game",                  value:1  },
  { team:"Florida", week:10, event:"Wins a game",                  value:1  },
  { team:"Florida", week:11, event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:11, event:"Wins a game",                  value:1  },
  { team:"Florida", week:12, event:"Wins a game",                  value:1  },
  { team:"Florida", week:12, event:"Wins a game",                  value:1  },
  { team:"Florida", week:13, event:"Wins a game",                  value:1  },
  { team:"Florida", week:13, event:"Wins a game",                  value:1  },
  { team:"Florida", week:14, event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:14, event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:15, event:"Wins a game",                  value:1  },
  { team:"Florida", week:15, event:"Wins a game",                  value:1  },
  { team:"Florida", week:16, event:"Wins a game",                  value:1  },
  { team:"Florida", week:16, event:"Wins a game",                  value:1  },
  { team:"Florida", week:17, event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:17, event:"Wins outright league title",   value:30 },
  { team:"Florida", week:18, event:"Wins SEC tournament",          value:15 },
  { team:"Florida", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Florida", week:19, event:"Wins a game",                  value:1  },
  { team:"Florida", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Florida", week:19, event:"Reaches Sweet Sixteen",         value:20 },
  { team:"Florida", week:19, event:"Reaches Elite Eight",           value:40 },
  { team:"Florida", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Florida", week:20, event:"Reaches Final Four",            value:80 },

  // Wisconsin — Final Four
  { team:"Wisconsin", week:1,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:1,  event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:2,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:2,  event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:3,  event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:3,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:4,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:4,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:5,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:5,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:6,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:7,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:8,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:9,  event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:10, event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:11, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:12, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:12, event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:13, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:14, event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:15, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:16, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:16, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:17, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:17, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:18, event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"Wisconsin", week:19, event:"Wins a game",                value:1  },
  { team:"Wisconsin", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Wisconsin", week:19, event:"Reaches Sweet Sixteen",       value:20 },
  { team:"Wisconsin", week:19, event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:19, event:"Reaches Elite Eight",         value:40 },
  { team:"Wisconsin", week:19, event:"Wins a top-25 team",         value:5  },
  { team:"Wisconsin", week:20, event:"Reaches Final Four",          value:80 },

  // Wichita St. — 35-0 reg season, R32 loss to Kentucky
  { team:"Wichita St.", week:17, event:"Wins outright league title",value:30 },
  { team:"Wichita St.", week:18, event:"Wins MVC tournament",       value:15 },
  { team:"Wichita St.", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Wichita St.", week:19, event:"Wins a game",               value:1  },
  { team:"Wichita St.", week:19, event:"Reaches Round of 32",        value:10 },

  // Mercer — beat Duke (R64)
  { team:"Mercer", week:18, event:"Wins Atlantic Sun tournament",   value:15 },
  { team:"Mercer", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Mercer", week:19, event:"Wins a top-25 team",             value:5  },
  { team:"Mercer", week:19, event:"Wins a game",                    value:1  },
  { team:"Mercer", week:19, event:"Reaches Round of 32",             value:10 },

  // Dayton — Elite Eight (11-seed)
  { team:"Dayton", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Dayton", week:19, event:"Wins a game",                    value:1  },
  { team:"Dayton", week:19, event:"Wins a top-25 team",             value:5  },
  { team:"Dayton", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Dayton", week:19, event:"Wins a top-25 team",             value:5  },
  { team:"Dayton", week:19, event:"Reaches Sweet Sixteen",           value:20 },
  { team:"Dayton", week:19, event:"Reaches Elite Eight",             value:40 },

  // Arizona — Elite Eight (overtime loss to Wisconsin)
  { team:"Arizona", week:2,  event:"Wins a top-25 team",             value:5  },
  { team:"Arizona", week:2,  event:"Wins a top-25 team",             value:5  },
  { team:"Arizona", week:4,  event:"Wins a top-25 team",             value:5  },
  { team:"Arizona", week:9,  event:"Wins a top-25 team",             value:5  },
  { team:"Arizona", week:13, event:"Wins a top-25 team",             value:5  },
  { team:"Arizona", week:17, event:"Wins outright league title",     value:30 },
  { team:"Arizona", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Arizona", week:19, event:"Wins a game",                    value:1  },
  { team:"Arizona", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Arizona", week:19, event:"Reaches Sweet Sixteen",           value:20 },
  { team:"Arizona", week:19, event:"Wins a top-25 team",             value:5  },
  { team:"Arizona", week:19, event:"Reaches Elite Eight",             value:40 },

  // Stanford — Sweet 16 (10-seed, beat Kansas)
  { team:"Stanford", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Stanford", week:19, event:"Wins a game",                   value:1  },
  { team:"Stanford", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Stanford", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Stanford", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Michigan State — Elite Eight
  { team:"Michigan St.", week:18, event:"Wins Big Ten tournament",  value:15 },
  { team:"Michigan St.", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"Michigan St.", week:19, event:"Wins a game",               value:1  },
  { team:"Michigan St.", week:19, event:"Reaches Round of 32",        value:10 },
  { team:"Michigan St.", week:19, event:"Reaches Sweet Sixteen",      value:20 },
  { team:"Michigan St.", week:19, event:"Wins a top-25 team",        value:5  },
  { team:"Michigan St.", week:19, event:"Reaches Elite Eight",        value:40 },

  // Iowa St. — Sweet 16
  { team:"Iowa St.", week:18, event:"Wins Big 12 tournament",       value:15 },
  { team:"Iowa St.", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Iowa St.", week:19, event:"Wins a game",                  value:1  },
  { team:"Iowa St.", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Iowa St.", week:19, event:"Reaches Sweet Sixteen",         value:20 },

  // Michigan — Elite Eight
  { team:"Michigan", week:17, event:"Wins outright league title",   value:30 },
  { team:"Michigan", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Michigan", week:19, event:"Wins a game",                  value:1  },
  { team:"Michigan", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Michigan", week:19, event:"Reaches Sweet Sixteen",         value:20 },
  { team:"Michigan", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Michigan", week:19, event:"Reaches Elite Eight",           value:40 },

  // Louisville — Sweet 16 (defending champs)
  { team:"Louisville", week:18, event:"Wins American tournament",   value:15 },
  { team:"Louisville", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Louisville", week:19, event:"Wins a game",                value:1  },
  { team:"Louisville", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Louisville", week:19, event:"Reaches Sweet Sixteen",       value:20 },

  // Virginia — Sweet 16 (#1 seed East, lost to MSU)
  { team:"Virginia", week:17, event:"Wins outright league title",   value:30 },
  { team:"Virginia", week:18, event:"Wins ACC tournament",          value:15 },
  { team:"Virginia", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Virginia", week:19, event:"Wins a game",                  value:1  },
  { team:"Virginia", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Virginia", week:19, event:"Reaches Sweet Sixteen",         value:20 },

  // Baylor — Sweet 16
  { team:"Baylor", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Baylor", week:19, event:"Wins a game",                    value:1  },
  { team:"Baylor", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Baylor", week:19, event:"Reaches Sweet Sixteen",           value:20 },

  // UCLA — Sweet 16
  { team:"UCLA", week:18, event:"Wins Pac-12 tournament",           value:15 },
  { team:"UCLA", week:19, event:"Makes the NCAA tournament",       value:10 },
  { team:"UCLA", week:19, event:"Wins a game",                      value:1  },
  { team:"UCLA", week:19, event:"Reaches Round of 32",               value:10 },
  { team:"UCLA", week:19, event:"Reaches Sweet Sixteen",             value:20 },

  // San Diego St. — Sweet 16
  { team:"San Diego St.", week:17, event:"Wins outright league title",value:30 },
  { team:"San Diego St.", week:18, event:"Wins MWC tournament",     value:15 },
  { team:"San Diego St.", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"San Diego St.", week:19, event:"Wins a game",             value:1  },
  { team:"San Diego St.", week:19, event:"Reaches Round of 32",      value:10 },
  { team:"San Diego St.", week:19, event:"Reaches Sweet Sixteen",    value:20 },

  // Tennessee — Sweet 16 (came out of First Four)
  { team:"Tennessee", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"Tennessee", week:19, event:"Wins a game",                 value:1  },
  { team:"Tennessee", week:19, event:"Wins a game",                 value:1  },
  { team:"Tennessee", week:19, event:"Reaches Round of 32",          value:10 },
  { team:"Tennessee", week:19, event:"Reaches Sweet Sixteen",        value:20 },

  // Other tournament teams
  { team:"Duke", week:19, event:"Makes the NCAA tournament",       value:10 },
  { team:"Kansas", week:18, event:"Wins outright league title",    value:30 },
  { team:"Kansas", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Kansas", week:19, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Syracuse", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Syracuse", week:19, event:"Wins a game",                 value:1  },
  { team:"Syracuse", week:19, event:"Reaches Round of 32",          value:10 },
  { team:"Creighton", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"Creighton", week:19, event:"Wins a game",                value:1  },
  { team:"Creighton", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Saint Louis", week:17, event:"Wins outright league title",value:30 },
  { team:"Saint Louis", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"Saint Louis", week:19, event:"Wins a game",              value:1  },
  { team:"Saint Louis", week:19, event:"Reaches Round of 32",       value:10 },
  { team:"Saint Joseph's", week:18, event:"Wins Atlantic 10 tournament",value:15},
  { team:"Saint Joseph's", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"VCU", week:19, event:"Makes the NCAA tournament",        value:10 },
  { team:"Cincinnati", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"North Carolina", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"North Carolina", week:19, event:"Wins a game",            value:1  },
  { team:"North Carolina", week:19, event:"Reaches Round of 32",     value:10 },
  { team:"Pittsburgh", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Pittsburgh", week:19, event:"Wins a game",                value:1  },
  { team:"Pittsburgh", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Memphis", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Memphis", week:19, event:"Wins a game",                  value:1  },
  { team:"Memphis", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Texas", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Texas", week:19, event:"Wins a game",                    value:1  },
  { team:"Texas", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Oklahoma", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Ohio St.", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Iowa", week:19, event:"Makes the NCAA tournament",       value:10 },
  { team:"Villanova", week:17, event:"Wins outright league title", value:30 },
  { team:"Villanova", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Villanova", week:19, event:"Wins a game",                value:1  },
  { team:"Villanova", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"George Washington", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"UMass", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Tulsa", week:18, event:"Wins C-USA tournament",          value:15 },
  { team:"Tulsa", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Harvard", week:17, event:"Wins outright league title",   value:30 },
  { team:"Harvard", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Harvard", week:19, event:"Wins a game",                  value:1  },
  { team:"Harvard", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Harvard", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"NC State", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"NC State", week:19, event:"Wins a game",                 value:1  },
  { team:"Stephen F. Austin", week:18, event:"Wins Southland tournament",value:15},
  { team:"Stephen F. Austin", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Stephen F. Austin", week:19, event:"Wins a game",         value:1  },
  { team:"Stephen F. Austin", week:19, event:"Reaches Round of 32", value:10 },
  { team:"Manhattan", week:18, event:"Wins MAAC tournament",       value:15 },
  { team:"Manhattan", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"North Dakota St.", week:18, event:"Wins Summit tournament",value:15},
  { team:"North Dakota St.", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"North Dakota St.", week:19, event:"Wins a top-25 team",   value:5  },
  { team:"North Dakota St.", week:19, event:"Wins a game",          value:1  },
  { team:"North Dakota St.", week:19, event:"Reaches Round of 32",   value:10 },
  { team:"Western Mich.", week:18, event:"Wins MAC tournament",    value:15 },
  { team:"Western Mich.", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Eastern Kentucky", week:18, event:"Wins OVC tournament", value:15 },
  { team:"Eastern Kentucky", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Coastal Carolina", week:18, event:"Wins Big South tournament",value:15},
  { team:"Coastal Carolina", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Albany", week:18, event:"Wins America East tournament",  value:15 },
  { team:"Albany", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Cal Poly", week:18, event:"Wins Big West tournament",    value:15 },
  { team:"Cal Poly", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Cal Poly", week:19, event:"Wins a game",                  value:1  },
  { team:"Delaware", week:18, event:"Wins CAA tournament",         value:15 },
  { team:"Delaware", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Wofford", week:18, event:"Wins Southern tournament",     value:15 },
  { team:"Wofford", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Weber St.", week:18, event:"Wins Big Sky tournament",    value:15 },
  { team:"Weber St.", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"NC Central", week:17, event:"Wins outright league title",value:30 },
  { team:"NC Central", week:19, event:"Makes other postseason",    value:5  },
  { team:"Texas Southern", week:18, event:"Wins SWAC tournament",  value:15 },
  { team:"Texas Southern", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Mt. St. Mary's", week:18, event:"Wins NEC tournament",   value:15 },
  { team:"Mt. St. Mary's", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Mt. St. Mary's", week:19, event:"Wins a game",            value:1  },
  { team:"Western Kentucky", week:18, event:"Wins Sun Belt tournament",value:15},
  { team:"Western Kentucky", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"American", week:18, event:"Wins Patriot tournament",     value:15 },
  { team:"American", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"New Mexico", week:17, event:"Wins outright league title",value:30 },
  { team:"New Mexico", week:18, event:"Wins MWC tournament",       value:15 },
  { team:"New Mexico", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"BYU", week:19, event:"Makes the NCAA tournament",        value:10 },
  { team:"Gonzaga", week:18, event:"Wins WCC tournament",          value:15 },
  { team:"Gonzaga", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Gonzaga", week:19, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Oklahoma St.", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"Kansas St.", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Colorado", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Arizona St.", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"Providence", week:18, event:"Wins Big East tournament",  value:15 },
  { team:"Providence", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"New Mexico St.", week:18, event:"Wins WAC tournament",   value:15 },
  { team:"New Mexico St.", week:19, event:"Makes the NCAA tournament",value:10},
];

const EVENTS_BY_WEEK = {};
for (const evt of DIVIDEND_EVENTS) {
  if (!EVENTS_BY_WEEK[evt.week]) EVENTS_BY_WEEK[evt.week] = [];
  EVENTS_BY_WEEK[evt.week].push(evt);
}

export const SEASON_2014 = {
  id: "2013-14",
  label: "2013-14",
  champion: "UConn",
  WEEKS,
  TEAM_HISTORY,
  SCHEDULES,
  DIVIDEND_EVENTS,
  EVENTS_BY_WEEK,
};
