// season2023.js — 2022-23 college basketball season
// Champion: UConn (defeated San Diego State 76-59)
// Notable: FAU & Princeton Cinderella runs, Purdue lost to FDU in 1st round
//
// AdjEM values are season-accurate approximations based on published KenPom
// end/mid-season ratings. Weekly values use smooth trajectories with seeded variance.

function traj(start, end, seed) {
  const n = 20;
  const out = [];
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1);
    const base = start + (end - start) * t;
    const noise = (Math.sin(i * seed * 2.3 + seed) + Math.cos(i * seed * 1.7)) * 0.35;
    out.push(Math.round((base + noise) * 100) / 100);
  }
  out[n - 1] = end;
  return out;
}

function rec(w, l) {
  const n = 20;
  return Array.from({ length: n }, (_, i) => {
    const t = i / (n - 1);
    return `${Math.round(w * t)}-${Math.round(l * t)}`;
  });
}

const WEEKS = [
  "Week 1 (Nov 7)",  "Week 2 (Nov 14)", "Week 3 (Nov 21)", "Week 4 (Nov 28)",
  "Week 5 (Dec 5)",  "Week 6 (Dec 12)", "Week 7 (Dec 19)", "Week 8 (Jan 2)",
  "Week 9 (Jan 9)",  "Week 10 (Jan 16)","Week 11 (Jan 23)","Week 12 (Jan 30)",
  "Week 13 (Feb 6)", "Week 14 (Feb 13)","Week 15 (Feb 20)","Week 16 (Feb 27)",
  "Week 17 (Mar 6)", "Week 18 (Mar 11)","Week 19 (Mar 18)","Week 20 (Mar 25)",
];

// [team, conference, startAdjEM, endAdjEM, wins, losses, seed]
const RAW = [
  // ── Power conferences — elite ─────────────────────────────────────────────
  ["Houston",         "American",       24.0,  31.6,  33,  4,  1],
  ["Alabama",         "SEC",            22.0,  29.5,  31,  6,  2],
  ["UCLA",            "Pac-12",         20.0,  26.5,  31,  6,  3],
  ["Texas",           "Big 12",         20.5,  27.4,  29, 10,  4],
  ["Purdue",          "Big Ten",        21.0,  26.7,  29,  6,  5],
  ["Tennessee",       "SEC",            20.0,  25.5,  25, 11,  6],
  ["Kansas",          "Big 12",         21.5,  25.3,  28,  8,  7],
  ["UConn",           "Big East",       19.5,  27.9,  31,  8,  8],
  ["Marquette",       "Big East",       16.0,  23.2,  29,  7,  9],
  ["Gonzaga",         "WCC",            19.0,  23.8,  31,  6, 10],
  ["Kentucky",        "SEC",            17.0,  22.0,  22, 12, 11],
  ["Arizona",         "Pac-12",         19.0,  23.6,  28,  7, 12],
  ["San Diego St.",   "Mountain West",  16.0,  22.0,  32,  7, 13],
  ["Baylor",          "Big 12",         17.5,  22.4,  23, 11, 14],
  ["Saint Mary's",    "WCC",            15.5,  20.8,  27,  8, 15],
  ["Creighton",       "Big East",       16.5,  22.6,  24, 13, 16],
  ["Duke",            "ACC",            15.5,  21.0,  27,  9, 17],
  ["Iowa St.",        "Big 12",         16.0,  21.6,  19, 14, 18],
  ["Kansas St.",      "Big 12",         13.5,  20.4,  26, 10, 19],
  ["Indiana",         "Big Ten",        15.0,  20.5,  23, 12, 20],
  ["Miami (FL)",      "ACC",            14.0,  19.8,  29,  8, 21],
  ["Florida Atlantic","C-USA",          12.0,  18.6,  35,  4, 22],
  ["Virginia",        "ACC",            14.5,  19.6,  25,  8, 23],
  ["Xavier",          "Big East",       14.5,  19.4,  27, 10, 24],
  ["Northwestern",    "Big Ten",        13.0,  18.0,  22, 12, 25],
  ["Illinois",        "Big Ten",        15.0,  19.5,  20, 13, 26],
  ["Auburn",          "SEC",            13.5,  18.8,  21, 13, 27],
  ["Iowa",            "Big Ten",        14.0,  18.6,  19, 14, 28],
  ["TCU",             "Big 12",         15.0,  19.7,  22, 13, 29],
  ["Memphis",         "American",       12.0,  17.5,  26,  9, 30],
  ["NC State",        "ACC",            11.5,  16.6,  23, 11, 31],
  ["Oral Roberts",    "Summit",         10.0,  15.0,  30,  5, 32],
  ["Charleston",      "CAA",            11.0,  15.8,  31,  4, 33],
  ["Maryland",        "Big Ten",        12.5,  17.5,  22, 13, 34],
  ["Michigan St.",    "Big Ten",        14.0,  18.2,  21, 13, 35],
  ["West Virginia",   "Big 12",         13.0,  17.6,  19, 15, 36],
  ["Texas A&M",       "SEC",            12.0,  17.1,  25, 10, 37],
  ["Providence",      "Big East",       12.5,  17.2,  21, 12, 38],
  ["Mississippi St.", "SEC",            11.0,  16.0,  21, 13, 39],
  ["Pittsburgh",      "ACC",            10.5,  15.6,  24, 12, 40],
  ["Penn St.",        "Big Ten",        11.5,  16.4,  23, 14, 41],
  ["Arkansas",        "SEC",            13.5,  18.0,  22, 14, 42],
  ["Missouri",        "SEC",            12.0,  16.8,  25, 10, 43],
  ["Boise St.",       "Mountain West",  10.5,  14.8,  24,  9, 44],
  ["Utah St.",        "Mountain West",  11.0,  15.6,  26,  9, 45],
  ["VCU",             "Atlantic 10",    11.0,  15.2,  27,  8, 46],
  ["Iona",            "MAAC",           10.0,  14.5,  27,  8, 47],
  ["Princeton",       "Ivy",             8.5,  13.5,  23,  9, 48],
  ["Furman",          "Southern",       10.5,  15.0,  28,  8, 49],
  ["Drake",           "Missouri Valley", 9.5,  13.8,  27,  8, 50],
  ["Kent St.",        "MAC",             9.0,  13.2,  28,  7, 51],
  ["Vermont",         "America East",    9.0,  13.0,  23, 11, 52],
  ["Colgate",         "Patriot",         8.5,  12.6,  26,  9, 53],
  ["UNC Asheville",   "Big South",       7.5,  11.5,  27,  8, 54],
  ["Texas Southern",  "SWAC",            5.5,   9.0,  14, 21, 55],
  ["Northern Kentucky","Horizon",        7.0,  11.0,  22, 13, 56],
  ["Grand Canyon",    "WAC",             8.5,  12.5,  24, 12, 57],
  ["Montana St.",     "Big Sky",         7.5,  11.5,  25, 10, 58],
  ["Howard",          "MEAC",            5.5,   9.0,  22, 13, 59],
  ["Louisiana",       "Sun Belt",        7.5,  11.5,  26,  8, 60],
  ["Kennesaw St.",    "ASUN",            6.5,  10.5,  26,  9, 61],
  ["FDU",             "NEC",             4.5,   8.5,  21, 16, 62],
  ["Texas A&M-CC",    "Southland",       7.0,  10.5,  24, 11, 63],

  // ── Power conferences — middle/lower ──────────────────────────────────────
  ["North Carolina",  "ACC",            16.5,  18.5,  20, 13, 64],
  ["Wisconsin",       "Big Ten",        12.0,  16.5,  17, 15, 65],
  ["Ohio St.",        "Big Ten",        13.5,  17.0,  16, 19, 66],
  ["Michigan",        "Big Ten",        12.5,  16.2,  18, 16, 67],
  ["Rutgers",         "Big Ten",        13.0,  17.5,  19, 15, 68],
  ["Nebraska",        "Big Ten",        10.0,  14.0,  16, 16, 69],
  ["Minnesota",       "Big Ten",         8.0,  12.0,   9, 22, 70],
  ["Florida",         "SEC",            12.0,  16.5,  16, 17, 71],
  ["South Carolina",  "SEC",             8.5,  12.5,  11, 21, 72],
  ["Vanderbilt",      "SEC",             9.0,  13.5,  22, 15, 73],
  ["LSU",             "SEC",            11.0,  15.0,  14, 19, 74],
  ["Ole Miss",        "SEC",             9.5,  13.5,  12, 21, 75],
  ["Georgia",         "SEC",            10.0,  14.0,  16, 16, 76],
  ["Oklahoma St.",    "Big 12",         11.5,  15.8,  20, 16, 77],
  ["Oklahoma",        "Big 12",         10.5,  14.5,  15, 17, 78],
  ["Texas Tech",      "Big 12",         10.0,  14.0,  16, 16, 79],
  ["BYU",             "WCC",            10.0,  14.0,  19, 15, 80],
  ["Washington St.",  "Pac-12",         10.0,  14.5,  17, 17, 81],
  ["USC",             "Pac-12",         12.5,  17.0,  22, 11, 82],
  ["Utah",            "Pac-12",         10.5,  14.5,  17, 15, 83],
  ["Oregon",          "Pac-12",         11.0,  14.8,  21, 15, 84],
  ["Colorado",        "Pac-12",         10.5,  14.0,  18, 17, 85],
  ["Stanford",        "Pac-12",         10.0,  13.5,  14, 19, 86],
  ["Washington",      "Pac-12",          9.0,  13.0,  16, 16, 87],
  ["Arizona St.",     "Pac-12",         10.5,  14.5,  23, 13, 88],
  ["Oregon St.",      "Pac-12",          7.0,  10.5,  11, 21, 89],
  ["California",      "Pac-12",          5.0,   8.0,   3, 29, 90],
  ["Wake Forest",     "ACC",             9.5,  13.5,  19, 14, 91],
  ["Clemson",         "ACC",            11.0,  15.0,  23, 11, 92],
  ["Florida St.",     "ACC",             8.5,  12.0,   9, 23, 93],
  ["Syracuse",        "ACC",             9.0,  13.0,  17, 15, 94],
  ["Virginia Tech",   "ACC",            11.0,  15.0,  19, 15, 95],
  ["Notre Dame",      "ACC",             8.0,  12.0,  11, 21, 96],
  ["Louisville",      "ACC",             4.5,   8.0,   4, 28, 97],
  ["Boston College",  "ACC",             7.5,  11.5,  16, 17, 98],
  ["Georgia Tech",    "ACC",             6.5,  10.5,  15, 18, 99],
  ["Villanova",       "Big East",       11.0,  14.5,  17, 17,100],
  ["St. John's",      "Big East",       10.0,  14.0,  18, 15,101],
  ["Seton Hall",      "Big East",        9.5,  13.5,  17, 16,102],
  ["Butler",          "Big East",        7.5,  11.5,  14, 19,103],
  ["DePaul",          "Big East",        2.0,   5.0,   9, 23,104],
  ["Georgetown",      "Big East",        2.5,   6.0,   7, 25,105],
  ["UCF",             "American",       10.5,  14.8,  21, 14,106],
  ["Cincinnati",      "American",       10.0,  14.5,  20, 13,107],
  ["Tulane",          "American",        9.0,  13.0,  20, 11,108],

  // ── Mid-majors and below ──────────────────────────────────────────────────
  ["Liberty",         "ASUN",            7.5,  11.0,  26,  9,109],
  ["Florida Gulf Coast","ASUN",          6.5,  10.0,  17, 17,110],
  ["Lipscomb",        "ASUN",            6.5,  10.5,  17, 15,111],
  ["Stetson",         "ASUN",            5.0,   8.5,  17, 16,112],
  ["Jacksonville St.","ASUN",            7.0,  11.0,  20, 14,113],
  ["Bellarmine",      "ASUN",            5.0,   8.5,  15, 17,114],
  ["Eastern Kentucky","ASUN",            5.5,   9.0,  16, 16,115],
  ["North Alabama",   "ASUN",            4.5,   8.0,  16, 16,116],
  ["Central Arkansas","ASUN",            5.0,   8.5,  16, 17,117],
  ["Queens",          "ASUN",            4.5,   8.0,  14, 18,118],
  ["Stony Brook",     "America East",    4.5,   8.0,  10, 21,119],
  ["UMBC",            "America East",    5.0,   8.5,  19, 14,120],
  ["UMass-Lowell",    "America East",    5.5,   9.0,  21, 11,121],
  ["Bryant",          "America East",    5.0,   8.5,  17, 16,122],
  ["NJIT",            "America East",    4.5,   8.0,  13, 19,123],
  ["Albany",          "America East",    4.0,   7.5,   8, 23,124],
  ["New Hampshire",   "America East",    3.0,   6.0,  15, 13,125],
  ["Hartford",        "America East",    2.5,   5.5,   5, 25,126],
  ["Maine",           "America East",    3.5,   7.0,  14, 17,127],
  ["UC Irvine",       "Big West",        7.5,  11.5,  23, 12,128],
  ["UC Santa Barbara","Big West",        7.0,  11.0,  27,  8,129],
  ["Hawaii",          "Big West",        7.0,  11.0,  21, 10,130],
  ["UC Davis",        "Big West",        5.5,   9.0,  19, 13,131],
  ["Long Beach St.",  "Big West",        6.0,  10.0,  17, 17,132],
  ["UC Riverside",    "Big West",        5.5,   9.0,  21, 12,133],
  ["Cal Poly",        "Big West",        4.0,   7.5,   9, 21,134],
  ["UC San Diego",    "Big West",        4.5,   8.0,  10, 22,135],
  ["Cal St. Fullerton","Big West",       6.0,  10.0,  20, 12,136],
  ["Cal St. Northridge","Big West",      5.0,   8.5,   9, 22,137],
  ["CS Bakersfield",  "Big West",        4.0,   7.5,  10, 22,138],
  ["Charleston",      "CAA",            11.0,  15.8,  31,  4,139],
  ["Hofstra",         "CAA",             9.5,  13.5,  23, 11,140],
  ["UNC Wilmington",  "CAA",             8.0,  12.0,  24, 10,141],
  ["Towson",          "CAA",             7.0,  11.0,  21, 12,142],
  ["Drexel",          "CAA",             7.0,  11.0,  17, 15,143],
  ["Delaware",        "CAA",             6.0,  10.0,  17, 16,144],
  ["Northeastern",    "CAA",             6.5,  10.5,  10, 21,145],
  ["Stony Brook",     "CAA",             5.0,   8.5,  10, 21,146],
  ["Elon",            "CAA",             5.5,   9.0,   8, 24,147],
  ["William & Mary",  "CAA",             5.0,   8.5,   6, 25,148],
  ["Hampton",         "CAA",             4.5,   8.0,  10, 22,149],
  ["FIU",             "C-USA",           5.0,   8.5,  14, 18,150],
  ["UAB",             "C-USA",           9.5,  13.5,  25, 10,151],
  ["UTSA",            "C-USA",           5.5,   9.0,  10, 22,152],
  ["UTEP",            "C-USA",           7.0,  11.0,  14, 17,153],
  ["Western Ky.",     "C-USA",           6.0,  10.0,  17, 16,154],
  ["North Texas",     "C-USA",           9.5,  13.5,  31,  7,155],
  ["Charlotte",       "C-USA",           6.0,  10.0,  13, 19,156],
  ["Rice",            "C-USA",           7.5,  11.5,  20, 14,157],
  ["Middle Tennessee","C-USA",           7.0,  11.0,  19, 16,158],
  ["Louisiana Tech",  "C-USA",           6.5,  10.5,  16, 16,159],
  ["Wright St.",      "Horizon",         7.0,  11.0,  18, 14,160],
  ["Cleveland St.",   "Horizon",         6.5,  10.5,  21, 14,161],
  ["Youngstown St.",  "Horizon",         6.5,  10.5,  24,  9,162],
  ["Milwaukee",       "Horizon",         5.5,   9.0,  10, 22,163],
  ["Oakland",         "Horizon",         6.5,  10.5,  13, 19,164],
  ["IUPUI",           "Horizon",         3.5,   7.0,   5, 25,165],
  ["Detroit Mercy",   "Horizon",         5.5,   9.0,  14, 19,166],
  ["Green Bay",       "Horizon",         5.0,   8.5,   3, 30,167],
  ["Robert Morris",   "Horizon",         4.5,   8.0,  16, 17,168],
  ["Purdue Fort Wayne","Horizon",        5.0,   8.5,  19, 13,169],
  ["Yale",            "Ivy",             8.5,  12.5,  20,  8,170],
  ["Penn",            "Ivy",             7.0,  11.0,  17, 13,171],
  ["Harvard",         "Ivy",             7.5,  11.5,  14, 12,172],
  ["Cornell",         "Ivy",             6.5,  10.5,  17, 11,173],
  ["Columbia",        "Ivy",             5.5,   9.0,  15, 12,174],
  ["Brown",           "Ivy",             5.0,   8.5,  14, 13,175],
  ["Dartmouth",       "Ivy",             4.0,   7.5,   8, 19,176],
  ["Iona",            "MAAC",           10.0,  14.5,  27,  8,177],
  ["Rider",           "MAAC",            6.5,  10.5,  18, 14,178],
  ["Siena",           "MAAC",            5.5,   9.0,  17, 16,179],
  ["Quinnipiac",      "MAAC",            5.5,   9.0,  19, 14,180],
  ["Marist",          "MAAC",            5.0,   8.5,  13, 18,181],
  ["Manhattan",       "MAAC",            4.5,   8.0,   6, 25,182],
  ["Niagara",         "MAAC",            4.5,   8.0,  17, 17,183],
  ["Fairfield",       "MAAC",            4.5,   8.0,   9, 22,184],
  ["St. Peter's",     "MAAC",            5.0,   8.5,  14, 18,185],
  ["Canisius",        "MAAC",            4.0,   7.5,  11, 19,186],
  ["Mt. St. Mary's",  "MAAC",            5.0,   8.5,   9, 23,187],
  ["Toledo",          "MAC",             8.5,  12.5,  27,  8,188],
  ["Akron",           "MAC",             7.5,  11.5,  24, 11,189],
  ["Ohio",            "MAC",             7.0,  11.0,  19, 14,190],
  ["Ball St.",        "MAC",             6.0,  10.0,  20, 12,191],
  ["Buffalo",         "MAC",             6.5,  10.5,  15, 17,192],
  ["Bowling Green",   "MAC",             5.5,   9.0,  13, 18,193],
  ["Western Mich.",   "MAC",             5.0,   8.5,   8, 23,194],
  ["Eastern Mich.",   "MAC",             4.5,   8.0,   8, 22,195],
  ["Northern Ill.",   "MAC",             4.0,   7.5,  13, 18,196],
  ["Central Mich.",   "MAC",             3.5,   7.0,   7, 24,197],
  ["Miami (OH)",      "MAC",             4.5,   8.0,  12, 20,198],
  ["Norfolk St.",     "MEAC",            6.0,  10.0,  23,  9,199],
  ["NC Central",      "MEAC",            5.0,   8.5,  18, 13,200],
  ["Howard",          "MEAC",            5.5,   9.0,  22, 13,201],
  ["Morgan St.",      "MEAC",            4.5,   8.0,  15, 17,202],
  ["Coppin St.",      "MEAC",            3.0,   6.0,   9, 23,203],
  ["South Carolina St.","MEAC",          2.5,   5.5,  10, 21,204],
  ["Delaware St.",    "MEAC",            2.0,   5.0,   6, 25,205],
  ["Maryland-Eastern Shore","MEAC",      1.5,   4.5,   5, 26,206],
  ["Drake",           "Missouri Valley", 9.5,  13.8,  27,  8,207],
  ["Bradley",         "Missouri Valley", 8.0,  12.0,  25, 10,208],
  ["Belmont",         "Missouri Valley", 8.5,  12.5,  21, 11,209],
  ["Indiana St.",     "Missouri Valley", 6.0,  10.0,  23, 13,210],
  ["Murray St.",      "Missouri Valley", 7.5,  11.5,  17, 16,211],
  ["UNI",             "Missouri Valley", 7.0,  11.0,  14, 18,212],
  ["Missouri St.",    "Missouri Valley", 7.5,  11.5,  17, 16,213],
  ["Illinois St.",    "Missouri Valley", 6.5,  10.5,  13, 21,214],
  ["S. Illinois",     "Missouri Valley", 6.0,  10.0,  17, 14,215],
  ["Evansville",      "Missouri Valley", 5.0,   8.5,   5, 26,216],
  ["Valparaiso",      "Missouri Valley", 5.0,   8.5,  12, 20,217],
  ["Nevada",          "Mountain West",  11.0,  15.0,  22, 11,218],
  ["New Mexico",      "Mountain West",  10.5,  14.5,  22, 12,219],
  ["Colorado St.",    "Mountain West",   9.0,  13.0,  15, 18,220],
  ["UNLV",            "Mountain West",   9.0,  13.0,  19, 13,221],
  ["Wyoming",         "Mountain West",   7.5,  11.5,   9, 22,222],
  ["Air Force",       "Mountain West",   6.5,  10.5,  14, 18,223],
  ["Fresno St.",      "Mountain West",   7.5,  11.5,  11, 21,224],
  ["San Jose St.",    "Mountain West",   3.0,   6.0,  20, 14,225],
  ["Wagner",          "NEC",             3.5,   7.0,  16, 16,226],
  ["LIU",             "NEC",             3.5,   7.0,  16, 13,227],
  ["Sacred Heart",    "NEC",             3.5,   7.0,  15, 14,228],
  ["Merrimack",       "NEC",             5.5,   9.0,  20, 11,229],
  ["St. Francis PA",  "NEC",             3.5,   7.0,  19, 14,230],
  ["Mount St. Mary's","NEC",             4.0,   7.5,  18, 14,231],
  ["Central Conn.",   "NEC",             3.0,   6.0,   8, 22,232],
  ["UT Martin",       "OVC",             6.0,  10.0,  19, 14,233],
  ["Morehead St.",    "OVC",             7.0,  11.0,  23, 12,234],
  ["Tennessee Tech",  "OVC",             5.5,   9.0,  17, 15,235],
  ["SE Missouri",     "OVC",             6.5,  10.5,  19, 17,236],
  ["E. Illinois",     "OVC",             4.5,   8.0,  13, 19,237],
  ["SIUE",            "OVC",             4.5,   8.0,  18, 16,238],
  ["Tennessee St.",   "OVC",             5.5,   9.0,  20, 14,239],
  ["Lindenwood",      "OVC",             3.0,   6.0,  10, 22,240],
  ["S. Indiana",      "OVC",             3.5,   7.0,   9, 21,241],
  ["Little Rock",     "OVC",             4.0,   7.5,  10, 21,242],
  ["Boston U.",       "Patriot",         6.5,  10.5,  20, 13,243],
  ["Lehigh",          "Patriot",         5.5,   9.0,  16, 14,244],
  ["Navy",            "Patriot",         5.0,   8.5,  18, 13,245],
  ["Holy Cross",      "Patriot",         5.5,   9.0,  16, 14,246],
  ["Army",            "Patriot",         5.5,   9.0,  17, 14,247],
  ["American U.",     "Patriot",         5.0,   8.5,  16, 14,248],
  ["Bucknell",        "Patriot",         5.0,   8.5,   9, 23,249],
  ["Loyola Maryland", "Patriot",         3.5,   7.0,   9, 23,250],
  ["Lafayette",       "Patriot",         3.5,   7.0,   8, 23,251],
  ["Samford",         "Southern",        7.5,  11.5,  21, 11,252],
  ["Furman",          "Southern",       10.5,  15.0,  28,  8,253],
  ["Chattanooga",     "Southern",        7.5,  11.5,  18, 16,254],
  ["UNCG",            "Southern",        6.5,  10.5,  16, 17,255],
  ["Mercer",          "Southern",        6.0,  10.0,  16, 16,256],
  ["Wofford",         "Southern",        7.0,  11.0,  17, 16,257],
  ["W. Carolina",     "Southern",        4.0,   7.5,  18, 14,258],
  ["E. Tennessee St.","Southern",        6.5,  10.5,  18, 13,259],
  ["VMI",             "Southern",        4.5,   8.0,  10, 22,260],
  ["The Citadel",     "Southern",        3.5,   7.0,  10, 21,261],
  ["Texas A&M-CC",    "Southland",       7.0,  10.5,  24, 11,262],
  ["SE Louisiana",    "Southland",       4.5,   8.0,  11, 19,263],
  ["Nicholls",        "Southland",       5.5,   9.0,  15, 17,264],
  ["McNeese",         "Southland",       4.5,   8.0,  11, 23,265],
  ["Lamar",           "Southland",       3.5,   7.0,  11, 22,266],
  ["NW St.",          "Southland",       4.5,   8.0,  22, 11,267],
  ["Stephen F. Austin","Southland",      5.0,   8.5,   9, 22,268],
  ["Houston Christian","Southland",      3.5,   7.0,  10, 21,269],
  ["Incarnate Word",  "Southland",       4.5,   8.0,  17, 18,270],
  ["New Orleans",     "Southland",       2.5,   5.5,  12, 19,271],
  ["S. Dakota St.",   "Summit",          8.0,  12.0,  19, 13,272],
  ["N. Dakota St.",   "Summit",          7.5,  11.5,  16, 13,273],
  ["S. Dakota",       "Summit",          7.0,  11.0,  19, 13,274],
  ["Oral Roberts",    "Summit",         10.0,  15.0,  30,  5,275],
  ["Omaha",           "Summit",          5.5,   9.0,   9, 22,276],
  ["N. Dakota",       "Summit",          5.5,   9.0,  13, 19,277],
  ["Denver",          "Summit",          6.5,  10.5,  15, 17,278],
  ["Kansas City",     "Summit",          5.0,   8.5,  10, 22,279],
  ["W. Illinois",     "Summit",          4.0,   7.5,   9, 22,280],
  ["South Alabama",   "Sun Belt",        6.0,  10.0,  19, 12,281],
  ["Marshall",        "Sun Belt",        7.0,  11.0,  24, 10,282],
  ["James Madison",   "Sun Belt",        7.5,  11.5,  22, 11,283],
  ["Old Dominion",    "Sun Belt",        6.0,  10.0,  18, 17,284],
  ["Texas St.",       "Sun Belt",        6.0,  10.0,  20, 14,285],
  ["App. St.",        "Sun Belt",        6.0,  10.0,  16, 17,286],
  ["Coastal Carolina","Sun Belt",        5.0,   8.5,  13, 19,287],
  ["Georgia St.",     "Sun Belt",        5.5,   9.0,  14, 17,288],
  ["Troy",            "Sun Belt",        6.5,  10.5,  19, 15,289],
  ["UL Monroe",       "Sun Belt",        4.5,   8.0,  12, 21,290],
  ["Georgia Southern","Sun Belt",        5.0,   8.5,  17, 17,291],
  ["Arkansas St.",    "Sun Belt",        5.0,   8.5,  13, 21,292],
  ["UT Arlington",    "Sun Belt",        4.5,   8.0,  12, 23,293],
  ["S. Miss.",        "Sun Belt",        5.5,   9.0,  25,  8,294],
  ["Alcorn St.",      "SWAC",            3.5,   7.0,  17, 15,295],
  ["Grambling",       "SWAC",            4.5,   8.0,  19, 14,296],
  ["Prairie View",    "SWAC",            4.0,   7.5,  16, 16,297],
  ["Southern U.",     "SWAC",            4.5,   8.0,  18, 14,298],
  ["Jackson St.",     "SWAC",            4.0,   7.5,  17, 16,299],
  ["Bethune-Cookman", "SWAC",            3.0,   6.0,  14, 17,300],
  ["AR-Pine Bluff",   "SWAC",            2.5,   5.5,   8, 24,301],
  ["Miss. Valley St.","SWAC",            2.0,   5.0,   3, 27,302],
  ["Alabama St.",     "SWAC",            2.5,   5.5,  10, 23,303],
  ["Alabama A&M",     "SWAC",            3.0,   6.0,   9, 23,304],
  ["Saint Mary's",    "WCC",            15.5,  20.8,  27,  8,305],
  ["Loyola Marymount","WCC",             7.5,  11.5,  19, 13,306],
  ["Santa Clara",     "WCC",             7.0,  11.0,  23, 10,307],
  ["San Francisco",   "WCC",             8.5,  12.5,  20, 13,308],
  ["Pacific",         "WCC",             4.0,   7.5,  15, 18,309],
  ["Portland",        "WCC",             4.0,   7.5,  10, 22,310],
  ["Pepperdine",      "WCC",             3.0,   6.0,   9, 22,311],
  ["Grand Canyon",    "WAC",             8.5,  12.5,  24, 12,312],
  ["UT Rio Grande",   "WAC",             5.5,   9.0,  17, 16,313],
  ["New Mexico St.",  "WAC",             6.5,  10.5,  10, 16,314],
  ["Sam Houston",     "WAC",             5.5,   9.0,  25,  8,315],
  ["Utah Valley",     "WAC",             6.5,  10.5,  28,  9,316],
  ["Seattle U.",      "WAC",             5.5,   9.0,  20, 13,317],
  ["Tarleton St.",    "WAC",             5.0,   8.5,  17, 16,318],
  ["Abilene Christian","WAC",            6.0,  10.0,  16, 17,319],
  ["Stephen F. Austin","WAC",            5.5,   9.0,  19, 16,320],
  ["S. Utah",         "WAC",             5.0,   8.5,  19, 14,321],
  ["California Baptist","WAC",           6.0,  10.0,  17, 15,322],
  ["UT Arlington",    "WAC",             4.0,   7.5,  12, 23,323],
  ["Chicago St.",     "WAC",             1.5,   4.5,   3, 26,324],
  ["Montana",         "Big Sky",         6.5,  10.5,  17, 14,325],
  ["E. Washington",   "Big Sky",         6.0,  10.0,  23, 11,326],
  ["Sacramento St.",  "Big Sky",         5.5,   9.0,  14, 16,327],
  ["Idaho St.",       "Big Sky",         4.5,   8.0,  10, 22,328],
  ["N. Arizona",      "Big Sky",         5.0,   8.5,   9, 23,329],
  ["Weber St.",       "Big Sky",         6.0,  10.0,  18, 13,330],
  ["Idaho",           "Big Sky",         4.5,   8.0,  10, 23,331],
  ["Portland St.",    "Big Sky",         5.0,   8.5,  17, 15,332],
  ["N. Colorado",     "Big Sky",         5.5,   9.0,  13, 19,333],
  ["UNC Asheville",   "Big South",       7.5,  11.5,  27,  8,334],
  ["Campbell",        "Big South",       6.5,  10.5,  17, 16,335],
  ["High Point",      "Big South",       5.5,   9.0,  14, 17,336],
  ["Longwood",        "Big South",       5.5,   9.0,  19, 14,337],
  ["Winthrop",        "Big South",       5.5,   9.0,  16, 16,338],
  ["Gardner-Webb",    "Big South",       5.0,   8.5,  16, 14,339],
  ["Radford",         "Big South",       4.5,   8.0,  17, 17,340],
  ["Charleston So.",  "Big South",       4.0,   7.5,  10, 23,341],
  ["Presbyterian",    "Big South",       3.5,   7.0,   8, 21,342],
  ["USC Upstate",     "Big South",       3.0,   6.0,   8, 22,343],
];

const seen = new Set();
const DEDUPLICATED = RAW.filter(([team]) => {
  if (seen.has(team)) return false;
  seen.add(team);
  return true;
});

const TEAM_HISTORY = DEDUPLICATED.map(([team, conference, start, end, wins, losses, seed]) => ({
  team,
  conference,
  weeklyAdjEM: traj(start, end, seed),
  weeklyRecord: rec(wins, losses),
}));

// ── Schedules for top contenders (8 teams) ─────────────────────────────────
// Showing representative games. Other teams have no schedule data
// (the team modal handles missing schedules gracefully).
const SCHEDULES = {
  "UConn": [
    { week:1,  opponent:"Stonehill",          opponentAdjEM:1.0,  result:"W", score:"95-60",  location:"H" },
    { week:1,  opponent:"Boston U.",          opponentAdjEM:10.5, result:"W", score:"81-57",  location:"H" },
    { week:2,  opponent:"Delaware St.",       opponentAdjEM:5.0,  result:"W", score:"80-49",  location:"H" },
    { week:2,  opponent:"Buffalo",            opponentAdjEM:10.5, result:"W", score:"82-69",  location:"H" },
    { week:3,  opponent:"Oregon",             opponentAdjEM:14.8, result:"W", score:"77-59",  location:"N" },
    { week:3,  opponent:"Alabama",            opponentAdjEM:29.5, result:"W", score:"82-67",  location:"N" },
    { week:4,  opponent:"Iowa St.",           opponentAdjEM:21.6, result:"W", score:"71-65",  location:"H" },
    { week:4,  opponent:"Florida",            opponentAdjEM:16.5, result:"W", score:"75-54",  location:"H" },
    { week:5,  opponent:"Oklahoma St.",       opponentAdjEM:15.8, result:"W", score:"74-64",  location:"H" },
    { week:6,  opponent:"Butler",             opponentAdjEM:11.5, result:"W", score:"75-56",  location:"A" },
    { week:6,  opponent:"Georgetown",         opponentAdjEM:6.0,  result:"W", score:"78-57",  location:"H" },
    { week:7,  opponent:"LIU",                opponentAdjEM:7.0,  result:"W", score:"104-56", location:"H" },
    { week:8,  opponent:"Marquette",          opponentAdjEM:23.2, result:"L", score:"79-82",  location:"A" },
    { week:8,  opponent:"Providence",         opponentAdjEM:17.2, result:"L", score:"73-77",  location:"A" },
    { week:9,  opponent:"Xavier",             opponentAdjEM:19.4, result:"W", score:"82-79",  location:"H" },
    { week:9,  opponent:"DePaul",             opponentAdjEM:5.0,  result:"W", score:"74-65",  location:"A" },
    { week:10, opponent:"Creighton",          opponentAdjEM:22.6, result:"L", score:"61-69",  location:"H" },
    { week:10, opponent:"St. John's",         opponentAdjEM:14.0, result:"L", score:"83-95",  location:"A" },
    { week:11, opponent:"Butler",             opponentAdjEM:11.5, result:"W", score:"74-58",  location:"H" },
    { week:11, opponent:"Marquette",          opponentAdjEM:23.2, result:"L", score:"75-87",  location:"H" },
    { week:12, opponent:"Georgetown",         opponentAdjEM:6.0,  result:"W", score:"71-58",  location:"A" },
    { week:12, opponent:"Seton Hall",         opponentAdjEM:13.5, result:"W", score:"66-58",  location:"H" },
    { week:13, opponent:"Villanova",          opponentAdjEM:14.5, result:"W", score:"68-58",  location:"H" },
    { week:13, opponent:"St. John's",         opponentAdjEM:14.0, result:"W", score:"85-74",  location:"H" },
    { week:14, opponent:"Xavier",             opponentAdjEM:19.4, result:"W", score:"82-67",  location:"A" },
    { week:14, opponent:"Providence",         opponentAdjEM:17.2, result:"W", score:"87-69",  location:"H" },
    { week:15, opponent:"Seton Hall",         opponentAdjEM:13.5, result:"L", score:"60-67",  location:"A" },
    { week:15, opponent:"Creighton",          opponentAdjEM:22.6, result:"W", score:"70-63",  location:"A" },
    { week:16, opponent:"DePaul",             opponentAdjEM:5.0,  result:"W", score:"82-58",  location:"H" },
    { week:16, opponent:"Villanova",          opponentAdjEM:14.5, result:"W", score:"76-58",  location:"A" },
    { week:17, opponent:"Marquette",          opponentAdjEM:23.2, result:"L", score:"72-73",  location:"N" },
    { week:18, opponent:"Iona",               opponentAdjEM:14.5, result:"W", score:"87-63",  location:"N" },
    { week:18, opponent:"Saint Mary's",       opponentAdjEM:20.8, result:"W", score:"70-55",  location:"N" },
    { week:19, opponent:"Arkansas",           opponentAdjEM:18.0, result:"W", score:"88-65",  location:"N" },
    { week:19, opponent:"Gonzaga",            opponentAdjEM:23.8, result:"W", score:"82-54",  location:"N" },
    { week:20, opponent:"Miami (FL)",         opponentAdjEM:19.8, result:"W", score:"72-59",  location:"N" },
    { week:20, opponent:"San Diego St.",      opponentAdjEM:22.0, result:"W", score:"76-59",  location:"N" },
  ],
  "Houston": [
    { week:1,  opponent:"Northern Colorado",  opponentAdjEM:9.0,  result:"W", score:"83-39",  location:"H" },
    { week:1,  opponent:"Texas Southern",     opponentAdjEM:9.0,  result:"W", score:"75-50",  location:"H" },
    { week:2,  opponent:"Saint Joseph's",     opponentAdjEM:11.0, result:"W", score:"66-48",  location:"H" },
    { week:2,  opponent:"Oregon",             opponentAdjEM:14.8, result:"W", score:"75-60",  location:"N" },
    { week:3,  opponent:"Norfolk St.",        opponentAdjEM:10.0, result:"W", score:"81-54",  location:"H" },
    { week:3,  opponent:"Saint Mary's",       opponentAdjEM:20.8, result:"L", score:"68-78",  location:"A" },
    { week:4,  opponent:"Kent St.",           opponentAdjEM:13.2, result:"W", score:"49-44",  location:"H" },
    { week:4,  opponent:"Alabama",            opponentAdjEM:29.5, result:"W", score:"71-65",  location:"N" },
    { week:5,  opponent:"North Florida",      opponentAdjEM:5.0,  result:"W", score:"79-45",  location:"H" },
    { week:5,  opponent:"Alcorn St.",         opponentAdjEM:7.0,  result:"W", score:"100-52", location:"H" },
    { week:6,  opponent:"Tulane",             opponentAdjEM:13.0, result:"W", score:"73-51",  location:"A" },
    { week:6,  opponent:"East Carolina",      opponentAdjEM:6.0,  result:"W", score:"66-39",  location:"H" },
    { week:7,  opponent:"Tulsa",              opponentAdjEM:7.0,  result:"W", score:"85-45",  location:"A" },
    { week:7,  opponent:"South Florida",      opponentAdjEM:7.5,  result:"W", score:"83-77",  location:"H" },
    { week:8,  opponent:"Cincinnati",         opponentAdjEM:14.5, result:"W", score:"75-69",  location:"H" },
    { week:9,  opponent:"Temple",             opponentAdjEM:9.0,  result:"L", score:"55-56",  location:"A" },
    { week:9,  opponent:"SMU",                opponentAdjEM:11.0, result:"W", score:"87-53",  location:"H" },
    { week:10, opponent:"East Carolina",      opponentAdjEM:6.0,  result:"W", score:"77-52",  location:"A" },
    { week:10, opponent:"UCF",                opponentAdjEM:14.8, result:"W", score:"72-43",  location:"H" },
    { week:11, opponent:"Wichita St.",        opponentAdjEM:10.0, result:"W", score:"75-46",  location:"H" },
    { week:11, opponent:"Memphis",            opponentAdjEM:17.5, result:"L", score:"64-66",  location:"A" },
    { week:12, opponent:"Tulsa",              opponentAdjEM:7.0,  result:"W", score:"75-48",  location:"H" },
    { week:12, opponent:"Cincinnati",         opponentAdjEM:14.5, result:"W", score:"79-66",  location:"A" },
    { week:13, opponent:"Tulane",             opponentAdjEM:13.0, result:"W", score:"86-78",  location:"H" },
    { week:13, opponent:"Temple",             opponentAdjEM:9.0,  result:"W", score:"72-52",  location:"H" },
    { week:14, opponent:"Memphis",            opponentAdjEM:17.5, result:"W", score:"72-64",  location:"H" },
    { week:14, opponent:"South Florida",      opponentAdjEM:7.5,  result:"W", score:"82-43",  location:"A" },
    { week:15, opponent:"UCF",                opponentAdjEM:14.8, result:"W", score:"68-52",  location:"A" },
    { week:15, opponent:"SMU",                opponentAdjEM:11.0, result:"W", score:"87-73",  location:"A" },
    { week:16, opponent:"Wichita St.",        opponentAdjEM:10.0, result:"W", score:"76-64",  location:"A" },
    { week:17, opponent:"Memphis",            opponentAdjEM:17.5, result:"L", score:"61-65",  location:"N" },
    { week:19, opponent:"Northern Kentucky",  opponentAdjEM:11.0, result:"W", score:"63-52",  location:"N" },
    { week:19, opponent:"Auburn",             opponentAdjEM:18.8, result:"W", score:"81-64",  location:"N" },
    { week:19, opponent:"Miami (FL)",         opponentAdjEM:19.8, result:"L", score:"81-89",  location:"N" },
  ],
  "Alabama": [
    { week:1,  opponent:"Longwood",           opponentAdjEM:8.5,  result:"W", score:"75-54",  location:"H" },
    { week:1,  opponent:"Liberty",            opponentAdjEM:11.0, result:"W", score:"79-65",  location:"H" },
    { week:2,  opponent:"South Alabama",      opponentAdjEM:10.0, result:"W", score:"75-67",  location:"H" },
    { week:2,  opponent:"Michigan St.",       opponentAdjEM:18.2, result:"W", score:"81-70",  location:"N" },
    { week:3,  opponent:"North Carolina",     opponentAdjEM:18.5, result:"W", score:"103-101",location:"N" },
    { week:3,  opponent:"UConn",              opponentAdjEM:27.9, result:"L", score:"67-82",  location:"N" },
    { week:4,  opponent:"South Dakota St.",   opponentAdjEM:12.0, result:"W", score:"82-65",  location:"H" },
    { week:4,  opponent:"Houston",            opponentAdjEM:31.6, result:"L", score:"65-71",  location:"N" },
    { week:5,  opponent:"Memphis",            opponentAdjEM:17.5, result:"W", score:"82-79",  location:"N" },
    { week:5,  opponent:"Gonzaga",            opponentAdjEM:23.8, result:"W", score:"91-82",  location:"N" },
    { week:6,  opponent:"Jackson St.",        opponentAdjEM:7.5,  result:"W", score:"96-49",  location:"H" },
    { week:6,  opponent:"Mississippi St.",    opponentAdjEM:16.0, result:"W", score:"66-55",  location:"H" },
    { week:7,  opponent:"Florida",            opponentAdjEM:16.5, result:"W", score:"87-69",  location:"A" },
    { week:8,  opponent:"Ole Miss",           opponentAdjEM:13.5, result:"W", score:"107-70", location:"H" },
    { week:9,  opponent:"Arkansas",           opponentAdjEM:18.0, result:"W", score:"84-69",  location:"H" },
    { week:9,  opponent:"Vanderbilt",         opponentAdjEM:13.5, result:"W", score:"77-52",  location:"A" },
    { week:10, opponent:"Kentucky",           opponentAdjEM:22.0, result:"W", score:"78-52",  location:"H" },
    { week:10, opponent:"LSU",                opponentAdjEM:15.0, result:"W", score:"106-66", location:"H" },
    { week:11, opponent:"Missouri",           opponentAdjEM:16.8, result:"W", score:"86-83",  location:"A" },
    { week:11, opponent:"Oklahoma",           opponentAdjEM:14.5, result:"W", score:"93-69",  location:"A" },
    { week:12, opponent:"Mississippi St.",    opponentAdjEM:16.0, result:"W", score:"66-63",  location:"A" },
    { week:12, opponent:"Georgia",            opponentAdjEM:14.0, result:"W", score:"108-59", location:"H" },
    { week:13, opponent:"Tennessee",          opponentAdjEM:25.5, result:"W", score:"68-59",  location:"H" },
    { week:13, opponent:"Vanderbilt",         opponentAdjEM:13.5, result:"L", score:"66-78",  location:"H" },
    { week:14, opponent:"South Carolina",     opponentAdjEM:12.5, result:"W", score:"78-76",  location:"H" },
    { week:14, opponent:"Florida",            opponentAdjEM:16.5, result:"W", score:"81-73",  location:"H" },
    { week:15, opponent:"Auburn",             opponentAdjEM:18.8, result:"W", score:"77-69",  location:"A" },
    { week:15, opponent:"Arkansas",           opponentAdjEM:18.0, result:"W", score:"86-83",  location:"A" },
    { week:16, opponent:"Tennessee",          opponentAdjEM:25.5, result:"W", score:"78-68",  location:"A" },
    { week:16, opponent:"Auburn",             opponentAdjEM:18.8, result:"W", score:"92-67",  location:"H" },
    { week:17, opponent:"Texas A&M",          opponentAdjEM:17.1, result:"L", score:"66-67",  location:"N" },
    { week:18, opponent:"Mississippi St.",    opponentAdjEM:16.0, result:"W", score:"72-49",  location:"N" },
    { week:18, opponent:"Missouri",           opponentAdjEM:16.8, result:"W", score:"72-61",  location:"N" },
    { week:19, opponent:"Texas A&M-CC",       opponentAdjEM:10.5, result:"W", score:"96-75",  location:"N" },
    { week:19, opponent:"Maryland",           opponentAdjEM:17.5, result:"W", score:"73-51",  location:"N" },
    { week:19, opponent:"San Diego St.",      opponentAdjEM:22.0, result:"L", score:"64-71",  location:"N" },
  ],
  "Purdue": [
    { week:1,  opponent:"Milwaukee",          opponentAdjEM:9.0,  result:"W", score:"84-53",  location:"H" },
    { week:2,  opponent:"Truman St.",         opponentAdjEM:1.0,  result:"W", score:"77-44",  location:"H" },
    { week:2,  opponent:"Austin Peay",        opponentAdjEM:6.0,  result:"W", score:"63-44",  location:"H" },
    { week:3,  opponent:"West Virginia",      opponentAdjEM:17.6, result:"W", score:"81-71",  location:"N" },
    { week:3,  opponent:"Gonzaga",            opponentAdjEM:23.8, result:"W", score:"84-66",  location:"N" },
    { week:3,  opponent:"Duke",               opponentAdjEM:21.0, result:"W", score:"75-56",  location:"N" },
    { week:4,  opponent:"Marquette",          opponentAdjEM:23.2, result:"W", score:"75-70",  location:"H" },
    { week:5,  opponent:"Hofstra",            opponentAdjEM:13.5, result:"W", score:"66-50",  location:"H" },
    { week:5,  opponent:"Florida A&M",        opponentAdjEM:1.0,  result:"W", score:"86-62",  location:"H" },
    { week:6,  opponent:"Davidson",           opponentAdjEM:11.0, result:"W", score:"69-61",  location:"N" },
    { week:6,  opponent:"New Orleans",        opponentAdjEM:5.5,  result:"W", score:"77-44",  location:"H" },
    { week:7,  opponent:"Nebraska",           opponentAdjEM:14.0, result:"W", score:"65-62",  location:"A" },
    { week:8,  opponent:"Rutgers",            opponentAdjEM:17.5, result:"W", score:"65-64",  location:"H" },
    { week:8,  opponent:"Penn St.",           opponentAdjEM:16.4, result:"W", score:"76-63",  location:"H" },
    { week:9,  opponent:"Maryland",           opponentAdjEM:17.5, result:"L", score:"54-68",  location:"A" },
    { week:9,  opponent:"Ohio St.",           opponentAdjEM:17.0, result:"W", score:"71-69",  location:"H" },
    { week:10, opponent:"Nebraska",           opponentAdjEM:14.0, result:"W", score:"75-58",  location:"H" },
    { week:10, opponent:"Michigan St.",       opponentAdjEM:18.2, result:"W", score:"64-63",  location:"A" },
    { week:11, opponent:"Northwestern",       opponentAdjEM:18.0, result:"L", score:"58-64",  location:"A" },
    { week:11, opponent:"Minnesota",          opponentAdjEM:12.0, result:"W", score:"61-39",  location:"H" },
    { week:12, opponent:"Iowa",               opponentAdjEM:18.6, result:"W", score:"87-73",  location:"H" },
    { week:12, opponent:"Michigan",           opponentAdjEM:16.2, result:"W", score:"75-70",  location:"H" },
    { week:13, opponent:"Indiana",            opponentAdjEM:20.5, result:"L", score:"69-79",  location:"A" },
    { week:13, opponent:"Ohio St.",           opponentAdjEM:17.0, result:"W", score:"82-55",  location:"A" },
    { week:14, opponent:"Maryland",           opponentAdjEM:17.5, result:"W", score:"58-55",  location:"H" },
    { week:14, opponent:"Northwestern",       opponentAdjEM:18.0, result:"W", score:"80-60",  location:"H" },
    { week:15, opponent:"Michigan",           opponentAdjEM:16.2, result:"W", score:"76-65",  location:"A" },
    { week:15, opponent:"Indiana",            opponentAdjEM:20.5, result:"W", score:"79-71",  location:"H" },
    { week:16, opponent:"Wisconsin",          opponentAdjEM:16.5, result:"W", score:"63-61",  location:"A" },
    { week:16, opponent:"Illinois",           opponentAdjEM:19.5, result:"W", score:"76-71",  location:"H" },
    { week:17, opponent:"Rutgers",            opponentAdjEM:17.5, result:"W", score:"65-64",  location:"A" },
    { week:18, opponent:"Rutgers",            opponentAdjEM:17.5, result:"W", score:"70-65",  location:"N" },
    { week:18, opponent:"Ohio St.",           opponentAdjEM:17.0, result:"W", score:"67-65",  location:"N" },
    { week:18, opponent:"Penn St.",           opponentAdjEM:16.4, result:"W", score:"67-65",  location:"N" },
    { week:19, opponent:"Fairleigh Dickinson",opponentAdjEM:8.5,  result:"L", score:"58-63",  location:"N" },
  ],
  "Kansas": [
    { week:1,  opponent:"Omaha",              opponentAdjEM:9.0,  result:"W", score:"89-64",  location:"H" },
    { week:1,  opponent:"North Dakota St.",   opponentAdjEM:11.5, result:"W", score:"89-50",  location:"H" },
    { week:2,  opponent:"Southern Utah",      opponentAdjEM:8.5,  result:"W", score:"99-71",  location:"H" },
    { week:2,  opponent:"Duke",               opponentAdjEM:21.0, result:"W", score:"69-64",  location:"N" },
    { week:3,  opponent:"Wisconsin",          opponentAdjEM:16.5, result:"W", score:"69-68",  location:"N" },
    { week:3,  opponent:"NC State",           opponentAdjEM:16.6, result:"W", score:"80-74",  location:"N" },
    { week:4,  opponent:"Texas Southern",     opponentAdjEM:9.0,  result:"W", score:"87-50",  location:"H" },
    { week:4,  opponent:"Missouri",           opponentAdjEM:16.8, result:"W", score:"95-67",  location:"A" },
    { week:5,  opponent:"Indiana",            opponentAdjEM:20.5, result:"L", score:"75-84",  location:"N" },
    { week:5,  opponent:"Harvard",            opponentAdjEM:11.5, result:"W", score:"83-78",  location:"H" },
    { week:6,  opponent:"Oklahoma",           opponentAdjEM:14.5, result:"W", score:"75-69",  location:"A" },
    { week:6,  opponent:"Iowa St.",           opponentAdjEM:21.6, result:"W", score:"62-60",  location:"H" },
    { week:7,  opponent:"Oklahoma St.",       opponentAdjEM:15.8, result:"W", score:"69-67",  location:"H" },
    { week:8,  opponent:"Texas Tech",         opponentAdjEM:14.0, result:"W", score:"75-72",  location:"A" },
    { week:9,  opponent:"TCU",                opponentAdjEM:19.7, result:"L", score:"75-83",  location:"A" },
    { week:9,  opponent:"Iowa St.",           opponentAdjEM:21.6, result:"L", score:"62-68",  location:"A" },
    { week:10, opponent:"Kansas St.",         opponentAdjEM:20.4, result:"W", score:"83-82",  location:"A" },
    { week:10, opponent:"Baylor",             opponentAdjEM:22.4, result:"L", score:"77-87",  location:"H" },
    { week:11, opponent:"West Virginia",      opponentAdjEM:17.6, result:"W", score:"76-74",  location:"H" },
    { week:11, opponent:"Iowa St.",           opponentAdjEM:21.6, result:"W", score:"79-75",  location:"H" },
    { week:12, opponent:"Oklahoma",           opponentAdjEM:14.5, result:"W", score:"79-65",  location:"H" },
    { week:12, opponent:"Texas",              opponentAdjEM:27.4, result:"L", score:"71-74",  location:"A" },
    { week:13, opponent:"Kansas St.",         opponentAdjEM:20.4, result:"W", score:"90-78",  location:"H" },
    { week:13, opponent:"Baylor",             opponentAdjEM:22.4, result:"W", score:"71-58",  location:"A" },
    { week:14, opponent:"Texas Tech",         opponentAdjEM:14.0, result:"W", score:"75-69",  location:"H" },
    { week:14, opponent:"Oklahoma St.",       opponentAdjEM:15.8, result:"W", score:"87-76",  location:"A" },
    { week:15, opponent:"West Virginia",      opponentAdjEM:17.6, result:"W", score:"76-69",  location:"A" },
    { week:15, opponent:"TCU",                opponentAdjEM:19.7, result:"W", score:"64-50",  location:"H" },
    { week:16, opponent:"Texas",              opponentAdjEM:27.4, result:"W", score:"83-56",  location:"H" },
    { week:17, opponent:"West Virginia",      opponentAdjEM:17.6, result:"W", score:"78-61",  location:"N" },
    { week:18, opponent:"Iowa St.",           opponentAdjEM:21.6, result:"W", score:"71-58",  location:"N" },
    { week:18, opponent:"Texas",              opponentAdjEM:27.4, result:"L", score:"56-76",  location:"N" },
    { week:19, opponent:"Howard",             opponentAdjEM:9.0,  result:"W", score:"96-68",  location:"N" },
    { week:19, opponent:"Arkansas",           opponentAdjEM:18.0, result:"L", score:"71-72",  location:"N" },
  ],
  "Marquette": [
    { week:1,  opponent:"Radford",            opponentAdjEM:7.8,  result:"W", score:"77-65",  location:"H" },
    { week:1,  opponent:"Northern Illinois",  opponentAdjEM:7.5,  result:"W", score:"95-68",  location:"H" },
    { week:2,  opponent:"Mississippi St.",    opponentAdjEM:16.0, result:"L", score:"58-66",  location:"N" },
    { week:2,  opponent:"Baylor",             opponentAdjEM:22.4, result:"L", score:"85-96",  location:"N" },
    { week:3,  opponent:"Loyola Marymount",   opponentAdjEM:11.5, result:"W", score:"85-65",  location:"H" },
    { week:4,  opponent:"Purdue",             opponentAdjEM:26.7, result:"L", score:"70-75",  location:"A" },
    { week:5,  opponent:"Wisconsin",          opponentAdjEM:16.5, result:"W", score:"80-77",  location:"H" },
    { week:5,  opponent:"Norfolk St.",        opponentAdjEM:10.0, result:"W", score:"86-58",  location:"H" },
    { week:6,  opponent:"Tulane",             opponentAdjEM:13.0, result:"W", score:"80-77",  location:"H" },
    { week:6,  opponent:"Notre Dame",         opponentAdjEM:12.0, result:"W", score:"73-58",  location:"H" },
    { week:7,  opponent:"UCLA",               opponentAdjEM:26.5, result:"L", score:"67-69",  location:"A" },
    { week:8,  opponent:"UConn",              opponentAdjEM:27.9, result:"W", score:"82-79",  location:"H" },
    { week:9,  opponent:"Xavier",             opponentAdjEM:19.4, result:"W", score:"83-67",  location:"A" },
    { week:9,  opponent:"Seton Hall",         opponentAdjEM:13.5, result:"W", score:"73-59",  location:"H" },
    { week:10, opponent:"Villanova",          opponentAdjEM:14.5, result:"W", score:"71-69",  location:"A" },
    { week:10, opponent:"Providence",         opponentAdjEM:17.2, result:"W", score:"83-81",  location:"H" },
    { week:11, opponent:"UConn",              opponentAdjEM:27.9, result:"W", score:"87-75",  location:"A" },
    { week:11, opponent:"DePaul",             opponentAdjEM:5.0,  result:"W", score:"88-74",  location:"H" },
    { week:12, opponent:"Butler",             opponentAdjEM:11.5, result:"W", score:"76-59",  location:"H" },
    { week:12, opponent:"St. John's",         opponentAdjEM:14.0, result:"W", score:"96-94",  location:"A" },
    { week:13, opponent:"Creighton",          opponentAdjEM:22.6, result:"W", score:"83-65",  location:"H" },
    { week:13, opponent:"Xavier",             opponentAdjEM:19.4, result:"L", score:"80-92",  location:"H" },
    { week:14, opponent:"Providence",         opponentAdjEM:17.2, result:"L", score:"63-71",  location:"A" },
    { week:14, opponent:"Georgetown",         opponentAdjEM:6.0,  result:"W", score:"100-80", location:"H" },
    { week:15, opponent:"Villanova",          opponentAdjEM:14.5, result:"W", score:"81-66",  location:"H" },
    { week:15, opponent:"Seton Hall",         opponentAdjEM:13.5, result:"W", score:"83-67",  location:"A" },
    { week:16, opponent:"Butler",             opponentAdjEM:11.5, result:"W", score:"76-67",  location:"A" },
    { week:16, opponent:"Creighton",          opponentAdjEM:22.6, result:"W", score:"81-77",  location:"A" },
    { week:17, opponent:"St. John's",         opponentAdjEM:14.0, result:"W", score:"96-83",  location:"H" },
    { week:17, opponent:"UConn",              opponentAdjEM:27.9, result:"W", score:"73-72",  location:"N" },
    { week:18, opponent:"St. John's",         opponentAdjEM:14.0, result:"W", score:"79-65",  location:"N" },
    { week:18, opponent:"Xavier",             opponentAdjEM:19.4, result:"L", score:"55-65",  location:"N" },
    { week:19, opponent:"Vermont",            opponentAdjEM:13.0, result:"W", score:"78-61",  location:"N" },
    { week:19, opponent:"Michigan St.",       opponentAdjEM:18.2, result:"L", score:"63-69",  location:"N" },
  ],
  "San Diego St.": [
    { week:1,  opponent:"UC Riverside",       opponentAdjEM:9.0,  result:"W", score:"66-61",  location:"H" },
    { week:1,  opponent:"BYU",                opponentAdjEM:14.0, result:"L", score:"54-66",  location:"N" },
    { week:2,  opponent:"Arkansas",           opponentAdjEM:18.0, result:"W", score:"78-74",  location:"N" },
    { week:3,  opponent:"Stanford",           opponentAdjEM:13.5, result:"W", score:"74-61",  location:"N" },
    { week:4,  opponent:"Saint Mary's",       opponentAdjEM:20.8, result:"L", score:"62-67",  location:"N" },
    { week:4,  opponent:"Cal St. Fullerton",  opponentAdjEM:10.0, result:"W", score:"71-58",  location:"H" },
    { week:5,  opponent:"Air Force",          opponentAdjEM:10.5, result:"W", score:"73-58",  location:"H" },
    { week:6,  opponent:"Ohio St.",           opponentAdjEM:17.0, result:"L", score:"71-72",  location:"N" },
    { week:7,  opponent:"Boise St.",          opponentAdjEM:14.8, result:"W", score:"66-56",  location:"H" },
    { week:7,  opponent:"Wyoming",            opponentAdjEM:11.5, result:"W", score:"69-52",  location:"A" },
    { week:8,  opponent:"Utah St.",           opponentAdjEM:15.6, result:"W", score:"81-64",  location:"H" },
    { week:9,  opponent:"New Mexico",         opponentAdjEM:14.5, result:"W", score:"74-60",  location:"H" },
    { week:9,  opponent:"Air Force",          opponentAdjEM:10.5, result:"W", score:"73-50",  location:"A" },
    { week:10, opponent:"Fresno St.",         opponentAdjEM:11.5, result:"W", score:"69-55",  location:"A" },
    { week:10, opponent:"UNLV",               opponentAdjEM:13.0, result:"W", score:"69-66",  location:"H" },
    { week:11, opponent:"Boise St.",          opponentAdjEM:14.8, result:"W", score:"68-55",  location:"A" },
    { week:11, opponent:"Wyoming",            opponentAdjEM:11.5, result:"W", score:"64-43",  location:"H" },
    { week:12, opponent:"Colorado St.",       opponentAdjEM:13.0, result:"W", score:"63-49",  location:"A" },
    { week:12, opponent:"San Jose St.",       opponentAdjEM:6.0,  result:"W", score:"65-49",  location:"H" },
    { week:13, opponent:"New Mexico",         opponentAdjEM:14.5, result:"L", score:"71-78",  location:"A" },
    { week:13, opponent:"Utah St.",           opponentAdjEM:15.6, result:"W", score:"79-66",  location:"A" },
    { week:14, opponent:"UNLV",               opponentAdjEM:13.0, result:"W", score:"65-52",  location:"A" },
    { week:14, opponent:"Fresno St.",         opponentAdjEM:11.5, result:"W", score:"71-50",  location:"H" },
    { week:15, opponent:"Nevada",             opponentAdjEM:15.0, result:"W", score:"65-56",  location:"H" },
    { week:15, opponent:"Air Force",          opponentAdjEM:10.5, result:"W", score:"86-65",  location:"H" },
    { week:16, opponent:"Wyoming",            opponentAdjEM:11.5, result:"W", score:"56-49",  location:"A" },
    { week:16, opponent:"Boise St.",          opponentAdjEM:14.8, result:"W", score:"74-65",  location:"H" },
    { week:17, opponent:"Nevada",             opponentAdjEM:15.0, result:"W", score:"60-58",  location:"A" },
    { week:18, opponent:"Air Force",          opponentAdjEM:10.5, result:"W", score:"75-55",  location:"N" },
    { week:18, opponent:"Utah St.",           opponentAdjEM:15.6, result:"L", score:"57-62",  location:"N" },
    { week:19, opponent:"Charleston",         opponentAdjEM:15.8, result:"W", score:"63-57",  location:"N" },
    { week:19, opponent:"Furman",             opponentAdjEM:15.0, result:"W", score:"75-52",  location:"N" },
    { week:19, opponent:"Alabama",            opponentAdjEM:29.5, result:"W", score:"71-64",  location:"N" },
    { week:19, opponent:"Creighton",          opponentAdjEM:22.6, result:"W", score:"57-56",  location:"N" },
    { week:20, opponent:"Florida Atlantic",   opponentAdjEM:18.6, result:"W", score:"72-71",  location:"N" },
    { week:20, opponent:"UConn",              opponentAdjEM:27.9, result:"L", score:"59-76",  location:"N" },
  ],
  "Florida Atlantic": [
    { week:1,  opponent:"South Florida",      opponentAdjEM:7.5,  result:"W", score:"81-67",  location:"H" },
    { week:1,  opponent:"Loyola (NO)",        opponentAdjEM:1.0,  result:"W", score:"105-58", location:"H" },
    { week:2,  opponent:"Texas A&M-CC",       opponentAdjEM:10.5, result:"W", score:"78-66",  location:"N" },
    { week:2,  opponent:"Loyola Chicago",     opponentAdjEM:13.0, result:"W", score:"79-66",  location:"N" },
    { week:3,  opponent:"Butler",             opponentAdjEM:11.5, result:"W", score:"66-65",  location:"N" },
    { week:3,  opponent:"Ole Miss",           opponentAdjEM:13.5, result:"W", score:"68-67",  location:"N" },
    { week:4,  opponent:"Florida",            opponentAdjEM:16.5, result:"L", score:"56-69",  location:"A" },
    { week:5,  opponent:"Florida Gulf Coast", opponentAdjEM:10.0, result:"W", score:"75-68",  location:"H" },
    { week:6,  opponent:"FIU",                opponentAdjEM:8.5,  result:"W", score:"79-69",  location:"H" },
    { week:7,  opponent:"Liberty",            opponentAdjEM:11.0, result:"L", score:"67-77",  location:"A" },
    { week:8,  opponent:"Western Ky.",        opponentAdjEM:10.0, result:"W", score:"79-65",  location:"H" },
    { week:8,  opponent:"Charlotte",          opponentAdjEM:10.0, result:"W", score:"68-49",  location:"A" },
    { week:9,  opponent:"UAB",                opponentAdjEM:13.5, result:"W", score:"76-66",  location:"H" },
    { week:9,  opponent:"Louisiana Tech",     opponentAdjEM:10.5, result:"W", score:"74-69",  location:"A" },
    { week:10, opponent:"North Texas",        opponentAdjEM:13.5, result:"L", score:"61-68",  location:"A" },
    { week:11, opponent:"Rice",               opponentAdjEM:11.5, result:"W", score:"86-78",  location:"H" },
    { week:11, opponent:"UTSA",               opponentAdjEM:9.0,  result:"W", score:"78-68",  location:"A" },
    { week:12, opponent:"Middle Tenn.",       opponentAdjEM:11.0, result:"W", score:"81-69",  location:"H" },
    { week:13, opponent:"Charlotte",          opponentAdjEM:10.0, result:"W", score:"100-71", location:"H" },
    { week:13, opponent:"Western Ky.",        opponentAdjEM:10.0, result:"W", score:"74-68",  location:"A" },
    { week:14, opponent:"FIU",                opponentAdjEM:8.5,  result:"W", score:"83-65",  location:"A" },
    { week:14, opponent:"UTSA",               opponentAdjEM:9.0,  result:"W", score:"86-72",  location:"H" },
    { week:15, opponent:"UAB",                opponentAdjEM:13.5, result:"L", score:"72-83",  location:"A" },
    { week:15, opponent:"UTEP",               opponentAdjEM:11.0, result:"W", score:"73-50",  location:"H" },
    { week:16, opponent:"Louisiana Tech",     opponentAdjEM:10.5, result:"W", score:"74-65",  location:"H" },
    { week:16, opponent:"North Texas",        opponentAdjEM:13.5, result:"W", score:"79-69",  location:"H" },
    { week:17, opponent:"Rice",               opponentAdjEM:11.5, result:"W", score:"85-67",  location:"A" },
    { week:17, opponent:"UAB",                opponentAdjEM:13.5, result:"W", score:"73-67",  location:"N" },
    { week:18, opponent:"UAB",                opponentAdjEM:13.5, result:"W", score:"56-49",  location:"N" },
    { week:19, opponent:"Memphis",            opponentAdjEM:17.5, result:"W", score:"66-65",  location:"N" },
    { week:19, opponent:"Fairleigh Dickinson",opponentAdjEM:8.5,  result:"W", score:"78-70",  location:"N" },
    { week:19, opponent:"Tennessee",          opponentAdjEM:25.5, result:"W", score:"62-55",  location:"N" },
    { week:19, opponent:"Kansas St.",         opponentAdjEM:20.4, result:"W", score:"79-76",  location:"N" },
    { week:20, opponent:"San Diego St.",      opponentAdjEM:22.0, result:"L", score:"71-72",  location:"N" },
  ],
};

// ── Dividend events ────────────────────────────────────────────────────────
const DIVIDEND_EVENTS = [
  // UConn — National Champions
  { team:"UConn", week:1,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:1,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:2,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:2,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:3,  event:"Wins multi-team tournament",    value:10 },
  { team:"UConn", week:4,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:4,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:5,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:6,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:6,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:7,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:9,  event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:9,  event:"Wins a game",                   value:1  },
  { team:"UConn", week:11, event:"Wins a game",                   value:1  },
  { team:"UConn", week:12, event:"Wins a game",                   value:1  },
  { team:"UConn", week:12, event:"Wins a game",                   value:1  },
  { team:"UConn", week:13, event:"Wins a game",                   value:1  },
  { team:"UConn", week:13, event:"Wins a game",                   value:1  },
  { team:"UConn", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:14, event:"Wins a game",                   value:1  },
  { team:"UConn", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:16, event:"Wins a game",                   value:1  },
  { team:"UConn", week:16, event:"Wins a game",                   value:1  },
  { team:"UConn", week:18, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:18, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"UConn", week:19, event:"Wins a game",                   value:1  },
  { team:"UConn", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"UConn", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"UConn", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"UConn", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"UConn", week:20, event:"Reaches Final Four",             value:80 },
  { team:"UConn", week:20, event:"Wins NCAA Championship",         value:150},

  // San Diego St. — Runner-up
  { team:"San Diego St.", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"San Diego St.", week:7,  event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:7,  event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:8,  event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:9,  event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:9,  event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:11, event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:11, event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:14, event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:14, event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:18, event:"Wins Mountain West tournament", value:15 },
  { team:"San Diego St.", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"San Diego St.", week:19, event:"Wins a game",                   value:1  },
  { team:"San Diego St.", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"San Diego St.", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"San Diego St.", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"San Diego St.", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"San Diego St.", week:20, event:"Reaches Final Four",             value:80 },
  { team:"San Diego St.", week:20, event:"NCAA Championship runner-up",    value:100},

  // Florida Atlantic — Cinderella Final Four (9-seed)
  { team:"Florida Atlantic", week:2,  event:"Wins multi-team tournament",  value:10 },
  { team:"Florida Atlantic", week:7,  event:"Wins a game",                  value:1  },
  { team:"Florida Atlantic", week:11, event:"Wins a game",                  value:1  },
  { team:"Florida Atlantic", week:11, event:"Wins a game",                  value:1  },
  { team:"Florida Atlantic", week:14, event:"Wins a game",                  value:1  },
  { team:"Florida Atlantic", week:14, event:"Wins a game",                  value:1  },
  { team:"Florida Atlantic", week:17, event:"Wins outright league title",   value:30 },
  { team:"Florida Atlantic", week:18, event:"Wins C-USA tournament",        value:15 },
  { team:"Florida Atlantic", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Florida Atlantic", week:19, event:"Wins a game",                  value:1  },
  { team:"Florida Atlantic", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Florida Atlantic", week:19, event:"Reaches Sweet Sixteen",         value:20 },
  { team:"Florida Atlantic", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Florida Atlantic", week:19, event:"Reaches Elite Eight",           value:40 },
  { team:"Florida Atlantic", week:20, event:"Reaches Final Four",            value:80 },

  // Miami (FL) — Final Four
  { team:"Miami (FL)", week:11, event:"Wins a game",                  value:1  },
  { team:"Miami (FL)", week:14, event:"Wins a game",                  value:1  },
  { team:"Miami (FL)", week:17, event:"Wins contested league title",  value:20 },
  { team:"Miami (FL)", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Miami (FL)", week:19, event:"Wins a game",                  value:1  },
  { team:"Miami (FL)", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Miami (FL)", week:19, event:"Reaches Sweet Sixteen",         value:20 },
  { team:"Miami (FL)", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Miami (FL)", week:19, event:"Reaches Elite Eight",           value:40 },
  { team:"Miami (FL)", week:20, event:"Reaches Final Four",            value:80 },

  // Houston — #1 overall seed, Sweet 16
  { team:"Houston", week:1,  event:"Wins a game",                   value:1  },
  { team:"Houston", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"Houston", week:4,  event:"Wins a top-25 team",            value:5  },
  { team:"Houston", week:6,  event:"Wins a game",                   value:1  },
  { team:"Houston", week:7,  event:"Wins a game",                   value:1  },
  { team:"Houston", week:8,  event:"Wins a game",                   value:1  },
  { team:"Houston", week:11, event:"Wins a game",                   value:1  },
  { team:"Houston", week:12, event:"Wins a game",                   value:1  },
  { team:"Houston", week:13, event:"Wins a game",                   value:1  },
  { team:"Houston", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"Houston", week:14, event:"Wins a game",                   value:1  },
  { team:"Houston", week:15, event:"Wins a game",                   value:1  },
  { team:"Houston", week:16, event:"Wins a game",                   value:1  },
  { team:"Houston", week:17, event:"Wins outright league title",    value:30 },
  { team:"Houston", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Houston", week:19, event:"Wins a game",                   value:1  },
  { team:"Houston", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Houston", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Alabama — #1 seed, Sweet 16
  { team:"Alabama", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:5,  event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:5,  event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:6,  event:"Wins a game",                   value:1  },
  { team:"Alabama", week:9,  event:"Wins a game",                   value:1  },
  { team:"Alabama", week:9,  event:"Wins a game",                   value:1  },
  { team:"Alabama", week:10, event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:11, event:"Wins a game",                   value:1  },
  { team:"Alabama", week:12, event:"Wins a game",                   value:1  },
  { team:"Alabama", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:14, event:"Wins a game",                   value:1  },
  { team:"Alabama", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:16, event:"Wins a top-25 team",            value:5  },
  { team:"Alabama", week:17, event:"Wins outright league title",    value:30 },
  { team:"Alabama", week:18, event:"Wins SEC tournament",           value:15 },
  { team:"Alabama", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Alabama", week:19, event:"Wins a game",                   value:1  },
  { team:"Alabama", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Alabama", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Purdue — #1 seed, lost to FDU 1st round (16-over-1 upset)
  { team:"Purdue", week:1,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:3,  event:"Wins multi-team tournament",    value:10 },
  { team:"Purdue", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:4,  event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:5,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:6,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:8,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:9,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:10, event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:12, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:13, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:14, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:15, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:16, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:16, event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:17, event:"Wins outright league title",    value:30 },
  { team:"Purdue", week:18, event:"Wins Big Ten tournament",       value:15 },
  { team:"Purdue", week:19, event:"Makes the NCAA tournament",     value:10 },

  // Kansas — defending champions, lost in 2nd round
  { team:"Kansas", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:3,  event:"Wins multi-team tournament",    value:10 },
  { team:"Kansas", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:6,  event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:7,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:8,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:10, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:12, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:14, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:14, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:16, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:17, event:"Wins outright league title",    value:30 },
  { team:"Kansas", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Kansas", week:19, event:"Wins a game",                   value:1  },

  // Texas — Big 12 tournament, Elite Eight
  { team:"Texas", week:5,  event:"Wins a top-25 team",            value:5  },
  { team:"Texas", week:11, event:"Wins a game",                   value:1  },
  { team:"Texas", week:12, event:"Wins a top-25 team",            value:5  },
  { team:"Texas", week:13, event:"Wins a game",                   value:1  },
  { team:"Texas", week:18, event:"Wins Big 12 tournament",        value:15 },
  { team:"Texas", week:18, event:"Wins a top-25 team",            value:5  },
  { team:"Texas", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Texas", week:19, event:"Wins a game",                   value:1  },
  { team:"Texas", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Texas", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Texas", week:19, event:"Reaches Elite Eight",            value:40 },

  // Marquette — Big East tournament champs, Sweet 16
  { team:"Marquette", week:8,  event:"Wins a top-25 team",            value:5  },
  { team:"Marquette", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Marquette", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Marquette", week:16, event:"Wins a top-25 team",            value:5  },
  { team:"Marquette", week:17, event:"Wins outright league title",    value:30 },
  { team:"Marquette", week:17, event:"Wins a top-25 team",            value:5  },
  { team:"Marquette", week:18, event:"Wins Big East tournament",      value:15 },
  { team:"Marquette", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Marquette", week:19, event:"Wins a game",                   value:1  },
  { team:"Marquette", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Marquette", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Princeton — 15-seed Sweet Sixteen Cinderella
  { team:"Princeton", week:18, event:"Wins Ivy League tournament",  value:15 },
  { team:"Princeton", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Princeton", week:19, event:"Wins a game",                 value:1  },
  { team:"Princeton", week:19, event:"Wins a top-25 team",          value:5  },
  { team:"Princeton", week:19, event:"Reaches Round of 32",          value:10 },
  { team:"Princeton", week:19, event:"Reaches Sweet Sixteen",        value:20 },

  // Creighton — Elite Eight
  { team:"Creighton", week:10, event:"Wins a top-25 team",            value:5  },
  { team:"Creighton", week:13, event:"Wins a game",                   value:1  },
  { team:"Creighton", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Creighton", week:19, event:"Wins a game",                   value:1  },
  { team:"Creighton", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Creighton", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Creighton", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Creighton", week:19, event:"Reaches Elite Eight",            value:40 },

  // Kansas St. — Elite Eight
  { team:"Kansas St.", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas St.", week:13, event:"Wins a game",                   value:1  },
  { team:"Kansas St.", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Kansas St.", week:19, event:"Wins a game",                   value:1  },
  { team:"Kansas St.", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Kansas St.", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Kansas St.", week:19, event:"Reaches Elite Eight",            value:40 },

  // Gonzaga — Elite Eight
  { team:"Gonzaga", week:5,  event:"Wins a top-25 team",            value:5  },
  { team:"Gonzaga", week:17, event:"Wins outright league title",    value:30 },
  { team:"Gonzaga", week:18, event:"Wins WCC tournament",           value:15 },
  { team:"Gonzaga", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Gonzaga", week:19, event:"Wins a game",                   value:1  },
  { team:"Gonzaga", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Gonzaga", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Gonzaga", week:19, event:"Reaches Elite Eight",            value:40 },

  // Tennessee — Sweet 16
  { team:"Tennessee", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Tennessee", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Tennessee", week:19, event:"Wins a game",                   value:1  },
  { team:"Tennessee", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Tennessee", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Arkansas — Sweet 16
  { team:"Arkansas", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Arkansas", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Arkansas", week:19, event:"Wins a game",                   value:1  },
  { team:"Arkansas", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Arkansas", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // UCLA — Sweet 16
  { team:"UCLA", week:7,  event:"Wins a top-25 team",            value:5  },
  { team:"UCLA", week:17, event:"Wins outright league title",    value:30 },
  { team:"UCLA", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"UCLA", week:19, event:"Wins a game",                   value:1  },
  { team:"UCLA", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"UCLA", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Michigan St. — Sweet 16
  { team:"Michigan St.", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Michigan St.", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Michigan St.", week:19, event:"Wins a game",                   value:1  },
  { team:"Michigan St.", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Michigan St.", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Xavier — Sweet 16
  { team:"Xavier", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Xavier", week:18, event:"Wins a top-25 team",            value:5  },
  { team:"Xavier", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Xavier", week:19, event:"Wins a game",                   value:1  },
  { team:"Xavier", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Xavier", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // FDU — historic 16-over-1 upset of Purdue
  { team:"FDU", week:18, event:"Wins NEC tournament",            value:15 },
  { team:"FDU", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"FDU", week:19, event:"Wins a game",                    value:1  },
  { team:"FDU", week:19, event:"Wins a top-25 team",             value:5  },

  // North Carolina — preseason #1, missed tournament (notable disappointment)
  { team:"North Carolina", week:3, event:"Wins a top-25 team",  value:5  },

  // Other tournament wins / Notable conference champs

  // Iowa St. — Big 12 contender
  { team:"Iowa St.", week:6,  event:"Wins a top-25 team",            value:5  },
  { team:"Iowa St.", week:9,  event:"Wins a top-25 team",            value:5  },
  { team:"Iowa St.", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Iowa St.", week:19, event:"Wins a game",                   value:1  },
  { team:"Iowa St.", week:19, event:"Reaches Round of 32",            value:10 },

  // Memphis — AAC tournament champs
  { team:"Memphis", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Memphis", week:14, event:"Wins a game",                   value:1  },
  { team:"Memphis", week:17, event:"Wins AAC tournament",           value:15 },
  { team:"Memphis", week:19, event:"Makes the NCAA tournament",     value:10 },

  // Charleston — CAA champs
  { team:"Charleston", week:17, event:"Wins outright league title",  value:30 },
  { team:"Charleston", week:18, event:"Wins CAA tournament",         value:15 },
  { team:"Charleston", week:19, event:"Makes the NCAA tournament",   value:10 },

  // Furman — SoCon champs
  { team:"Furman", week:18, event:"Wins SoCon tournament",          value:15 },
  { team:"Furman", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Furman", week:19, event:"Wins a game",                    value:1  },
  { team:"Furman", week:19, event:"Wins a top-25 team",             value:5  },

  // Vermont — America East
  { team:"Vermont", week:18, event:"Wins America East tournament", value:15 },
  { team:"Vermont", week:19, event:"Makes the NCAA tournament",    value:10 },

  // Colgate — Patriot
  { team:"Colgate", week:18, event:"Wins Patriot tournament",      value:15 },
  { team:"Colgate", week:19, event:"Makes the NCAA tournament",    value:10 },

  // Iona — MAAC
  { team:"Iona", week:18, event:"Wins MAAC tournament",            value:15 },
  { team:"Iona", week:19, event:"Makes the NCAA tournament",       value:10 },

  // Drake — MVC
  { team:"Drake", week:18, event:"Wins MVC tournament",            value:15 },
  { team:"Drake", week:19, event:"Makes the NCAA tournament",      value:10 },

  // Kennesaw St. — ASUN champions
  { team:"Kennesaw St.", week:18, event:"Wins ASUN tournament",    value:15 },
  { team:"Kennesaw St.", week:19, event:"Makes the NCAA tournament", value:10 },

  // Texas A&M-CC — Southland champions
  { team:"Texas A&M-CC", week:18, event:"Wins Southland tournament", value:15 },
  { team:"Texas A&M-CC", week:19, event:"Makes the NCAA tournament", value:10 },

  // Northern Kentucky — Horizon
  { team:"Northern Kentucky", week:18, event:"Wins Horizon tournament", value:15 },
  { team:"Northern Kentucky", week:19, event:"Makes the NCAA tournament", value:10 },

  // Grand Canyon — WAC
  { team:"Grand Canyon", week:18, event:"Wins WAC tournament",     value:15 },
  { team:"Grand Canyon", week:19, event:"Makes the NCAA tournament", value:10 },

  // Montana St. — Big Sky
  { team:"Montana St.", week:18, event:"Wins Big Sky tournament", value:15 },
  { team:"Montana St.", week:19, event:"Makes the NCAA tournament", value:10 },

  // Howard — MEAC
  { team:"Howard", week:18, event:"Wins MEAC tournament",          value:15 },
  { team:"Howard", week:19, event:"Makes the NCAA tournament",     value:10 },

  // Louisiana — Sun Belt
  { team:"Louisiana", week:18, event:"Wins Sun Belt tournament",   value:15 },
  { team:"Louisiana", week:19, event:"Makes the NCAA tournament",  value:10 },

  // Oral Roberts — Summit
  { team:"Oral Roberts", week:17, event:"Wins outright league title", value:30 },
  { team:"Oral Roberts", week:18, event:"Wins Summit tournament", value:15 },
  { team:"Oral Roberts", week:19, event:"Makes the NCAA tournament", value:10 },

  // Kent St. — MAC champs
  { team:"Kent St.", week:17, event:"Wins outright league title", value:30 },
  { team:"Kent St.", week:18, event:"Wins MAC tournament",        value:15 },
  { team:"Kent St.", week:19, event:"Makes the NCAA tournament", value:10 },

  // UNC Asheville — Big South
  { team:"UNC Asheville", week:18, event:"Wins Big South tournament", value:15 },
  { team:"UNC Asheville", week:19, event:"Makes the NCAA tournament", value:10 },

  // Texas Southern — SWAC
  { team:"Texas Southern", week:18, event:"Wins SWAC tournament", value:15 },
  { team:"Texas Southern", week:19, event:"Makes the NCAA tournament", value:10 },
];

const EVENTS_BY_WEEK = {};
for (const evt of DIVIDEND_EVENTS) {
  if (!EVENTS_BY_WEEK[evt.week]) EVENTS_BY_WEEK[evt.week] = [];
  EVENTS_BY_WEEK[evt.week].push(evt);
}

export const SEASON_2023 = {
  id: "2022-23",
  label: "2022-23",
  champion: "UConn",
  WEEKS,
  TEAM_HISTORY,
  SCHEDULES,
  DIVIDEND_EVENTS,
  EVENTS_BY_WEEK,
};
