// season2018.js — 2017-18 college basketball season
// Champion: Villanova (defeated Michigan 79-62)
// Final Four: Villanova, Michigan, Loyola Chicago, Kansas
// Notable: UMBC becomes first 16-seed to beat a 1-seed (def. Virginia 74-54)
//          Loyola Chicago's Sister Jean Final Four run from MVC
//          Trae Young's scoring spectacle at Oklahoma
//          Jalen Brunson Naismith POY, Donte DiVincenzo MOP
//
// AdjEM values are season-accurate approximations based on published KenPom
// end/mid-season ratings. Weekly values use smooth trajectories with seeded variance.

function traj(start, end, seed) {
  const n = 20;
  const out = [];
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1);
    const base = start + (end - start) * t;
    const noise = (Math.sin(i * seed * 2.3 + seed) + Math.cos(i * seed * 1.7)) * 0.35;
    out.push(Math.round((base + noise) * 100) / 100);
  }
  out[n - 1] = end;
  return out;
}

function rec(w, l) {
  const n = 20;
  return Array.from({ length: n }, (_, i) => {
    const t = i / (n - 1);
    return `${Math.round(w * t)}-${Math.round(l * t)}`;
  });
}

const WEEKS = [
  "Week 1 (Nov 13)", "Week 2 (Nov 20)", "Week 3 (Nov 27)", "Week 4 (Dec 4)",
  "Week 5 (Dec 11)", "Week 6 (Dec 18)", "Week 7 (Dec 25)", "Week 8 (Jan 1)",
  "Week 9 (Jan 8)",  "Week 10 (Jan 15)","Week 11 (Jan 22)","Week 12 (Jan 29)",
  "Week 13 (Feb 5)", "Week 14 (Feb 12)","Week 15 (Feb 19)","Week 16 (Feb 26)",
  "Week 17 (Mar 5)", "Week 18 (Mar 12)","Week 19 (Mar 19)","Week 20 (Mar 26)",
];

// [team, conference, startAdjEM, endAdjEM, wins, losses, seed]
const RAW = [
  // ── Power conferences — elite ─────────────────────────────────────────────
  ["Villanova",       "Big East",       24.0,  31.1,  36,  4,  1],
  ["Virginia",        "ACC",            22.5,  27.0,  31,  3,  2],
  ["Duke",            "ACC",            22.0,  26.5,  29,  8,  3],
  ["Michigan St.",    "Big Ten",        23.5,  25.7,  30,  5,  4],
  ["North Carolina",  "ACC",            21.0,  24.5,  26, 11,  5],
  ["Cincinnati",      "American",       20.0,  24.0,  31,  5,  6],
  ["Wichita St.",     "American",       21.5,  24.0,  25,  8,  7],
  ["Kentucky",        "SEC",            19.5,  23.5,  26, 11,  8],
  ["Purdue",          "Big Ten",        20.5,  23.5,  30,  7,  9],
  ["Gonzaga",         "WCC",            21.0,  23.5,  32,  5, 10],
  ["Kansas",          "Big 12",         20.0,  22.6,  31,  8, 11],
  ["Michigan",        "Big Ten",        18.5,  22.0,  33,  8, 12],
  ["Xavier",          "Big East",       19.0,  22.0,  29,  6, 13],
  ["Auburn",          "SEC",            17.5,  22.0,  26,  8, 14],
  ["Tennessee",       "SEC",            17.0,  21.5,  26,  9, 15],
  ["Texas Tech",      "Big 12",         18.0,  21.5,  27, 10, 16],
  ["Arizona",         "Pac-12",         20.0,  21.5,  27,  8, 17],
  ["West Virginia",   "Big 12",         19.5,  21.0,  26, 11, 18],
  ["Houston",         "American",       17.5,  21.0,  27,  8, 19],
  ["Clemson",         "ACC",            16.5,  20.5,  25, 10, 20],
  ["Saint Mary's",    "WCC",            18.5,  20.0,  30,  6, 21],
  ["Ohio St.",        "Big Ten",        17.0,  20.0,  25,  9, 22],
  ["Florida",         "SEC",            18.5,  19.5,  21, 13, 23],
  ["Florida St.",     "ACC",            16.0,  19.0,  23, 12, 24],
  ["Texas",           "Big 12",         16.5,  18.5,  19, 15, 25],
  ["Texas A&M",       "SEC",            17.0,  18.0,  22, 13, 26],
  ["Nevada",          "Mountain West",  15.5,  18.0,  29,  8, 27],
  ["TCU",             "Big 12",         16.5,  17.5,  21, 12, 28],
  ["Miami (FL)",      "ACC",            16.0,  17.5,  22, 10, 29],
  ["Oklahoma",        "Big 12",         16.5,  17.0,  18, 14, 30],
  ["Arkansas",        "SEC",            15.0,  17.0,  23, 12, 31],
  ["Missouri",        "SEC",            14.0,  16.5,  20, 13, 32],
  ["Kansas St.",      "Big 12",         14.0,  16.0,  25, 12, 33],
  ["Seton Hall",      "Big East",       14.5,  17.5,  22, 12, 34],
  ["Creighton",       "Big East",       14.0,  17.0,  21, 12, 35],
  ["Providence",      "Big East",       13.5,  16.5,  21, 14, 36],
  ["Butler",          "Big East",       13.0,  17.0,  21, 14, 37],
  ["Rhode Island",    "Atlantic 10",    13.0,  16.0,  26,  8, 38],
  ["Loyola Chicago",  "Missouri Valley",10.5,  14.0,  32,  6, 39],
  ["UCLA",            "Pac-12",         13.5,  15.5,  21, 12, 40],
  ["USC",             "Pac-12",         14.0,  16.0,  24, 12, 41],
  ["Arizona St.",     "Pac-12",         13.0,  15.0,  20, 12, 42],
  ["Stanford",        "Pac-12",         11.5,  13.0,  19, 16, 43],
  ["Oregon",          "Pac-12",         12.5,  14.0,  23, 13, 44],
  ["Utah",            "Pac-12",         12.0,  14.0,  23, 12, 45],
  ["Washington",      "Pac-12",         11.0,  13.5,  21, 13, 46],
  ["Colorado",        "Pac-12",         11.0,  13.0,  17, 15, 47],
  ["Oregon St.",      "Pac-12",         10.0,  12.0,  16, 16, 48],
  ["Washington St.",  "Pac-12",          9.0,  11.0,  12, 19, 49],
  ["Cal",             "Pac-12",          7.5,   9.5,   8, 24, 50],
  ["Iowa St.",        "Big 12",         12.0,  14.0,  13, 18, 51],
  ["Oklahoma St.",    "Big 12",         13.0,  15.5,  21, 15, 52],
  ["Baylor",          "Big 12",         13.5,  15.0,  19, 15, 53],
  ["Wisconsin",       "Big Ten",        12.5,  14.5,  15, 18, 54],
  ["Indiana",         "Big Ten",        11.5,  13.5,  16, 15, 55],
  ["Northwestern",    "Big Ten",        12.0,  14.0,  15, 17, 56],
  ["Penn St.",        "Big Ten",        13.5,  16.0,  26, 13, 57],
  ["Maryland",        "Big Ten",        13.0,  15.0,  19, 13, 58],
  ["Nebraska",        "Big Ten",        13.5,  15.5,  22, 11, 59],
  ["Minnesota",       "Big Ten",        10.0,  12.0,  15, 17, 60],
  ["Iowa",            "Big Ten",        10.5,  12.5,  14, 19, 61],
  ["Illinois",        "Big Ten",         9.5,  11.5,  14, 18, 62],
  ["Rutgers",         "Big Ten",         8.0,  10.5,  15, 19, 63],
  ["NC State",        "ACC",            13.5,  15.5,  21, 12, 64],
  ["Virginia Tech",   "ACC",            14.0,  16.0,  21, 12, 65],
  ["Notre Dame",      "ACC",            13.0,  15.0,  21, 15, 66],
  ["Louisville",      "ACC",            12.5,  14.5,  22, 14, 67],
  ["Syracuse",        "ACC",            12.0,  14.5,  23, 14, 68],
  ["Boston College",  "ACC",            10.5,  12.5,  19, 16, 69],
  ["Georgia Tech",    "ACC",             9.0,  11.0,  13, 19, 70],
  ["Wake Forest",     "ACC",             9.0,  10.5,  11, 20, 71],
  ["Pittsburgh",      "ACC",             5.0,   7.0,   8, 24, 72],
  ["Mississippi St.", "SEC",            13.5,  15.5,  25, 12, 73],
  ["Alabama",         "SEC",            14.5,  16.5,  20, 16, 74],
  ["LSU",             "SEC",            12.0,  14.0,  18, 15, 75],
  ["South Carolina",  "SEC",            10.5,  12.5,  17, 16, 76],
  ["Vanderbilt",      "SEC",            10.0,  12.0,  12, 20, 77],
  ["Georgia",         "SEC",            10.5,  12.5,  18, 15, 78],
  ["Ole Miss",        "SEC",             9.0,  11.0,  12, 20, 79],
  ["Marquette",       "Big East",       12.5,  14.5,  21, 14, 80],
  ["Georgetown",      "Big East",        9.5,  11.5,  15, 15, 81],
  ["St. John's",      "Big East",       11.0,  13.0,  16, 17, 82],
  ["DePaul",          "Big East",        7.0,   9.0,  11, 20, 83],
  ["SMU",             "American",       13.5,  15.5,  17, 16, 84],
  ["Memphis",         "American",       11.5,  13.5,  21, 13, 85],
  ["UCF",             "American",       12.5,  14.5,  19, 13, 86],
  ["Temple",          "American",       11.0,  13.0,  17, 16, 87],
  ["Tulsa",           "American",       11.5,  13.5,  19, 12, 88],
  ["Tulane",          "American",        7.5,   9.5,  14, 17, 89],
  ["East Carolina",   "American",        7.0,   9.0,  10, 20, 90],
  ["South Florida",   "American",        7.5,   9.5,  10, 22, 91],
  ["BYU",             "WCC",            13.0,  15.0,  24, 11, 92],
  ["San Francisco",   "WCC",            10.5,  13.0,  22, 17, 93],
  ["San Diego",       "WCC",             9.0,  11.0,  20, 14, 94],
  ["Pacific",         "WCC",             7.5,   9.5,  14, 17, 95],
  ["Pepperdine",      "WCC",             7.0,   9.0,   6, 26, 96],
  ["Boise St.",       "Mountain West",  13.5,  15.5,  23,  9, 97],
  ["San Diego St.",   "Mountain West",  12.0,  14.0,  22, 11, 98],
  ["New Mexico",      "Mountain West",  11.5,  13.5,  19, 15, 99],
  ["Fresno St.",      "Mountain West",  10.5,  12.5,  21, 11,100],
  ["UNLV",            "Mountain West",   9.5,  11.5,  20, 13,101],
  ["Wyoming",         "Mountain West",   9.0,  11.0,  20, 13,102],
  ["Utah St.",        "Mountain West",   8.5,  10.5,  17, 17,103],
  ["Colorado St.",    "Mountain West",   8.0,  10.0,  11, 21,104],

  // ── Tournament Cinderellas & auto-bids ───────────────────────────────────
  ["UMBC",            "America East",    8.0,  12.0,  25, 11,105],
  ["Buffalo",         "MAC",            12.5,  15.5,  27,  9,106],
  ["Murray St.",      "OVC",            10.5,  13.5,  26,  6,107],
  ["Davidson",        "Atlantic 10",    11.5,  13.5,  21, 12,108],
  ["Marshall",        "C-USA",          11.0,  13.0,  25, 11,109],
  ["South Dakota St.","Summit",         10.0,  12.0,  28,  7,110],
  ["Stephen F. Austin","Southland",      9.0,  11.0,  28,  7,111],
  ["Bucknell",        "Patriot",         9.5,  11.5,  25, 10,112],
  ["Cal St. Fullerton","Big West",       9.0,  11.0,  20, 12,113],
  ["Charleston",      "CAA",            10.5,  12.5,  26,  8,114],
  ["Iona",            "MAAC",            9.5,  11.5,  20, 14,115],
  ["Penn",            "Ivy",             9.0,  11.0,  24,  9,116],
  ["LIU Brooklyn",    "NEC",             4.5,   7.0,  18, 17,117],
  ["UNC Greensboro",  "Southern",        9.5,  11.5,  27,  8,118],
  ["NC Central",      "MEAC",            5.5,   8.0,  19, 16,119],
  ["Lipscomb",        "ASUN",            9.0,  11.0,  23, 10,120],
  ["Texas Southern",  "SWAC",            5.5,   8.0,  16, 20,121],
  ["Radford",         "Big South",       8.0,  10.0,  23, 13,122],
  ["Wright St.",      "Horizon",         8.5,  10.5,  25, 10,123],
  ["Montana",         "Big Sky",         9.0,  11.0,  26,  8,124],
  ["New Mexico St.",  "WAC",            10.5,  12.5,  28,  6,125],
  ["Georgia St.",     "Sun Belt",       10.0,  12.0,  24, 11,126],

  // ── Atlantic 10 / mid-major depth ─────────────────────────────────────────
  ["Saint Joseph's",  "Atlantic 10",    10.0,  12.0,  16, 16,127],
  ["Saint Louis",     "Atlantic 10",     9.5,  11.5,  17, 16,128],
  ["VCU",             "Atlantic 10",    11.0,  13.0,  18, 15,129],
  ["Dayton",          "Atlantic 10",    10.5,  12.5,  14, 17,130],
  ["George Mason",    "Atlantic 10",     9.0,  11.0,  18, 15,131],
  ["Richmond",        "Atlantic 10",     9.5,  11.5,  12, 20,132],
  ["UMass",           "Atlantic 10",     8.5,  10.5,  13, 20,133],
  ["George Washington","Atlantic 10",    8.0,  10.0,  15, 18,134],
  ["La Salle",        "Atlantic 10",     7.5,   9.5,  13, 19,135],
  ["Fordham",         "Atlantic 10",     7.0,   9.0,   9, 22,136],
  ["Duquesne",        "Atlantic 10",     8.5,  10.5,  16, 16,137],
  ["St. Bonaventure", "Atlantic 10",    11.5,  13.5,  26,  8,138],

  // ── Trae Young's Oklahoma + supporting cast ──────────────────────────────
  ["Mercer",          "Southern",        7.5,   9.5,  20, 14,139],
  ["Wofford",         "Southern",        9.0,  11.0,  21, 13,140],
  ["East Tennessee St.","Southern",      8.5,  10.5,  25,  9,141],
  ["Furman",          "Southern",        8.0,  10.0,  23, 10,142],
  ["Western Carolina","Southern",        5.5,   7.5,  10, 22,143],

  // ── Other auto-bid filler ────────────────────────────────────────────────
  ["Vermont",         "America East",    9.5,  11.5,  27,  8,144],
  ["Hartford",        "America East",    6.0,   8.0,  19, 14,145],
  ["UC Santa Barbara","Big West",        7.5,   9.5,  23, 10,146],
  ["UC Irvine",       "Big West",        8.0,  10.0,  18, 17,147],
  ["UC Davis",        "Big West",        7.0,   9.0,  22, 11,148],
  ["Hofstra",         "CAA",             9.5,  11.5,  19, 12,149],
  ["Northeastern",    "CAA",             8.5,  10.5,  23, 10,150],
  ["Western Kentucky","C-USA",          11.0,  13.0,  27, 11,151],
  ["Middle Tennessee","C-USA",          10.5,  12.5,  25,  8,152],
  ["UAB",             "C-USA",           9.0,  11.0,  20, 13,153],
  ["Old Dominion",    "C-USA",           8.5,  10.5,  25,  7,154],
  ["Northern Kentucky","Horizon",        8.0,  10.0,  22, 10,155],
  ["Wright St.",      "Horizon",         8.5,  10.5,  25, 10,156],
  ["Oakland",         "Horizon",         8.0,  10.0,  25,  9,157],
  ["Harvard",         "Ivy",             8.0,  10.0,  18,  9,158],
  ["Yale",            "Ivy",             7.5,   9.5,  16, 14,159],
  ["Cornell",         "Ivy",             6.5,   8.5,  12, 16,160],
  ["Princeton",       "Ivy",             7.0,   9.0,  13, 16,161],
  ["Rider",           "MAAC",            8.5,  10.5,  22, 10,162],
  ["Canisius",        "MAAC",            7.5,   9.5,  21, 12,163],
  ["Manhattan",       "MAAC",            6.5,   8.5,  10, 23,164],
  ["Toledo",          "MAC",            10.0,  12.0,  23, 11,165],
  ["Akron",           "MAC",             9.0,  11.0,  17, 16,166],
  ["Bowling Green",   "MAC",             7.5,   9.5,  14, 18,167],
  ["Hampton",         "MEAC",            5.5,   7.5,  18, 17,168],
  ["Savannah St.",    "MEAC",            5.0,   7.0,  16, 17,169],
  ["Loyola Chicago",  "Missouri Valley",10.5,  14.0,  32,  6,170], // duplicate row guard
  ["Illinois St.",    "Missouri Valley", 8.5,  10.5,  18, 15,171],
  ["S. Illinois",     "Missouri Valley", 7.5,   9.5,  20, 14,172],
  ["Drake",           "Missouri Valley", 6.5,   8.5,  17, 17,173],
  ["Indiana St.",     "Missouri Valley", 6.0,   8.0,  13, 18,174],
  ["Bradley",         "Missouri Valley", 7.0,   9.0,  20, 13,175],
  ["Wagner",          "NEC",             6.0,   8.0,  23, 10,176],
  ["Mount St. Mary's","NEC",             4.5,   6.5,  16, 16,177],
  ["Belmont",         "OVC",             9.0,  11.0,  24,  9,178],
  ["Tennessee St.",   "OVC",             6.0,   8.0,  16, 13,179],
  ["Lehigh",          "Patriot",         8.0,  10.0,  20, 11,180],
  ["Colgate",         "Patriot",         7.0,   9.0,  17, 15,181],
  ["Navy",            "Patriot",         6.5,   8.5,  19, 13,182],
  ["Sam Houston St.", "Southland",       7.5,   9.5,  21, 11,183],
  ["Nicholls St.",    "Southland",       6.5,   8.5,  21, 12,184],
  ["South Dakota",    "Summit",          8.5,  10.5,  26,  9,185],
  ["North Dakota St.","Summit",          7.5,   9.5,  15, 17,186],
  ["Louisiana",       "Sun Belt",        8.0,  10.0,  27,  7,187],
  ["South Alabama",   "Sun Belt",        7.0,   9.0,  14, 19,188],
  ["Texas-Arlington", "Sun Belt",        9.0,  11.0,  21, 13,189],
  ["Grambling",       "SWAC",            5.0,   7.0,  17, 17,190],
  ["Prairie View A&M","SWAC",            5.5,   7.5,  20, 14,191],
  ["Grand Canyon",    "WAC",             8.5,  10.5,  22, 12,192],
  ["UT Rio Grande",   "WAC",             5.5,   7.5,  10, 19,193],
  ["Eastern Washington","Big Sky",       8.0,  10.0,  21, 15,194],
  ["Idaho",           "Big Sky",         8.0,  10.0,  22,  9,195],
  ["Weber St.",       "Big Sky",         7.5,   9.5,  20, 11,196],
  ["UNC Asheville",   "Big South",       7.5,   9.5,  21, 12,197],
  ["Liberty",         "Big South",       7.0,   9.0,  21, 15,198],
  ["Winthrop",        "Big South",       7.5,   9.5,  19, 13,199],
];

const seen = new Set();
const DEDUPLICATED = RAW.filter(([team]) => {
  if (seen.has(team)) return false;
  seen.add(team);
  return true;
});

const TEAM_HISTORY = DEDUPLICATED.map(([team, conference, start, end, wins, losses, seed]) => ({
  team,
  conference,
  weeklyAdjEM: traj(start, end, seed),
  weeklyRecord: rec(wins, losses),
}));

// ── Schedules ─────────────────────────────────────────────────────────────
// HAND_CURATED is our hand-written set for the marquee teams (richer narrative,
// known-correct AdjEM values). GENERATED_SCHEDULES is auto-pulled from KenPom
// for every D-I team. We spread generated first so HAND_CURATED wins on overlap.
import { GENERATED_SCHEDULES } from "./generated/season2018.schedules";

const HAND_CURATED = {
  "Villanova": [
    { week:1,  opponent:"Columbia",            opponentAdjEM:6.0,  result:"W", score:"83-62",  location:"H" },
    { week:1,  opponent:"Nicholls St.",        opponentAdjEM:8.5,  result:"W", score:"112-58", location:"H" },
    { week:2,  opponent:"Western Kentucky",    opponentAdjEM:13.0, result:"W", score:"82-60",  location:"H" },
    { week:2,  opponent:"Tennessee",           opponentAdjEM:21.5, result:"W", score:"67-61",  location:"N" },
    { week:2,  opponent:"Purdue",              opponentAdjEM:23.5, result:"W", score:"81-58",  location:"N" },
    { week:3,  opponent:"Lafayette",           opponentAdjEM:5.5,  result:"W", score:"108-67", location:"H" },
    { week:3,  opponent:"Gonzaga",             opponentAdjEM:23.5, result:"W", score:"88-72",  location:"N" },
    { week:4,  opponent:"Saint Joseph's",      opponentAdjEM:12.0, result:"W", score:"88-57",  location:"H" },
    { week:4,  opponent:"La Salle",            opponentAdjEM:9.5,  result:"W", score:"89-79",  location:"H" },
    { week:5,  opponent:"Temple",              opponentAdjEM:13.0, result:"W", score:"103-67", location:"H" },
    { week:5,  opponent:"American",            opponentAdjEM:5.0,  result:"W", score:"83-50",  location:"H" },
    { week:6,  opponent:"Penn",                opponentAdjEM:11.0, result:"W", score:"78-57",  location:"H" },
    { week:7,  opponent:"DePaul",              opponentAdjEM:9.0,  result:"W", score:"95-71",  location:"H" },
    { week:8,  opponent:"Marquette",           opponentAdjEM:14.5, result:"W", score:"94-70",  location:"A" },
    { week:8,  opponent:"Xavier",              opponentAdjEM:22.0, result:"L", score:"82-89",  location:"A" },
    { week:9,  opponent:"Butler",              opponentAdjEM:17.0, result:"L", score:"98-101", location:"H" },
    { week:9,  opponent:"Creighton",           opponentAdjEM:17.0, result:"W", score:"82-65",  location:"H" },
    { week:10, opponent:"Providence",          opponentAdjEM:16.5, result:"W", score:"89-69",  location:"H" },
    { week:10, opponent:"Georgetown",          opponentAdjEM:11.5, result:"W", score:"88-56",  location:"A" },
    { week:11, opponent:"Seton Hall",          opponentAdjEM:17.5, result:"W", score:"76-71",  location:"H" },
    { week:11, opponent:"St. John's",          opponentAdjEM:13.0, result:"L", score:"77-79",  location:"H" },
    { week:12, opponent:"DePaul",              opponentAdjEM:9.0,  result:"W", score:"81-65",  location:"A" },
    { week:12, opponent:"Marquette",           opponentAdjEM:14.5, result:"W", score:"86-65",  location:"H" },
    { week:13, opponent:"St. John's",          opponentAdjEM:13.0, result:"W", score:"89-75",  location:"A" },
    { week:13, opponent:"Butler",              opponentAdjEM:17.0, result:"W", score:"86-75",  location:"A" },
    { week:14, opponent:"Xavier",              opponentAdjEM:22.0, result:"W", score:"95-79",  location:"H" },
    { week:14, opponent:"Providence",          opponentAdjEM:16.5, result:"W", score:"75-71",  location:"A" },
    { week:15, opponent:"Creighton",           opponentAdjEM:17.0, result:"W", score:"99-74",  location:"A" },
    { week:15, opponent:"Georgetown",          opponentAdjEM:11.5, result:"W", score:"73-69",  location:"H" },
    { week:16, opponent:"Seton Hall",          opponentAdjEM:17.5, result:"L", score:"68-70",  location:"A" },
    { week:17, opponent:"Marquette",           opponentAdjEM:14.5, result:"W", score:"94-70",  location:"N" },
    { week:17, opponent:"Butler",              opponentAdjEM:17.0, result:"W", score:"87-68",  location:"N" },
    { week:17, opponent:"Providence",          opponentAdjEM:16.5, result:"W", score:"76-66",  location:"N" },
    { week:19, opponent:"LIU Brooklyn",        opponentAdjEM:7.0,  result:"W", score:"87-57",  location:"N" },
    { week:19, opponent:"Alabama",             opponentAdjEM:16.5, result:"W", score:"81-58",  location:"N" },
    { week:19, opponent:"West Virginia",       opponentAdjEM:21.0, result:"W", score:"90-78",  location:"N" },
    { week:19, opponent:"Texas Tech",          opponentAdjEM:21.5, result:"W", score:"71-59",  location:"N" },
    { week:20, opponent:"Kansas",              opponentAdjEM:22.6, result:"W", score:"95-79",  location:"N" },
    { week:20, opponent:"Michigan",            opponentAdjEM:22.0, result:"W", score:"79-62",  location:"N" },
  ],
  "Michigan": [
    { week:1,  opponent:"North Florida",       opponentAdjEM:5.0,  result:"W", score:"86-66",  location:"H" },
    { week:1,  opponent:"Central Michigan",    opponentAdjEM:6.0,  result:"W", score:"99-79",  location:"H" },
    { week:2,  opponent:"Southern Mississippi",opponentAdjEM:6.5,  result:"W", score:"82-50",  location:"H" },
    { week:2,  opponent:"VCU",                 opponentAdjEM:13.0, result:"L", score:"75-78",  location:"N" },
    { week:2,  opponent:"LSU",                 opponentAdjEM:14.0, result:"W", score:"76-65",  location:"N" },
    { week:3,  opponent:"North Carolina",      opponentAdjEM:24.5, result:"W", score:"86-71",  location:"N" },
    { week:3,  opponent:"UC Riverside",        opponentAdjEM:5.5,  result:"W", score:"85-39",  location:"H" },
    { week:4,  opponent:"Texas",               opponentAdjEM:18.5, result:"W", score:"59-53",  location:"H" },
    { week:4,  opponent:"Indiana",             opponentAdjEM:13.5, result:"L", score:"66-69",  location:"A" },
    { week:5,  opponent:"UCLA",                opponentAdjEM:15.5, result:"W", score:"78-69",  location:"H" },
    { week:5,  opponent:"Detroit Mercy",       opponentAdjEM:5.0,  result:"W", score:"90-58",  location:"A" },
    { week:6,  opponent:"Alabama A&M",         opponentAdjEM:1.0,  result:"W", score:"82-49",  location:"H" },
    { week:7,  opponent:"Ohio St.",            opponentAdjEM:20.0, result:"L", score:"68-71",  location:"A" },
    { week:8,  opponent:"Iowa",                opponentAdjEM:12.5, result:"W", score:"75-68",  location:"H" },
    { week:8,  opponent:"Illinois",            opponentAdjEM:11.5, result:"W", score:"79-69",  location:"A" },
    { week:9,  opponent:"Maryland",            opponentAdjEM:15.0, result:"W", score:"68-67",  location:"H" },
    { week:9,  opponent:"Michigan St.",        opponentAdjEM:25.7, result:"L", score:"72-82",  location:"A" },
    { week:10, opponent:"Nebraska",            opponentAdjEM:15.5, result:"W", score:"58-72",  location:"A" },
    { week:10, opponent:"Rutgers",             opponentAdjEM:10.5, result:"W", score:"77-58",  location:"H" },
    { week:11, opponent:"Maryland",            opponentAdjEM:15.0, result:"W", score:"85-61",  location:"A" },
    { week:11, opponent:"Northwestern",        opponentAdjEM:14.0, result:"W", score:"58-47",  location:"H" },
    { week:12, opponent:"Minnesota",           opponentAdjEM:12.0, result:"W", score:"83-78",  location:"A" },
    { week:12, opponent:"Purdue",              opponentAdjEM:23.5, result:"L", score:"70-92",  location:"A" },
    { week:13, opponent:"Northwestern",        opponentAdjEM:14.0, result:"W", score:"61-52",  location:"A" },
    { week:13, opponent:"Penn St.",            opponentAdjEM:16.0, result:"W", score:"72-63",  location:"H" },
    { week:14, opponent:"Wisconsin",           opponentAdjEM:14.5, result:"W", score:"68-64",  location:"A" },
    { week:14, opponent:"Ohio St.",            opponentAdjEM:20.0, result:"W", score:"74-62",  location:"H" },
    { week:15, opponent:"Iowa",                opponentAdjEM:12.5, result:"W", score:"74-59",  location:"A" },
    { week:15, opponent:"Maryland",            opponentAdjEM:15.0, result:"W", score:"85-61",  location:"H" },
    { week:16, opponent:"Penn St.",            opponentAdjEM:16.0, result:"L", score:"72-79",  location:"A" },
    { week:16, opponent:"Michigan St.",        opponentAdjEM:25.7, result:"W", score:"75-64",  location:"H" },
    { week:17, opponent:"Iowa",                opponentAdjEM:12.5, result:"W", score:"77-71",  location:"N" },
    { week:17, opponent:"Nebraska",            opponentAdjEM:15.5, result:"W", score:"77-58",  location:"N" },
    { week:17, opponent:"Michigan St.",        opponentAdjEM:25.7, result:"W", score:"75-64",  location:"N" },
    { week:17, opponent:"Purdue",              opponentAdjEM:23.5, result:"W", score:"75-66",  location:"N" },
    { week:19, opponent:"Montana",             opponentAdjEM:11.0, result:"W", score:"61-47",  location:"N" },
    { week:19, opponent:"Houston",             opponentAdjEM:21.0, result:"W", score:"64-63",  location:"N" },
    { week:19, opponent:"Texas A&M",           opponentAdjEM:18.0, result:"W", score:"99-72",  location:"N" },
    { week:19, opponent:"Florida St.",         opponentAdjEM:19.0, result:"W", score:"58-54",  location:"N" },
    { week:20, opponent:"Loyola Chicago",      opponentAdjEM:14.0, result:"W", score:"69-57",  location:"N" },
    { week:20, opponent:"Villanova",           opponentAdjEM:31.1, result:"L", score:"62-79",  location:"N" },
  ],
  "Loyola Chicago": [
    { week:1,  opponent:"UW-Milwaukee",        opponentAdjEM:5.0,  result:"W", score:"100-69", location:"H" },
    { week:1,  opponent:"Wright St.",          opponentAdjEM:10.5, result:"W", score:"75-68",  location:"H" },
    { week:2,  opponent:"Florida",             opponentAdjEM:19.5, result:"W", score:"65-59",  location:"A" },
    { week:2,  opponent:"Boise St.",           opponentAdjEM:15.5, result:"W", score:"70-66",  location:"N" },
    { week:3,  opponent:"Illinois St.",        opponentAdjEM:10.5, result:"W", score:"80-72",  location:"H" },
    { week:3,  opponent:"Furman",              opponentAdjEM:10.0, result:"L", score:"63-73",  location:"N" },
    { week:4,  opponent:"Indiana St.",         opponentAdjEM:8.0,  result:"W", score:"75-58",  location:"A" },
    { week:4,  opponent:"Nevada",              opponentAdjEM:18.0, result:"L", score:"68-79",  location:"H" },
    { week:5,  opponent:"Wisconsin",           opponentAdjEM:14.5, result:"L", score:"63-67",  location:"A" },
    { week:5,  opponent:"Norfolk St.",         opponentAdjEM:5.0,  result:"W", score:"95-66",  location:"H" },
    { week:6,  opponent:"Niagara",             opponentAdjEM:5.5,  result:"W", score:"81-58",  location:"A" },
    { week:7,  opponent:"Drake",               opponentAdjEM:8.5,  result:"W", score:"79-64",  location:"H" },
    { week:8,  opponent:"Northern Iowa",       opponentAdjEM:7.0,  result:"W", score:"75-67",  location:"H" },
    { week:8,  opponent:"Bradley",             opponentAdjEM:9.0,  result:"W", score:"74-62",  location:"A" },
    { week:9,  opponent:"Missouri St.",        opponentAdjEM:8.5,  result:"W", score:"70-67",  location:"H" },
    { week:9,  opponent:"Indiana St.",         opponentAdjEM:8.0,  result:"W", score:"83-49",  location:"H" },
    { week:10, opponent:"Illinois St.",        opponentAdjEM:10.5, result:"L", score:"60-66",  location:"A" },
    { week:10, opponent:"Evansville",          opponentAdjEM:6.5,  result:"W", score:"79-56",  location:"H" },
    { week:11, opponent:"Northern Iowa",       opponentAdjEM:7.0,  result:"W", score:"73-58",  location:"A" },
    { week:11, opponent:"Drake",               opponentAdjEM:8.5,  result:"W", score:"79-65",  location:"A" },
    { week:12, opponent:"Bradley",             opponentAdjEM:9.0,  result:"W", score:"66-49",  location:"H" },
    { week:12, opponent:"Missouri St.",        opponentAdjEM:8.5,  result:"W", score:"73-66",  location:"A" },
    { week:13, opponent:"S. Illinois",         opponentAdjEM:9.5,  result:"W", score:"60-49",  location:"A" },
    { week:13, opponent:"Indiana St.",         opponentAdjEM:8.0,  result:"W", score:"61-39",  location:"A" },
    { week:14, opponent:"Evansville",          opponentAdjEM:6.5,  result:"W", score:"81-65",  location:"A" },
    { week:14, opponent:"Bradley",             opponentAdjEM:9.0,  result:"W", score:"82-67",  location:"H" },
    { week:15, opponent:"Missouri St.",        opponentAdjEM:8.5,  result:"L", score:"64-65",  location:"A" },
    { week:15, opponent:"Northern Iowa",       opponentAdjEM:7.0,  result:"W", score:"54-48",  location:"H" },
    { week:16, opponent:"Drake",               opponentAdjEM:8.5,  result:"W", score:"74-65",  location:"H" },
    { week:16, opponent:"Illinois St.",        opponentAdjEM:10.5, result:"W", score:"66-58",  location:"H" },
    { week:17, opponent:"S. Illinois",         opponentAdjEM:9.5,  result:"W", score:"63-49",  location:"N" },
    { week:18, opponent:"Bradley",             opponentAdjEM:9.0,  result:"W", score:"54-46",  location:"N" },
    { week:18, opponent:"Illinois St.",        opponentAdjEM:10.5, result:"W", score:"65-49",  location:"N" },
    { week:19, opponent:"Miami (FL)",          opponentAdjEM:17.5, result:"W", score:"64-62",  location:"N" },
    { week:19, opponent:"Tennessee",           opponentAdjEM:21.5, result:"W", score:"63-62",  location:"N" },
    { week:19, opponent:"Nevada",              opponentAdjEM:18.0, result:"W", score:"69-68",  location:"N" },
    { week:19, opponent:"Kansas St.",          opponentAdjEM:16.0, result:"W", score:"78-62",  location:"N" },
    { week:20, opponent:"Michigan",            opponentAdjEM:22.0, result:"L", score:"57-69",  location:"N" },
  ],
  "Kansas": [
    { week:1,  opponent:"Tennessee St.",       opponentAdjEM:8.0,  result:"W", score:"92-54",  location:"H" },
    { week:1,  opponent:"South Dakota St.",    opponentAdjEM:12.0, result:"W", score:"96-83",  location:"H" },
    { week:2,  opponent:"Kentucky",            opponentAdjEM:23.5, result:"L", score:"61-65",  location:"N" },
    { week:2,  opponent:"Texas Southern",      opponentAdjEM:8.0,  result:"W", score:"86-61",  location:"H" },
    { week:3,  opponent:"Washington",          opponentAdjEM:13.5, result:"W", score:"74-65",  location:"N" },
    { week:3,  opponent:"Syracuse",            opponentAdjEM:14.5, result:"W", score:"76-60",  location:"N" },
    { week:4,  opponent:"Arizona St.",         opponentAdjEM:15.0, result:"L", score:"81-95",  location:"H" },
    { week:4,  opponent:"Stanford",            opponentAdjEM:13.0, result:"W", score:"75-65",  location:"H" },
    { week:5,  opponent:"Nebraska",            opponentAdjEM:15.5, result:"W", score:"73-72",  location:"H" },
    { week:5,  opponent:"Omaha",               opponentAdjEM:5.0,  result:"W", score:"107-66", location:"H" },
    { week:6,  opponent:"Texas A&M",           opponentAdjEM:18.0, result:"L", score:"74-79",  location:"N" },
    { week:7,  opponent:"Iowa St.",            opponentAdjEM:14.0, result:"W", score:"100-64", location:"A" },
    { week:8,  opponent:"Texas Tech",          opponentAdjEM:21.5, result:"W", score:"74-72",  location:"H" },
    { week:8,  opponent:"TCU",                 opponentAdjEM:17.5, result:"W", score:"88-84",  location:"A" },
    { week:9,  opponent:"Texas",               opponentAdjEM:18.5, result:"W", score:"92-86",  location:"H" },
    { week:9,  opponent:"Iowa St.",            opponentAdjEM:14.0, result:"W", score:"83-78",  location:"H" },
    { week:10, opponent:"Kansas St.",          opponentAdjEM:16.0, result:"W", score:"73-72",  location:"A" },
    { week:10, opponent:"West Virginia",       opponentAdjEM:21.0, result:"L", score:"66-71",  location:"A" },
    { week:11, opponent:"Baylor",              opponentAdjEM:15.0, result:"W", score:"70-67",  location:"H" },
    { week:11, opponent:"Oklahoma",            opponentAdjEM:17.0, result:"L", score:"81-85",  location:"A" },
    { week:12, opponent:"Oklahoma St.",        opponentAdjEM:15.5, result:"L", score:"81-84",  location:"A" },
    { week:12, opponent:"Texas Tech",          opponentAdjEM:21.5, result:"L", score:"55-65",  location:"A" },
    { week:13, opponent:"Iowa St.",            opponentAdjEM:14.0, result:"W", score:"83-77",  location:"A" },
    { week:13, opponent:"Baylor",              opponentAdjEM:15.0, result:"W", score:"71-69",  location:"A" },
    { week:14, opponent:"Kansas St.",          opponentAdjEM:16.0, result:"W", score:"70-56",  location:"H" },
    { week:14, opponent:"West Virginia",       opponentAdjEM:21.0, result:"W", score:"77-69",  location:"H" },
    { week:15, opponent:"TCU",                 opponentAdjEM:17.5, result:"W", score:"71-64",  location:"H" },
    { week:15, opponent:"Oklahoma",            opponentAdjEM:17.0, result:"W", score:"104-74", location:"H" },
    { week:16, opponent:"Texas",               opponentAdjEM:18.5, result:"W", score:"80-70",  location:"A" },
    { week:16, opponent:"Oklahoma St.",        opponentAdjEM:15.5, result:"W", score:"82-64",  location:"H" },
    { week:17, opponent:"Oklahoma St.",        opponentAdjEM:15.5, result:"W", score:"82-64",  location:"N" },
    { week:17, opponent:"Kansas St.",          opponentAdjEM:16.0, result:"W", score:"83-67",  location:"N" },
    { week:17, opponent:"West Virginia",       opponentAdjEM:21.0, result:"W", score:"81-70",  location:"N" },
    { week:19, opponent:"Penn",                opponentAdjEM:11.0, result:"W", score:"76-60",  location:"N" },
    { week:19, opponent:"Seton Hall",          opponentAdjEM:17.5, result:"W", score:"83-79",  location:"N" },
    { week:19, opponent:"Clemson",             opponentAdjEM:20.5, result:"W", score:"80-76",  location:"N" },
    { week:19, opponent:"Duke",                opponentAdjEM:26.5, result:"W", score:"85-81",  location:"N" },
    { week:20, opponent:"Villanova",           opponentAdjEM:31.1, result:"L", score:"79-95",  location:"N" },
  ],
  "Virginia": [
    { week:1,  opponent:"UNC Greensboro",      opponentAdjEM:11.5, result:"W", score:"69-57",  location:"H" },
    { week:1,  opponent:"Hampton",             opponentAdjEM:7.5,  result:"W", score:"75-50",  location:"H" },
    { week:2,  opponent:"Rhode Island",        opponentAdjEM:16.0, result:"W", score:"77-55",  location:"N" },
    { week:2,  opponent:"VCU",                 opponentAdjEM:13.0, result:"W", score:"76-67",  location:"N" },
    { week:3,  opponent:"Wisconsin",           opponentAdjEM:14.5, result:"W", score:"49-37",  location:"H" },
    { week:3,  opponent:"Lehigh",              opponentAdjEM:10.0, result:"W", score:"68-49",  location:"H" },
    { week:4,  opponent:"Davidson",            opponentAdjEM:13.5, result:"W", score:"56-44",  location:"N" },
    { week:4,  opponent:"Monmouth",            opponentAdjEM:6.5,  result:"W", score:"61-44",  location:"H" },
    { week:5,  opponent:"Hampton",             opponentAdjEM:7.5,  result:"W", score:"76-46",  location:"H" },
    { week:5,  opponent:"Boston College",      opponentAdjEM:12.5, result:"W", score:"59-58",  location:"A" },
    { week:6,  opponent:"Savannah St.",        opponentAdjEM:7.0,  result:"W", score:"81-43",  location:"H" },
    { week:7,  opponent:"Morgan St.",          opponentAdjEM:5.5,  result:"W", score:"72-52",  location:"H" },
    { week:8,  opponent:"NC State",            opponentAdjEM:15.5, result:"W", score:"68-51",  location:"H" },
    { week:8,  opponent:"Syracuse",            opponentAdjEM:14.5, result:"W", score:"68-58",  location:"A" },
    { week:9,  opponent:"Florida St.",         opponentAdjEM:19.0, result:"W", score:"59-55",  location:"A" },
    { week:9,  opponent:"Wake Forest",         opponentAdjEM:10.5, result:"W", score:"76-71",  location:"H" },
    { week:10, opponent:"Clemson",             opponentAdjEM:20.5, result:"W", score:"61-36",  location:"H" },
    { week:10, opponent:"Virginia Tech",       opponentAdjEM:16.0, result:"W", score:"78-52",  location:"H" },
    { week:11, opponent:"Duke",                opponentAdjEM:26.5, result:"W", score:"65-63",  location:"H" },
    { week:11, opponent:"Pittsburgh",          opponentAdjEM:7.0,  result:"W", score:"66-37",  location:"A" },
    { week:12, opponent:"Notre Dame",          opponentAdjEM:15.0, result:"W", score:"62-57",  location:"H" },
    { week:12, opponent:"Louisville",          opponentAdjEM:14.5, result:"W", score:"61-53",  location:"A" },
    { week:13, opponent:"NC State",            opponentAdjEM:15.5, result:"L", score:"53-63",  location:"A" },
    { week:13, opponent:"Georgia Tech",        opponentAdjEM:11.0, result:"W", score:"65-54",  location:"H" },
    { week:14, opponent:"Virginia Tech",       opponentAdjEM:16.0, result:"W", score:"65-39",  location:"A" },
    { week:14, opponent:"Duke",                opponentAdjEM:26.5, result:"W", score:"65-63",  location:"A" },
    { week:15, opponent:"Miami (FL)",          opponentAdjEM:17.5, result:"W", score:"59-50",  location:"H" },
    { week:15, opponent:"Syracuse",            opponentAdjEM:14.5, result:"W", score:"59-44",  location:"H" },
    { week:16, opponent:"Pittsburgh",          opponentAdjEM:7.0,  result:"W", score:"66-37",  location:"H" },
    { week:16, opponent:"Notre Dame",          opponentAdjEM:15.0, result:"W", score:"62-57",  location:"A" },
    { week:17, opponent:"Louisville",          opponentAdjEM:14.5, result:"W", score:"67-60",  location:"N" },
    { week:18, opponent:"Louisville",          opponentAdjEM:14.5, result:"W", score:"75-58",  location:"N" },
    { week:18, opponent:"Clemson",             opponentAdjEM:20.5, result:"W", score:"64-58",  location:"N" },
    { week:18, opponent:"North Carolina",      opponentAdjEM:24.5, result:"L", score:"71-82",  location:"N" },
    { week:19, opponent:"UMBC",                opponentAdjEM:12.0, result:"L", score:"54-74",  location:"N" },
  ],
  "UMBC": [
    { week:1,  opponent:"Stony Brook",         opponentAdjEM:7.5,  result:"L", score:"70-78",  location:"H" },
    { week:1,  opponent:"Mount St. Mary's",    opponentAdjEM:6.5,  result:"W", score:"82-66",  location:"A" },
    { week:2,  opponent:"Arizona",             opponentAdjEM:21.5, result:"L", score:"66-103", location:"A" },
    { week:2,  opponent:"Penn St.",            opponentAdjEM:16.0, result:"L", score:"74-81",  location:"A" },
    { week:3,  opponent:"Bryant",              opponentAdjEM:5.0,  result:"W", score:"96-66",  location:"H" },
    { week:3,  opponent:"Howard",              opponentAdjEM:5.0,  result:"W", score:"93-79",  location:"H" },
    { week:4,  opponent:"Albany",              opponentAdjEM:7.5,  result:"W", score:"87-71",  location:"A" },
    { week:4,  opponent:"New Hampshire",       opponentAdjEM:6.0,  result:"W", score:"73-58",  location:"A" },
    { week:5,  opponent:"Hartford",            opponentAdjEM:8.0,  result:"W", score:"83-64",  location:"H" },
    { week:5,  opponent:"Vermont",             opponentAdjEM:11.5, result:"L", score:"64-78",  location:"H" },
    { week:6,  opponent:"Loyola Maryland",     opponentAdjEM:7.0,  result:"W", score:"86-78",  location:"A" },
    { week:7,  opponent:"Stony Brook",         opponentAdjEM:7.5,  result:"L", score:"77-83",  location:"A" },
    { week:8,  opponent:"Maine",               opponentAdjEM:5.0,  result:"W", score:"91-76",  location:"H" },
    { week:8,  opponent:"UMass-Lowell",        opponentAdjEM:6.5,  result:"W", score:"77-72",  location:"H" },
    { week:9,  opponent:"Binghamton",          opponentAdjEM:5.5,  result:"W", score:"82-68",  location:"A" },
    { week:9,  opponent:"New Hampshire",       opponentAdjEM:6.0,  result:"W", score:"86-71",  location:"H" },
    { week:10, opponent:"Vermont",             opponentAdjEM:11.5, result:"L", score:"69-86",  location:"A" },
    { week:10, opponent:"Albany",              opponentAdjEM:7.5,  result:"W", score:"83-78",  location:"H" },
    { week:11, opponent:"Maine",               opponentAdjEM:5.0,  result:"W", score:"95-65",  location:"A" },
    { week:11, opponent:"Hartford",            opponentAdjEM:8.0,  result:"W", score:"85-72",  location:"A" },
    { week:12, opponent:"UMass-Lowell",        opponentAdjEM:6.5,  result:"W", score:"73-65",  location:"A" },
    { week:12, opponent:"Stony Brook",         opponentAdjEM:7.5,  result:"W", score:"79-77",  location:"H" },
    { week:13, opponent:"Binghamton",          opponentAdjEM:5.5,  result:"W", score:"82-72",  location:"H" },
    { week:13, opponent:"New Hampshire",       opponentAdjEM:6.0,  result:"W", score:"77-66",  location:"A" },
    { week:14, opponent:"Hartford",            opponentAdjEM:8.0,  result:"W", score:"71-67",  location:"H" },
    { week:14, opponent:"Maine",               opponentAdjEM:5.0,  result:"W", score:"103-79", location:"H" },
    { week:15, opponent:"Albany",              opponentAdjEM:7.5,  result:"L", score:"68-80",  location:"A" },
    { week:15, opponent:"UMass-Lowell",        opponentAdjEM:6.5,  result:"W", score:"94-83",  location:"H" },
    { week:16, opponent:"Vermont",             opponentAdjEM:11.5, result:"L", score:"61-80",  location:"H" },
    { week:16, opponent:"Stony Brook",         opponentAdjEM:7.5,  result:"L", score:"70-77",  location:"A" },
    { week:17, opponent:"Binghamton",          opponentAdjEM:5.5,  result:"W", score:"83-69",  location:"N" },
    { week:18, opponent:"Hartford",            opponentAdjEM:8.0,  result:"W", score:"77-57",  location:"N" },
    { week:18, opponent:"Vermont",             opponentAdjEM:11.5, result:"W", score:"65-62",  location:"N" },
    { week:19, opponent:"Virginia",            opponentAdjEM:27.0, result:"W", score:"74-54",  location:"N" },
    { week:19, opponent:"Kansas St.",          opponentAdjEM:16.0, result:"L", score:"43-50",  location:"N" },
  ],
  "Duke": [
    { week:1,  opponent:"Elon",                opponentAdjEM:6.0,  result:"W", score:"97-68",  location:"H" },
    { week:1,  opponent:"Utah Valley",         opponentAdjEM:6.5,  result:"W", score:"99-69",  location:"H" },
    { week:2,  opponent:"Michigan St.",        opponentAdjEM:25.7, result:"W", score:"88-81",  location:"N" },
    { week:2,  opponent:"Southern",            opponentAdjEM:5.0,  result:"W", score:"78-61",  location:"H" },
    { week:3,  opponent:"Furman",              opponentAdjEM:10.0, result:"W", score:"77-64",  location:"H" },
    { week:3,  opponent:"Indiana",             opponentAdjEM:13.5, result:"W", score:"91-81",  location:"H" },
    { week:4,  opponent:"Portland St.",        opponentAdjEM:5.0,  result:"W", score:"100-55", location:"H" },
    { week:4,  opponent:"Florida",             opponentAdjEM:19.5, result:"W", score:"87-84",  location:"H" },
    { week:5,  opponent:"St. Francis NY",      opponentAdjEM:3.5,  result:"W", score:"95-68",  location:"H" },
    { week:5,  opponent:"Boston College",      opponentAdjEM:12.5, result:"W", score:"90-55",  location:"A" },
    { week:6,  opponent:"Evansville",          opponentAdjEM:6.5,  result:"W", score:"104-40", location:"H" },
    { week:7,  opponent:"NC State",            opponentAdjEM:15.5, result:"W", score:"110-57", location:"H" },
    { week:8,  opponent:"Florida St.",         opponentAdjEM:19.0, result:"L", score:"72-80",  location:"A" },
    { week:8,  opponent:"Wake Forest",         opponentAdjEM:10.5, result:"W", score:"89-71",  location:"A" },
    { week:9,  opponent:"Pittsburgh",          opponentAdjEM:7.0,  result:"W", score:"81-54",  location:"H" },
    { week:9,  opponent:"Miami (FL)",          opponentAdjEM:17.5, result:"L", score:"81-83",  location:"A" },
    { week:10, opponent:"Wake Forest",         opponentAdjEM:10.5, result:"W", score:"84-70",  location:"H" },
    { week:10, opponent:"NC State",            opponentAdjEM:15.5, result:"L", score:"82-96",  location:"A" },
    { week:11, opponent:"Virginia",            opponentAdjEM:27.0, result:"L", score:"63-65",  location:"A" },
    { week:11, opponent:"Notre Dame",          opponentAdjEM:15.0, result:"W", score:"88-66",  location:"H" },
    { week:12, opponent:"Georgia Tech",        opponentAdjEM:11.0, result:"W", score:"110-57", location:"H" },
    { week:12, opponent:"St. John's",          opponentAdjEM:13.0, result:"L", score:"77-81",  location:"H" },
    { week:13, opponent:"North Carolina",      opponentAdjEM:24.5, result:"L", score:"78-82",  location:"H" },
    { week:13, opponent:"Georgia Tech",        opponentAdjEM:11.0, result:"W", score:"86-67",  location:"A" },
    { week:14, opponent:"Louisville",          opponentAdjEM:14.5, result:"W", score:"82-56",  location:"A" },
    { week:14, opponent:"Notre Dame",          opponentAdjEM:15.0, result:"W", score:"88-70",  location:"A" },
    { week:15, opponent:"Virginia",            opponentAdjEM:27.0, result:"L", score:"63-65",  location:"H" },
    { week:15, opponent:"Syracuse",            opponentAdjEM:14.5, result:"W", score:"60-44",  location:"H" },
    { week:16, opponent:"Syracuse",            opponentAdjEM:14.5, result:"W", score:"60-44",  location:"A" },
    { week:16, opponent:"North Carolina",      opponentAdjEM:24.5, result:"W", score:"74-64",  location:"A" },
    { week:17, opponent:"Notre Dame",          opponentAdjEM:15.0, result:"W", score:"88-70",  location:"N" },
    { week:17, opponent:"North Carolina",      opponentAdjEM:24.5, result:"L", score:"83-93",  location:"N" },
    { week:19, opponent:"Iona",                opponentAdjEM:11.5, result:"W", score:"89-67",  location:"N" },
    { week:19, opponent:"Rhode Island",        opponentAdjEM:16.0, result:"W", score:"87-62",  location:"N" },
    { week:19, opponent:"Syracuse",            opponentAdjEM:14.5, result:"W", score:"69-65",  location:"N" },
    { week:19, opponent:"Kansas",              opponentAdjEM:22.6, result:"L", score:"81-85",  location:"N" },
  ],
  "Xavier": [
    { week:1,  opponent:"Morehead St.",        opponentAdjEM:7.0,  result:"W", score:"79-58",  location:"H" },
    { week:1,  opponent:"E. Tennessee St.",    opponentAdjEM:10.5, result:"W", score:"80-62",  location:"H" },
    { week:2,  opponent:"Wisconsin",           opponentAdjEM:14.5, result:"L", score:"60-65",  location:"N" },
    { week:2,  opponent:"Baylor",              opponentAdjEM:15.0, result:"W", score:"76-63",  location:"N" },
    { week:3,  opponent:"Arizona St.",         opponentAdjEM:15.0, result:"L", score:"86-102", location:"N" },
    { week:3,  opponent:"Cincinnati",          opponentAdjEM:24.0, result:"L", score:"68-75",  location:"A" },
    { week:4,  opponent:"Hampton",             opponentAdjEM:7.5,  result:"W", score:"108-71", location:"H" },
    { week:4,  opponent:"Tennessee St.",       opponentAdjEM:8.0,  result:"W", score:"86-49",  location:"H" },
    { week:5,  opponent:"Marshall",            opponentAdjEM:13.0, result:"W", score:"81-78",  location:"H" },
    { week:5,  opponent:"Wake Forest",         opponentAdjEM:10.5, result:"W", score:"94-78",  location:"H" },
    { week:6,  opponent:"East Carolina",       opponentAdjEM:9.0,  result:"W", score:"89-72",  location:"H" },
    { week:7,  opponent:"DePaul",              opponentAdjEM:9.0,  result:"W", score:"93-69",  location:"A" },
    { week:8,  opponent:"Villanova",           opponentAdjEM:31.1, result:"W", score:"89-82",  location:"H" },
    { week:8,  opponent:"Marquette",           opponentAdjEM:14.5, result:"W", score:"89-70",  location:"A" },
    { week:9,  opponent:"Georgetown",          opponentAdjEM:11.5, result:"W", score:"89-77",  location:"H" },
    { week:9,  opponent:"Butler",              opponentAdjEM:17.0, result:"L", score:"96-98",  location:"A" },
    { week:10, opponent:"Creighton",           opponentAdjEM:17.0, result:"W", score:"73-66",  location:"H" },
    { week:10, opponent:"Seton Hall",          opponentAdjEM:17.5, result:"W", score:"102-90", location:"H" },
    { week:11, opponent:"DePaul",              opponentAdjEM:9.0,  result:"W", score:"82-65",  location:"H" },
    { week:11, opponent:"Providence",          opponentAdjEM:16.5, result:"W", score:"79-78",  location:"H" },
    { week:12, opponent:"St. John's",          opponentAdjEM:13.0, result:"W", score:"88-82",  location:"A" },
    { week:12, opponent:"Marquette",           opponentAdjEM:14.5, result:"W", score:"86-69",  location:"H" },
    { week:13, opponent:"Butler",              opponentAdjEM:17.0, result:"W", score:"84-75",  location:"H" },
    { week:13, opponent:"Seton Hall",          opponentAdjEM:17.5, result:"W", score:"81-65",  location:"A" },
    { week:14, opponent:"Villanova",           opponentAdjEM:31.1, result:"L", score:"79-95",  location:"A" },
    { week:14, opponent:"St. John's",          opponentAdjEM:13.0, result:"W", score:"94-72",  location:"H" },
    { week:15, opponent:"Creighton",           opponentAdjEM:17.0, result:"L", score:"79-81",  location:"A" },
    { week:15, opponent:"Providence",          opponentAdjEM:16.5, result:"W", score:"73-71",  location:"A" },
    { week:16, opponent:"Georgetown",          opponentAdjEM:11.5, result:"W", score:"83-71",  location:"A" },
    { week:17, opponent:"St. John's",          opponentAdjEM:13.0, result:"W", score:"75-72",  location:"N" },
    { week:17, opponent:"Providence",          opponentAdjEM:16.5, result:"L", score:"71-75",  location:"N" },
    { week:19, opponent:"Texas Southern",      opponentAdjEM:8.0,  result:"W", score:"102-83", location:"N" },
    { week:19, opponent:"Florida St.",         opponentAdjEM:19.0, result:"L", score:"66-75",  location:"N" },
  ],
};

// Final SCHEDULES: generated entries for every D-I team, with hand-curated
// overrides taking precedence for the marquee teams above.
const SCHEDULES = { ...GENERATED_SCHEDULES, ...HAND_CURATED };

// ── Dividend events ────────────────────────────────────────────────────────
const DIVIDEND_EVENTS = [
  // Villanova — National Champions (2nd in 3 years)
  { team:"Villanova", week:1,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:1,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:2,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:2,  event:"Wins multi-team tournament",    value:10 },
  { team:"Villanova", week:3,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:4,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:4,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:5,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:5,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:6,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:7,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:8,  event:"Wins a game",                   value:1  },
  { team:"Villanova", week:9,  event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:10, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:10, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:12, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:12, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:13, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:14, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:15, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:17, event:"Wins outright league title",    value:30 },
  { team:"Villanova", week:17, event:"Wins Big East tournament",      value:15 },
  { team:"Villanova", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Villanova", week:19, event:"Wins a game",                   value:1  },
  { team:"Villanova", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Villanova", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Villanova", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Villanova", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"Villanova", week:20, event:"Reaches Final Four",             value:80 },
  { team:"Villanova", week:20, event:"Wins NCAA Championship",         value:150},

  // Michigan — Runner-up
  { team:"Michigan", week:1,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:1,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:2,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:2,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Michigan", week:4,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:5,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:5,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:6,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:8,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:8,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:9,  event:"Wins a game",                   value:1  },
  { team:"Michigan", week:10, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:10, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:11, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:11, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:12, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:13, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:13, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:14, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"Michigan", week:15, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:16, event:"Wins a top-25 team",            value:5  },
  { team:"Michigan", week:17, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:17, event:"Wins a top-25 team",            value:5  },
  { team:"Michigan", week:17, event:"Wins a top-25 team",            value:5  },
  { team:"Michigan", week:17, event:"Wins Big Ten tournament",       value:15 },
  { team:"Michigan", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Michigan", week:19, event:"Wins a game",                   value:1  },
  { team:"Michigan", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Michigan", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Michigan", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Michigan", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"Michigan", week:20, event:"Reaches Final Four",             value:80 },
  { team:"Michigan", week:20, event:"NCAA Championship runner-up",    value:100},

  // Loyola Chicago — Cinderella Final Four (11-seed)
  { team:"Loyola Chicago", week:1,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:1,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"Loyola Chicago", week:2,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:3,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:4,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:5,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:6,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:7,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:8,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:8,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:9,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:9,  event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:10, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:11, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:11, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:12, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:12, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:13, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:13, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:14, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:14, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:15, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:16, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:16, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:17, event:"Wins outright league title",    value:30 },
  { team:"Loyola Chicago", week:18, event:"Wins MVC tournament",            value:15 },
  { team:"Loyola Chicago", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Loyola Chicago", week:19, event:"Wins a game",                   value:1  },
  { team:"Loyola Chicago", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Loyola Chicago", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Loyola Chicago", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Loyola Chicago", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"Loyola Chicago", week:20, event:"Reaches Final Four",             value:80 },

  // Kansas — Final Four
  { team:"Kansas", week:1,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:1,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:2,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:3,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:3,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:4,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:5,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:5,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:7,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:8,  event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:8,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:9,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:9,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:10, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:11, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:13, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:13, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:14, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:15, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:15, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:16, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:16, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:17, event:"Wins contested league title",    value:20 },
  { team:"Kansas", week:17, event:"Wins Big 12 tournament",         value:15 },
  { team:"Kansas", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Kansas", week:19, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Kansas", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"Kansas", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"Kansas", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:20, event:"Reaches Final Four",             value:80 },

  // Virginia — #1 overall, lost to UMBC (R64)
  { team:"Virginia", week:2,  event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:3,  event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:8,  event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:10, event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"Virginia", week:17, event:"Wins outright league title",    value:30 },
  { team:"Virginia", week:18, event:"Wins ACC tournament",          value:15 },
  { team:"Virginia", week:19, event:"Makes the NCAA tournament",     value:10 },

  // UMBC — historic 16-over-1 upset
  { team:"UMBC", week:18, event:"Wins America East tournament",     value:15 },
  { team:"UMBC", week:19, event:"Makes the NCAA tournament",        value:10 },
  { team:"UMBC", week:19, event:"Wins a top-25 team",                value:5  },
  { team:"UMBC", week:19, event:"Wins a game",                       value:1  },

  // Duke — Elite Eight
  { team:"Duke", week:2,  event:"Wins a top-25 team",                value:5  },
  { team:"Duke", week:4,  event:"Wins a top-25 team",                value:5  },
  { team:"Duke", week:13, event:"Wins a top-25 team",                value:5  },
  { team:"Duke", week:16, event:"Wins a top-25 team",                value:5  },
  { team:"Duke", week:19, event:"Makes the NCAA tournament",        value:10 },
  { team:"Duke", week:19, event:"Wins a game",                       value:1  },
  { team:"Duke", week:19, event:"Reaches Round of 32",                value:10 },
  { team:"Duke", week:19, event:"Reaches Sweet Sixteen",              value:20 },
  { team:"Duke", week:19, event:"Wins a top-25 team",                value:5  },
  { team:"Duke", week:19, event:"Reaches Elite Eight",                value:40 },

  // Xavier — #1 seed, R32 exit
  { team:"Xavier", week:2,  event:"Wins a top-25 team",              value:5  },
  { team:"Xavier", week:8,  event:"Wins a top-25 team",              value:5  },
  { team:"Xavier", week:10, event:"Wins a top-25 team",              value:5  },
  { team:"Xavier", week:10, event:"Wins a top-25 team",              value:5  },
  { team:"Xavier", week:13, event:"Wins a top-25 team",              value:5  },
  { team:"Xavier", week:14, event:"Wins a top-25 team",              value:5  },
  { team:"Xavier", week:17, event:"Wins outright league title",      value:30 },
  { team:"Xavier", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Xavier", week:19, event:"Wins a game",                     value:1  },

  // Other key tournament teams (abbreviated)
  // Michigan St.
  { team:"Michigan St.", week:17, event:"Wins outright league title", value:30 },
  { team:"Michigan St.", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Michigan St.", week:19, event:"Wins a game",                value:1  },
  { team:"Michigan St.", week:19, event:"Reaches Round of 32",         value:10 },

  // Purdue — Sweet 16
  { team:"Purdue", week:17, event:"Wins contested league title",     value:20 },
  { team:"Purdue", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Purdue", week:19, event:"Wins a game",                     value:1  },
  { team:"Purdue", week:19, event:"Reaches Round of 32",              value:10 },
  { team:"Purdue", week:19, event:"Reaches Sweet Sixteen",            value:20 },

  // North Carolina — R32
  { team:"North Carolina", week:18, event:"Wins ACC tournament",     value:15 },
  { team:"North Carolina", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"North Carolina", week:19, event:"Wins a game",              value:1  },
  { team:"North Carolina", week:19, event:"Reaches Round of 32",       value:10 },

  // Cincinnati — R32
  { team:"Cincinnati", week:17, event:"Wins outright league title",   value:30 },
  { team:"Cincinnati", week:18, event:"Wins American tournament",    value:15 },
  { team:"Cincinnati", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Cincinnati", week:19, event:"Wins a game",                  value:1  },
  { team:"Cincinnati", week:19, event:"Reaches Round of 32",           value:10 },

  // Wichita St. — R64
  { team:"Wichita St.", week:19, event:"Makes the NCAA tournament",  value:10 },

  // Kentucky — Sweet 16
  { team:"Kentucky", week:18, event:"Wins SEC tournament",            value:15 },
  { team:"Kentucky", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Kentucky", week:19, event:"Wins a game",                    value:1  },
  { team:"Kentucky", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Kentucky", week:19, event:"Reaches Sweet Sixteen",           value:20 },

  // Gonzaga — Sweet 16
  { team:"Gonzaga", week:17, event:"Wins outright league title",      value:30 },
  { team:"Gonzaga", week:18, event:"Wins WCC tournament",             value:15 },
  { team:"Gonzaga", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Gonzaga", week:19, event:"Wins a game",                     value:1  },
  { team:"Gonzaga", week:19, event:"Reaches Round of 32",              value:10 },
  { team:"Gonzaga", week:19, event:"Reaches Sweet Sixteen",            value:20 },

  // Texas Tech — Elite Eight
  { team:"Texas Tech", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Texas Tech", week:19, event:"Wins a game",                  value:1  },
  { team:"Texas Tech", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Texas Tech", week:19, event:"Reaches Sweet Sixteen",         value:20 },
  { team:"Texas Tech", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Texas Tech", week:19, event:"Reaches Elite Eight",           value:40 },

  // West Virginia — Sweet 16
  { team:"West Virginia", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"West Virginia", week:19, event:"Wins a game",               value:1  },
  { team:"West Virginia", week:19, event:"Reaches Round of 32",        value:10 },
  { team:"West Virginia", week:19, event:"Reaches Sweet Sixteen",      value:20 },

  // Florida St. — Elite Eight
  { team:"Florida St.", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Florida St.", week:19, event:"Wins a game",                value:1  },
  { team:"Florida St.", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Florida St.", week:19, event:"Wins a top-25 team",         value:5  },
  { team:"Florida St.", week:19, event:"Reaches Sweet Sixteen",       value:20 },
  { team:"Florida St.", week:19, event:"Reaches Elite Eight",         value:40 },

  // Texas A&M — Sweet 16
  { team:"Texas A&M", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Texas A&M", week:19, event:"Wins a game",                  value:1  },
  { team:"Texas A&M", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Texas A&M", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Texas A&M", week:19, event:"Reaches Sweet Sixteen",         value:20 },

  // Nevada — Sweet 16 (came back from 22 down vs Cincinnati)
  { team:"Nevada", week:17, event:"Wins outright league title",       value:30 },
  { team:"Nevada", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Nevada", week:19, event:"Wins a game",                     value:1  },
  { team:"Nevada", week:19, event:"Reaches Round of 32",              value:10 },
  { team:"Nevada", week:19, event:"Reaches Sweet Sixteen",            value:20 },

  // Kansas St. — Elite Eight
  { team:"Kansas St.", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"Kansas St.", week:19, event:"Wins a game",                value:1  },
  { team:"Kansas St.", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Kansas St.", week:19, event:"Reaches Sweet Sixteen",       value:20 },
  { team:"Kansas St.", week:19, event:"Reaches Elite Eight",         value:40 },

  // Auburn — R32
  { team:"Auburn", week:17, event:"Wins outright league title",       value:30 },
  { team:"Auburn", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Auburn", week:19, event:"Wins a game",                     value:1  },
  { team:"Auburn", week:19, event:"Reaches Round of 32",              value:10 },

  // Tennessee — R32
  { team:"Tennessee", week:17, event:"Wins contested league title",   value:20 },
  { team:"Tennessee", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Tennessee", week:19, event:"Wins a game",                  value:1  },
  { team:"Tennessee", week:19, event:"Reaches Round of 32",           value:10 },

  // Houston — R32
  { team:"Houston", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Houston", week:19, event:"Wins a game",                    value:1  },
  { team:"Houston", week:19, event:"Reaches Round of 32",             value:10 },

  // Clemson — Sweet 16
  { team:"Clemson", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Clemson", week:19, event:"Wins a game",                    value:1  },
  { team:"Clemson", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Clemson", week:19, event:"Reaches Sweet Sixteen",           value:20 },

  // Seton Hall — R64
  { team:"Seton Hall", week:19, event:"Makes the NCAA tournament", value:10 },

  // Creighton — R64
  { team:"Creighton", week:19, event:"Makes the NCAA tournament",  value:10 },

  // Providence — R64 (lost to A&M in OT)
  { team:"Providence", week:19, event:"Makes the NCAA tournament", value:10 },

  // Butler — R64
  { team:"Butler", week:19, event:"Makes the NCAA tournament",     value:10 },

  // Florida — R32
  { team:"Florida", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Florida", week:19, event:"Wins a game",                   value:1  },
  { team:"Florida", week:19, event:"Reaches Round of 32",            value:10 },

  // Texas — R64
  { team:"Texas", week:19, event:"Makes the NCAA tournament",      value:10 },

  // Arizona — R64 (upset by Buffalo)
  { team:"Arizona", week:17, event:"Wins outright league title",    value:30 },
  { team:"Arizona", week:18, event:"Wins Pac-12 tournament",        value:15 },
  { team:"Arizona", week:19, event:"Makes the NCAA tournament",   value:10 },

  // Buffalo — R32 (def. Arizona)
  { team:"Buffalo", week:17, event:"Wins outright league title",    value:30 },
  { team:"Buffalo", week:18, event:"Wins MAC tournament",           value:15 },
  { team:"Buffalo", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Buffalo", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Buffalo", week:19, event:"Wins a game",                   value:1  },
  { team:"Buffalo", week:19, event:"Reaches Round of 32",            value:10 },

  // Saint Mary's — NIT
  { team:"Saint Mary's", week:19, event:"Makes other postseason",   value:5  },

  // Rhode Island — R32
  { team:"Rhode Island", week:17, event:"Wins outright league title",value:30 },
  { team:"Rhode Island", week:18, event:"Wins Atlantic 10 tournament",value:15},
  { team:"Rhode Island", week:19, event:"Makes the NCAA tournament",value:10 },
  { team:"Rhode Island", week:19, event:"Wins a game",               value:1  },
  { team:"Rhode Island", week:19, event:"Reaches Round of 32",        value:10 },

  // Davidson — R64
  { team:"Davidson", week:18, event:"Wins Atlantic 10 tournament",  value:15 },
  { team:"Davidson", week:19, event:"Makes the NCAA tournament",   value:10 },

  // St. Bonaventure — First Four winner, R64
  { team:"St. Bonaventure", week:19, event:"Makes the NCAA tournament", value:10 },
  { team:"St. Bonaventure", week:19, event:"Wins a game",            value:1  },

  // San Diego St. — R64
  { team:"San Diego St.", week:18, event:"Wins MWC tournament",     value:15 },
  { team:"San Diego St.", week:19, event:"Makes the NCAA tournament",value:10},

  // New Mexico St. — R64
  { team:"New Mexico St.", week:18, event:"Wins WAC tournament",    value:15 },
  { team:"New Mexico St.", week:19, event:"Makes the NCAA tournament",value:10},

  // South Dakota St. — R64
  { team:"South Dakota St.", week:18, event:"Wins Summit tournament",value:15},
  { team:"South Dakota St.", week:19, event:"Makes the NCAA tournament",value:10},

  // Marshall — R32
  { team:"Marshall", week:18, event:"Wins C-USA tournament",        value:15 },
  { team:"Marshall", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Marshall", week:19, event:"Wins a game",                  value:1  },
  { team:"Marshall", week:19, event:"Reaches Round of 32",           value:10 },

  // Murray St. — R64
  { team:"Murray St.", week:17, event:"Wins outright league title", value:30 },
  { team:"Murray St.", week:18, event:"Wins OVC tournament",        value:15 },
  { team:"Murray St.", week:19, event:"Makes the NCAA tournament",value:10  },

  // Stephen F. Austin — R64
  { team:"Stephen F. Austin", week:18, event:"Wins Southland tournament",value:15},
  { team:"Stephen F. Austin", week:19, event:"Makes the NCAA tournament",value:10},

  // Bucknell — R64
  { team:"Bucknell", week:18, event:"Wins Patriot tournament",      value:15 },
  { team:"Bucknell", week:19, event:"Makes the NCAA tournament",  value:10 },

  // Cal St. Fullerton — R64
  { team:"Cal St. Fullerton", week:18, event:"Wins Big West tournament", value:15},
  { team:"Cal St. Fullerton", week:19, event:"Makes the NCAA tournament",value:10},

  // Charleston — R64
  { team:"Charleston", week:18, event:"Wins CAA tournament",        value:15 },
  { team:"Charleston", week:19, event:"Makes the NCAA tournament", value:10 },

  // Iona — R64
  { team:"Iona", week:18, event:"Wins MAAC tournament",             value:15 },
  { team:"Iona", week:19, event:"Makes the NCAA tournament",      value:10 },

  // Penn — R64
  { team:"Penn", week:17, event:"Wins outright league title",       value:30 },
  { team:"Penn", week:18, event:"Wins Ivy tournament",              value:15 },
  { team:"Penn", week:19, event:"Makes the NCAA tournament",      value:10 },

  // LIU Brooklyn — First Four loss
  { team:"LIU Brooklyn", week:18, event:"Wins NEC tournament",      value:15 },
  { team:"LIU Brooklyn", week:19, event:"Makes the NCAA tournament",value:10},

  // UNC Greensboro — R64
  { team:"UNC Greensboro", week:18, event:"Wins Southern tournament",value:15},
  { team:"UNC Greensboro", week:19, event:"Makes the NCAA tournament",value:10},

  // NC Central — First Four loss
  { team:"NC Central", week:18, event:"Wins MEAC tournament",       value:15 },
  { team:"NC Central", week:19, event:"Makes the NCAA tournament",value:10  },

  // Lipscomb — R64
  { team:"Lipscomb", week:18, event:"Wins ASUN tournament",         value:15 },
  { team:"Lipscomb", week:19, event:"Makes the NCAA tournament",  value:10 },

  // Texas Southern — First Four winner
  { team:"Texas Southern", week:18, event:"Wins SWAC tournament",   value:15 },
  { team:"Texas Southern", week:19, event:"Makes the NCAA tournament",value:10},
  { team:"Texas Southern", week:19, event:"Wins a game",            value:1  },

  // Radford — First Four winner
  { team:"Radford", week:18, event:"Wins Big South tournament",     value:15 },
  { team:"Radford", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Radford", week:19, event:"Wins a game",                   value:1  },

  // Wright St. — R64
  { team:"Wright St.", week:18, event:"Wins Horizon tournament",    value:15 },
  { team:"Wright St.", week:19, event:"Makes the NCAA tournament",value:10  },

  // Montana — R64
  { team:"Montana", week:18, event:"Wins Big Sky tournament",       value:15 },
  { team:"Montana", week:19, event:"Makes the NCAA tournament",   value:10 },

  // Georgia St. — R64
  { team:"Georgia St.", week:18, event:"Wins Sun Belt tournament",  value:15 },
  { team:"Georgia St.", week:19, event:"Makes the NCAA tournament",value:10 },
];

const EVENTS_BY_WEEK = {};
for (const evt of DIVIDEND_EVENTS) {
  if (!EVENTS_BY_WEEK[evt.week]) EVENTS_BY_WEEK[evt.week] = [];
  EVENTS_BY_WEEK[evt.week].push(evt);
}

export const SEASON_2018 = {
  id: "2017-18",
  label: "2017-18",
  champion: "Villanova",
  WEEKS,
  TEAM_HISTORY,
  SCHEDULES,
  DIVIDEND_EVENTS,
  EVENTS_BY_WEEK,
};
