// dividends.js
// Pre-scripted 2023-24 season events, mapped to weeks.
// Each entry: { team, week, event, value }
// Dividend payout = value × shares owned by player.
//
// DIVIDEND TABLE:
//   Win a game                          +1
//   Win a multi-team tournament         +10
//   Win vs top-25 AP Poll team          +5
//   Win outright league title           +30
//   Win contested league title          +20
//   Win league tournament title         +15
//   Make NCAA tournament                +10
//   Make other postseason               +5
//   Reach NCAA Round of 32              +10
//   Reach Sweet Sixteen                 +20
//   Reach Elite Eight                   +40
//   Reach Final Four                    +80
//   NCAA Championship runner-up         +100
//   Win NCAA Championship               +150
//   Win other postseason tournament     +30

// Weeks reference:
// W1=Nov6  W2=Nov13  W3=Nov20  W4=Nov27  W5=Dec4   W6=Dec11  W7=Dec18
// W8=Jan2  W9=Jan8   W10=Jan15 W11=Jan22 W12=Jan29 W13=Feb5  W14=Feb12
// W15=Feb19 W16=Feb26 W17=Mar4 W18=Mar9  W19=Mar16 W20=Mar23

export const DIVIDEND_EVENTS = [

  // ── Weekly wins (representative top-25 matchups, Weeks 1-17) ────────────
  // These approximate each team's win total per week segment.
  // Each entry covers ~1 week of games (typically 2 games per team).

  // UConn — went 37-3, dominant all season
  { team:"UConn", week:1,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:1,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:2,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:2,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:3,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:3,  event:"Wins a multi-team tournament",   value:10 },
  { team:"UConn", week:4,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:4,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:5,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:5,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:6,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:6,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:7,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:7,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:8,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:9,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:9,  event:"Wins a game",                    value:1  },
  { team:"UConn", week:10, event:"Wins a game",                    value:1  },
  { team:"UConn", week:10, event:"Wins a game",                    value:1  },
  { team:"UConn", week:11, event:"Wins a game",                    value:1  },
  { team:"UConn", week:11, event:"Wins a game",                    value:1  },
  { team:"UConn", week:12, event:"Wins a game",                    value:1  },
  { team:"UConn", week:12, event:"Wins a game",                    value:1  },
  { team:"UConn", week:13, event:"Wins a game",                    value:1  },
  { team:"UConn", week:13, event:"Wins a top-25 team",             value:5  },
  { team:"UConn", week:14, event:"Wins a game",                    value:1  },
  { team:"UConn", week:14, event:"Wins a game",                    value:1  },
  { team:"UConn", week:15, event:"Wins a game",                    value:1  },
  { team:"UConn", week:15, event:"Wins a top-25 team",             value:5  },
  { team:"UConn", week:16, event:"Wins a game",                    value:1  },
  { team:"UConn", week:16, event:"Wins a top-25 team",             value:5  },
  { team:"UConn", week:17, event:"Wins contested league title",    value:20 },
  { team:"UConn", week:17, event:"Wins a game",                    value:1  },
  { team:"UConn", week:18, event:"Wins Big East tournament title", value:15 },
  { team:"UConn", week:18, event:"Wins a top-25 team",             value:5  },
  { team:"UConn", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"UConn", week:19, event:"Wins a game",                    value:1  },
  { team:"UConn", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"UConn", week:19, event:"Wins a top-25 team",             value:5  },
  { team:"UConn", week:19, event:"Reaches Sweet Sixteen",          value:20 },
  { team:"UConn", week:19, event:"Reaches Elite Eight",            value:40 },
  { team:"UConn", week:20, event:"Reaches Final Four",             value:80 },
  { team:"UConn", week:20, event:"Wins NCAA Championship",         value:150},

  // Purdue — 34-3, Big Ten champions, Final Four
  { team:"Purdue", week:1,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:1,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:2,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:2,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:3,  event:"Wins a multi-team tournament",  value:10 },
  { team:"Purdue", week:3,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:4,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:4,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:5,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:5,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:6,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:6,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:7,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:7,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:8,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:9,  event:"Wins a game",                   value:1  },
  { team:"Purdue", week:9,  event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:10, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:10, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:11, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:11, event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:12, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:12, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:13, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:13, event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:14, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:14, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:15, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:15, event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:16, event:"Wins outright league title",    value:30 },
  { team:"Purdue", week:16, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:17, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:17, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:18, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Purdue", week:19, event:"Wins a game",                   value:1  },
  { team:"Purdue", week:19, event:"Reaches Round of 32",           value:10 },
  { team:"Purdue", week:19, event:"Wins a top-25 team",            value:5  },
  { team:"Purdue", week:19, event:"Reaches Sweet Sixteen",         value:20 },
  { team:"Purdue", week:19, event:"Reaches Elite Eight",           value:40 },
  { team:"Purdue", week:20, event:"Reaches Final Four",            value:80 },
  { team:"Purdue", week:20, event:"NCAA Championship runner-up",   value:100},

  // Houston — 32-5, Big 12 co-champs, Elite Eight
  { team:"Houston", week:1,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:1,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:2,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:2,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:3,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:3,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:4,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:4,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:5,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:5,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:6,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:7,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:7,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:8,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:9,  event:"Wins a game",                  value:1  },
  { team:"Houston", week:9,  event:"Wins a top-25 team",           value:5  },
  { team:"Houston", week:10, event:"Wins a game",                  value:1  },
  { team:"Houston", week:10, event:"Wins a game",                  value:1  },
  { team:"Houston", week:11, event:"Wins a game",                  value:1  },
  { team:"Houston", week:11, event:"Wins a game",                  value:1  },
  { team:"Houston", week:12, event:"Wins a game",                  value:1  },
  { team:"Houston", week:12, event:"Wins a top-25 team",           value:5  },
  { team:"Houston", week:13, event:"Wins a game",                  value:1  },
  { team:"Houston", week:13, event:"Wins a game",                  value:1  },
  { team:"Houston", week:14, event:"Wins a game",                  value:1  },
  { team:"Houston", week:14, event:"Wins a top-25 team",           value:5  },
  { team:"Houston", week:15, event:"Wins a game",                  value:1  },
  { team:"Houston", week:15, event:"Wins a game",                  value:1  },
  { team:"Houston", week:16, event:"Wins contested league title",  value:20 },
  { team:"Houston", week:16, event:"Wins a game",                  value:1  },
  { team:"Houston", week:17, event:"Wins a game",                  value:1  },
  { team:"Houston", week:18, event:"Wins a game",                  value:1  },
  { team:"Houston", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Houston", week:19, event:"Wins a game",                  value:1  },
  { team:"Houston", week:19, event:"Reaches Round of 32",          value:10 },
  { team:"Houston", week:19, event:"Reaches Sweet Sixteen",        value:20 },
  { team:"Houston", week:19, event:"Reaches Elite Eight",          value:40 },
  { team:"Houston", week:20, event:"Wins a top-25 team",           value:5  },

  // Tennessee — 27-10, SEC co-champs, Sweet Sixteen
  { team:"Tennessee", week:1,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:1,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:2,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:3,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:3,  event:"Wins a multi-team tournament",value:10 },
  { team:"Tennessee", week:4,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:4,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:5,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:5,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:6,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:7,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:8,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:9,  event:"Wins a game",                value:1  },
  { team:"Tennessee", week:9,  event:"Wins a top-25 team",         value:5  },
  { team:"Tennessee", week:10, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:10, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:11, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:12, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:12, event:"Wins a top-25 team",         value:5  },
  { team:"Tennessee", week:13, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:13, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:14, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:15, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:15, event:"Wins a top-25 team",         value:5  },
  { team:"Tennessee", week:16, event:"Wins contested league title",value:20 },
  { team:"Tennessee", week:17, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"Tennessee", week:19, event:"Wins a game",                value:1  },
  { team:"Tennessee", week:19, event:"Reaches Round of 32",        value:10 },
  { team:"Tennessee", week:19, event:"Reaches Sweet Sixteen",      value:20 },

  // Iowa St. — 29-9, Big 12 co-champs, Elite Eight
  { team:"Iowa St.", week:1,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:1,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:2,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:2,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:3,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:3,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:4,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:4,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:5,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:6,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:6,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:7,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:7,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:8,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:8,  event:"Wins a top-25 team",          value:5  },
  { team:"Iowa St.", week:9,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:9,  event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:10, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:10, event:"Wins a top-25 team",          value:5  },
  { team:"Iowa St.", week:11, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:11, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:12, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:13, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:13, event:"Wins a top-25 team",          value:5  },
  { team:"Iowa St.", week:14, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:15, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:15, event:"Wins a top-25 team",          value:5  },
  { team:"Iowa St.", week:16, event:"Wins contested league title", value:20 },
  { team:"Iowa St.", week:17, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:18, event:"Wins Big 12 tournament title",value:15 },
  { team:"Iowa St.", week:18, event:"Wins a top-25 team",          value:5  },
  { team:"Iowa St.", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Iowa St.", week:19, event:"Wins a game",                 value:1  },
  { team:"Iowa St.", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Iowa St.", week:19, event:"Reaches Sweet Sixteen",       value:20 },
  { team:"Iowa St.", week:19, event:"Reaches Elite Eight",         value:40 },

  // NC State — 27-13, ACC tournament champions (Cinderella), Final Four
  { team:"NC State", week:1,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:2,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:3,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:4,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:5,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:6,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:7,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:8,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:9,  event:"Wins a game",                 value:1  },
  { team:"NC State", week:10, event:"Wins a game",                 value:1  },
  { team:"NC State", week:11, event:"Wins a game",                 value:1  },
  { team:"NC State", week:12, event:"Wins a game",                 value:1  },
  { team:"NC State", week:13, event:"Wins a game",                 value:1  },
  { team:"NC State", week:14, event:"Wins a game",                 value:1  },
  { team:"NC State", week:15, event:"Wins a game",                 value:1  },
  { team:"NC State", week:16, event:"Wins a game",                 value:1  },
  { team:"NC State", week:17, event:"Wins a game",                 value:1  },
  { team:"NC State", week:18, event:"Wins ACC tournament title",   value:15 },
  { team:"NC State", week:18, event:"Wins a top-25 team",          value:5  },
  { team:"NC State", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"NC State", week:19, event:"Wins a game",                 value:1  },
  { team:"NC State", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"NC State", week:19, event:"Wins a top-25 team",          value:5  },
  { team:"NC State", week:19, event:"Reaches Sweet Sixteen",       value:20 },
  { team:"NC State", week:19, event:"Reaches Elite Eight",         value:40 },
  { team:"NC State", week:20, event:"Reaches Final Four",          value:80 },

  // Alabama — 21-13, SEC tournament title
  { team:"Alabama", week:1,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:2,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:3,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:4,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:5,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:6,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:7,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:8,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:9,  event:"Wins a game",                  value:1  },
  { team:"Alabama", week:10, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:10, event:"Wins a top-25 team",           value:5  },
  { team:"Alabama", week:11, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:12, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:13, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:14, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:15, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:16, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:17, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:18, event:"Wins SEC tournament title",    value:15 },
  { team:"Alabama", week:18, event:"Wins a top-25 team",           value:5  },
  { team:"Alabama", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Alabama", week:19, event:"Wins a game",                  value:1  },
  { team:"Alabama", week:19, event:"Reaches Round of 32",          value:10 },
  { team:"Alabama", week:19, event:"Reaches Sweet Sixteen",        value:20 },

  // Marquette — Big East co-champs
  { team:"Marquette", week:1,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:2,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:2,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:3,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:3,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:4,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:4,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:5,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:5,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:6,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:7,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:8,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:9,  event:"Wins a game",                value:1  },
  { team:"Marquette", week:9,  event:"Wins a top-25 team",         value:5  },
  { team:"Marquette", week:10, event:"Wins a game",                value:1  },
  { team:"Marquette", week:11, event:"Wins a game",                value:1  },
  { team:"Marquette", week:12, event:"Wins a game",                value:1  },
  { team:"Marquette", week:13, event:"Wins a game",                value:1  },
  { team:"Marquette", week:14, event:"Wins a game",                value:1  },
  { team:"Marquette", week:15, event:"Wins a game",                value:1  },
  { team:"Marquette", week:16, event:"Wins contested league title",value:20 },
  { team:"Marquette", week:16, event:"Wins a top-25 team",         value:5  },
  { team:"Marquette", week:17, event:"Wins a game",                value:1  },
  { team:"Marquette", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"Marquette", week:19, event:"Wins a game",                value:1  },
  { team:"Marquette", week:19, event:"Reaches Round of 32",        value:10 },

  // Duke — 27-9, ACC regular season co-champ
  { team:"Duke", week:1,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:2,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:2,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:3,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:3,  event:"Wins a multi-team tournament",    value:10 },
  { team:"Duke", week:4,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:4,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:5,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:6,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:7,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:8,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:9,  event:"Wins a game",                     value:1  },
  { team:"Duke", week:9,  event:"Wins a top-25 team",              value:5  },
  { team:"Duke", week:10, event:"Wins a game",                     value:1  },
  { team:"Duke", week:10, event:"Wins a game",                     value:1  },
  { team:"Duke", week:11, event:"Wins a game",                     value:1  },
  { team:"Duke", week:11, event:"Wins a top-25 team",              value:5  },
  { team:"Duke", week:12, event:"Wins a game",                     value:1  },
  { team:"Duke", week:13, event:"Wins a game",                     value:1  },
  { team:"Duke", week:14, event:"Wins a game",                     value:1  },
  { team:"Duke", week:14, event:"Wins a top-25 team",              value:5  },
  { team:"Duke", week:15, event:"Wins a game",                     value:1  },
  { team:"Duke", week:16, event:"Wins contested league title",     value:20 },
  { team:"Duke", week:17, event:"Wins a game",                     value:1  },
  { team:"Duke", week:19, event:"Makes the NCAA tournament",       value:10 },
  { team:"Duke", week:19, event:"Wins a game",                     value:1  },
  { team:"Duke", week:19, event:"Reaches Round of 32",             value:10 },
  { team:"Duke", week:19, event:"Reaches Sweet Sixteen",           value:20 },

  // Kansas — Big 12 co-champs
  { team:"Kansas", week:1,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:2,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:3,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:3,  event:"Wins a multi-team tournament",  value:10 },
  { team:"Kansas", week:4,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:5,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:6,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:7,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:8,  event:"Wins a game",                   value:1  },
  { team:"Kansas", week:9,  event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:10, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:11, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:12, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:13, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:14, event:"Wins a top-25 team",            value:5  },
  { team:"Kansas", week:15, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:16, event:"Wins contested league title",   value:20 },
  { team:"Kansas", week:17, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Kansas", week:19, event:"Wins a game",                   value:1  },
  { team:"Kansas", week:19, event:"Reaches Round of 32",           value:10 },

  // Illinois — Big Ten co-champs, Sweet Sixteen
  { team:"Illinois", week:1,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:2,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:3,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:4,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:5,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:6,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:7,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:8,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:9,  event:"Wins a game",                 value:1  },
  { team:"Illinois", week:10, event:"Wins a top-25 team",          value:5  },
  { team:"Illinois", week:11, event:"Wins a game",                 value:1  },
  { team:"Illinois", week:12, event:"Wins a game",                 value:1  },
  { team:"Illinois", week:13, event:"Wins a game",                 value:1  },
  { team:"Illinois", week:14, event:"Wins a top-25 team",          value:5  },
  { team:"Illinois", week:15, event:"Wins a game",                 value:1  },
  { team:"Illinois", week:16, event:"Wins contested league title", value:20 },
  { team:"Illinois", week:17, event:"Wins a game",                 value:1  },
  { team:"Illinois", week:18, event:"Wins Big Ten tournament title",value:15},
  { team:"Illinois", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Illinois", week:19, event:"Wins a game",                 value:1  },
  { team:"Illinois", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Illinois", week:19, event:"Reaches Sweet Sixteen",       value:20 },

  // Arizona — Pac-12 champs, Sweet Sixteen
  { team:"Arizona", week:1,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:2,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:3,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:4,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:5,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:6,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:7,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:8,  event:"Wins a game",                  value:1  },
  { team:"Arizona", week:9,  event:"Wins a top-25 team",           value:5  },
  { team:"Arizona", week:10, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:11, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:12, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:13, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:14, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:15, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:16, event:"Wins outright league title",   value:30 },
  { team:"Arizona", week:17, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Arizona", week:19, event:"Wins a game",                  value:1  },
  { team:"Arizona", week:19, event:"Reaches Round of 32",          value:10 },
  { team:"Arizona", week:19, event:"Reaches Sweet Sixteen",        value:20 },

  // McNeese — 30-5, Southland champions, NCAA tournament
  { team:"McNeese", week:1,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:2,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:2,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:3,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:4,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:4,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:5,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:5,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:6,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:6,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:7,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:8,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:9,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:9,  event:"Wins a game",                  value:1  },
  { team:"McNeese", week:10, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:10, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:11, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:11, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:12, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:13, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:13, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:14, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:15, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:16, event:"Wins outright league title",   value:30 },
  { team:"McNeese", week:17, event:"Wins a game",                  value:1  },
  { team:"McNeese", week:18, event:"Wins Southland tournament",    value:15 },
  { team:"McNeese", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"McNeese", week:19, event:"Wins a game",                  value:1  },

  // South Dakota St. — Summit League champs, NCAA tournament
  { team:"South Dakota St.", week:16, event:"Wins outright league title", value:30 },
  { team:"South Dakota St.", week:17, event:"Wins a game",                value:1  },
  { team:"South Dakota St.", week:18, event:"Wins Summit tournament",     value:15 },
  { team:"South Dakota St.", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"South Dakota St.", week:19, event:"Wins a game",                value:1  },
  { team:"South Dakota St.", week:19, event:"Reaches Round of 32",        value:10 },

  // Samford — Southern Conference champs, NCAA tournament
  { team:"Samford", week:16, event:"Wins outright league title",   value:30 },
  { team:"Samford", week:18, event:"Wins Southern tournament",     value:15 },
  { team:"Samford", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Samford", week:19, event:"Wins a game",                  value:1  },

  // Duquesne — A-10 tournament champs, NCAA tournament (first time since 1977)
  { team:"Duquesne", week:18, event:"Wins A-10 tournament title",  value:15 },
  { team:"Duquesne", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Duquesne", week:19, event:"Wins a game",                 value:1  },

  // Colgate — Patriot League champs
  { team:"Colgate", week:16, event:"Wins outright league title",   value:30 },
  { team:"Colgate", week:18, event:"Wins Patriot tournament",      value:15 },
  { team:"Colgate", week:19, event:"Makes the NCAA tournament",    value:10 },

  // Vermont — America East champs
  { team:"Vermont", week:16, event:"Wins outright league title",   value:30 },
  { team:"Vermont", week:18, event:"Wins America East tournament", value:15 },
  { team:"Vermont", week:19, event:"Makes the NCAA tournament",    value:10 },

  // Drake — Missouri Valley runner-up (made NIT)
  { team:"Drake", week:16, event:"Wins contested league title",    value:20 },
  { team:"Drake", week:19, event:"Makes it to other postseason",   value:5  },
  { team:"Drake", week:20, event:"Wins other postseason tournament",value:30 },

  // Gonzaga — WCC regular season champs, NCAA tournament
  { team:"Gonzaga", week:1,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:2,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:3,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:4,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:5,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:6,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:7,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:8,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:9,  event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:10, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:11, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:12, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:13, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:14, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:15, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:16, event:"Wins outright league title",   value:30 },
  { team:"Gonzaga", week:18, event:"Wins WCC tournament title",    value:15 },
  { team:"Gonzaga", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Gonzaga", week:19, event:"Wins a game",                  value:1  },
  { team:"Gonzaga", week:19, event:"Reaches Round of 32",          value:10 },

  // Missouri — SEC surprise, Sweet Sixteen
  { team:"Missouri", week:19, event:"Makes the NCAA tournament",   value:10 },
  { team:"Missouri", week:19, event:"Wins a game",                 value:1  },
  { team:"Missouri", week:19, event:"Reaches Round of 32",         value:10 },
  { team:"Missouri", week:19, event:"Reaches Sweet Sixteen",       value:20 },

  // Dayton — A-10 regular season champs, NCAA tournament
  { team:"Dayton", week:16, event:"Wins outright league title",    value:30 },
  { team:"Dayton", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"Dayton", week:19, event:"Wins a game",                   value:1  },
  { team:"Dayton", week:19, event:"Reaches Round of 32",           value:10 },

  // Yale — Ivy League tournament winner, NCAA tournament
  { team:"Yale", week:18, event:"Wins Ivy tournament title",       value:15 },
  { team:"Yale", week:19, event:"Makes the NCAA tournament",       value:10 },
  { team:"Yale", week:19, event:"Wins a game",                     value:1  },

  // Oakland — Horizon League champs, upset Kentucky in Round of 64
  { team:"Oakland", week:18, event:"Wins Horizon tournament",      value:15 },
  { team:"Oakland", week:19, event:"Makes the NCAA tournament",    value:10 },
  { team:"Oakland", week:19, event:"Wins a top-25 team",           value:5  },
  { team:"Oakland", week:19, event:"Reaches Round of 32",          value:10 },

  // James Madison — Sun Belt champs, NCAA tournament
  { team:"James Madison", week:16, event:"Wins outright league title", value:30 },
  { team:"James Madison", week:18, event:"Wins Sun Belt tournament",   value:15 },
  { team:"James Madison", week:19, event:"Makes the NCAA tournament",  value:10 },
  { team:"James Madison", week:19, event:"Wins a game",                value:1  },

  // Grand Canyon — WAC champs, NCAA tournament
  { team:"Grand Canyon", week:16, event:"Wins outright league title",  value:30 },
  { team:"Grand Canyon", week:18, event:"Wins WAC tournament title",   value:15 },
  { team:"Grand Canyon", week:19, event:"Makes the NCAA tournament",   value:10 },

  // Montana St. — Big Sky champs, NCAA tournament
  { team:"Montana St.", week:16, event:"Wins outright league title",   value:30 },
  { team:"Montana St.", week:18, event:"Wins Big Sky tournament",      value:15 },
  { team:"Montana St.", week:19, event:"Makes the NCAA tournament",    value:10 },

  // New Mexico — Mountain West co-champs
  { team:"New Mexico", week:16, event:"Wins contested league title",   value:20 },
  { team:"New Mexico", week:19, event:"Makes the NCAA tournament",     value:10 },
  { team:"New Mexico", week:19, event:"Wins a game",                   value:1  },

  // UNLV — Mountain West co-champs
  { team:"UNLV", week:16, event:"Wins contested league title",         value:20 },
  { team:"UNLV", week:19, event:"Makes the NCAA tournament",           value:10 },

  // Utah St. — Mountain West tournament
  { team:"Utah St.", week:18, event:"Wins Mountain West tournament",   value:15 },
  { team:"Utah St.", week:19, event:"Makes the NCAA tournament",       value:10 },
  { team:"Utah St.", week:19, event:"Wins a game",                     value:1  },

  // Creighton — Sweet Sixteen
  { team:"Creighton", week:19, event:"Makes the NCAA tournament",      value:10 },
  { team:"Creighton", week:19, event:"Wins a game",                    value:1  },
  { team:"Creighton", week:19, event:"Reaches Round of 32",            value:10 },
  { team:"Creighton", week:19, event:"Reaches Sweet Sixteen",          value:20 },

  // Clemson — Sweet Sixteen
  { team:"Clemson", week:19, event:"Makes the NCAA tournament",        value:10 },
  { team:"Clemson", week:19, event:"Wins a game",                      value:1  },
  { team:"Clemson", week:19, event:"Reaches Round of 32",              value:10 },
  { team:"Clemson", week:19, event:"Reaches Sweet Sixteen",            value:20 },

];

// Pre-compute a lookup: week → [events]
export const EVENTS_BY_WEEK = {};
for (const evt of DIVIDEND_EVENTS) {
  if (!EVENTS_BY_WEEK[evt.week]) EVENTS_BY_WEEK[evt.week] = [];
  EVENTS_BY_WEEK[evt.week].push(evt);
}
