// schedules.js
// Per-team game log for the 2023-24 season.
// Each entry: { team, games: [{ week, opponent, opponentAdjEM, result, score, location }] }
// result: "W" | "L"
// location: "H" | "A" | "N" (home / away / neutral)
// opponentAdjEM: the opponent's season-end AdjEM (used for "upcoming" context)

export const SCHEDULES = {

  "UConn": [
    { week:1,  opponent:"Fairleigh Dickinson", opponentAdjEM:4.8,  result:"W", score:"87-54",  location:"H" },
    { week:1,  opponent:"Stony Brook",          opponentAdjEM:5.2,  result:"W", score:"91-52",  location:"H" },
    { week:2,  opponent:"NC State",             opponentAdjEM:17.6, result:"W", score:"79-65",  location:"N" },
    { week:2,  opponent:"Georgia",              opponentAdjEM:13.2, result:"W", score:"77-52",  location:"N" },
    { week:3,  opponent:"Oklahoma",             opponentAdjEM:17.9, result:"W", score:"69-52",  location:"N" },
    { week:3,  opponent:"Oregon",               opponentAdjEM:18.2, result:"W", score:"92-64",  location:"N" },
    { week:4,  opponent:"Arizona St.",          opponentAdjEM:12.8, result:"W", score:"79-60",  location:"H" },
    { week:4,  opponent:"Grambling",            opponentAdjEM:7.2,  result:"W", score:"101-62", location:"H" },
    { week:5,  opponent:"Providence",           opponentAdjEM:15.4, result:"W", score:"72-56",  location:"A" },
    { week:5,  opponent:"Georgetown",           opponentAdjEM:6.5,  result:"W", score:"100-63", location:"H" },
    { week:6,  opponent:"Seton Hall",           opponentAdjEM:14.0, result:"W", score:"80-61",  location:"H" },
    { week:6,  opponent:"Marquette",            opponentAdjEM:24.6, result:"W", score:"74-71",  location:"A" },
    { week:7,  opponent:"Butler",               opponentAdjEM:11.8, result:"W", score:"83-55",  location:"H" },
    { week:7,  opponent:"St. John's",           opponentAdjEM:21.0, result:"W", score:"77-62",  location:"H" },
    { week:8,  opponent:"Xavier",               opponentAdjEM:16.8, result:"W", score:"76-60",  location:"A" },
    { week:9,  opponent:"Villanova",            opponentAdjEM:18.9, result:"W", score:"90-68",  location:"H" },
    { week:9,  opponent:"Creighton",            opponentAdjEM:23.5, result:"W", score:"75-70",  location:"A" },
    { week:10, opponent:"DePaul",               opponentAdjEM:4.2,  result:"W", score:"102-55", location:"H" },
    { week:10, opponent:"Georgetown",           opponentAdjEM:6.5,  result:"W", score:"88-49",  location:"A" },
    { week:11, opponent:"Providence",           opponentAdjEM:15.4, result:"W", score:"86-54",  location:"H" },
    { week:11, opponent:"Seton Hall",           opponentAdjEM:14.0, result:"W", score:"78-52",  location:"A" },
    { week:12, opponent:"Butler",               opponentAdjEM:11.8, result:"W", score:"85-54",  location:"A" },
    { week:12, opponent:"Xavier",               opponentAdjEM:16.8, result:"W", score:"80-68",  location:"H" },
    { week:13, opponent:"Marquette",            opponentAdjEM:24.6, result:"W", score:"71-68",  location:"H" },
    { week:13, opponent:"St. John's",           opponentAdjEM:21.0, result:"W", score:"89-73",  location:"A" },
    { week:14, opponent:"Creighton",            opponentAdjEM:23.5, result:"W", score:"78-71",  location:"H" },
    { week:14, opponent:"Villanova",            opponentAdjEM:18.9, result:"W", score:"91-65",  location:"A" },
    { week:15, opponent:"DePaul",               opponentAdjEM:4.2,  result:"W", score:"107-58", location:"H" },
    { week:15, opponent:"Marquette",            opponentAdjEM:24.6, result:"L", score:"80-82",  location:"A" },
    { week:16, opponent:"Georgetown",           opponentAdjEM:6.5,  result:"W", score:"95-52",  location:"H" },
    { week:16, opponent:"Creighton",            opponentAdjEM:23.5, result:"W", score:"76-64",  location:"H" },
    { week:17, opponent:"Seton Hall",           opponentAdjEM:14.0, result:"W", score:"83-56",  location:"H" },
    { week:17, opponent:"St. John's",           opponentAdjEM:21.0, result:"L", score:"70-72",  location:"A" },
    { week:18, opponent:"Xavier",               opponentAdjEM:16.8, result:"W", score:"88-71",  location:"N" },
    { week:18, opponent:"Marquette",            opponentAdjEM:24.6, result:"W", score:"73-57",  location:"N" },
    { week:18, opponent:"St. John's",           opponentAdjEM:21.0, result:"W", score:"82-54",  location:"N" },
    { week:19, opponent:"Stetson",              opponentAdjEM:3.8,  result:"W", score:"91-52",  location:"N" },
    { week:19, opponent:"Northwestern St.",     opponentAdjEM:4.0,  result:"W", score:"95-50",  location:"N" },
    { week:19, opponent:"San Diego St.",        opponentAdjEM:17.6, result:"W", score:"82-52",  location:"N" },
    { week:19, opponent:"Illinois",             opponentAdjEM:25.6, result:"W", score:"77-52",  location:"N" },
    { week:20, opponent:"Alabama",              opponentAdjEM:22.8, result:"W", score:"72-69",  location:"N" },
    { week:20, opponent:"Purdue",               opponentAdjEM:31.0, result:"W", score:"75-60",  location:"N" },
  ],

  "Purdue": [
    { week:1,  opponent:"Longwood",             opponentAdjEM:10.5, result:"W", score:"97-56",  location:"H" },
    { week:1,  opponent:"Milwaukee",            opponentAdjEM:9.0,  result:"W", score:"84-58",  location:"H" },
    { week:2,  opponent:"Morehead St.",         opponentAdjEM:10.5, result:"W", score:"102-69", location:"H" },
    { week:2,  opponent:"Marquette",            opponentAdjEM:24.6, result:"W", score:"73-72",  location:"N" },
    { week:3,  opponent:"Tennessee",            opponentAdjEM:27.6, result:"W", score:"72-66",  location:"N" },
    { week:3,  opponent:"Gonzaga",              opponentAdjEM:23.7, result:"W", score:"81-70",  location:"N" },
    { week:4,  opponent:"Florida Atlantic",     opponentAdjEM:16.0, result:"W", score:"84-70",  location:"H" },
    { week:4,  opponent:"Samford",              opponentAdjEM:11.1, result:"W", score:"95-62",  location:"H" },
    { week:5,  opponent:"Indiana",              opponentAdjEM:15.6, result:"W", score:"79-56",  location:"H" },
    { week:5,  opponent:"Nebraska",             opponentAdjEM:17.1, result:"W", score:"88-71",  location:"A" },
    { week:6,  opponent:"Iowa",                 opponentAdjEM:18.3, result:"W", score:"77-60",  location:"H" },
    { week:6,  opponent:"Ohio St.",             opponentAdjEM:19.8, result:"W", score:"81-63",  location:"A" },
    { week:7,  opponent:"Penn St.",             opponentAdjEM:16.9, result:"W", score:"89-73",  location:"H" },
    { week:7,  opponent:"Michigan St.",         opponentAdjEM:20.6, result:"W", score:"85-71",  location:"H" },
    { week:8,  opponent:"Maryland",             opponentAdjEM:17.8, result:"W", score:"78-58",  location:"A" },
    { week:9,  opponent:"Illinois",             opponentAdjEM:25.6, result:"W", score:"88-79",  location:"H" },
    { week:9,  opponent:"Michigan",             opponentAdjEM:15.1, result:"W", score:"91-65",  location:"A" },
    { week:10, opponent:"Wisconsin",            opponentAdjEM:19.4, result:"W", score:"80-61",  location:"H" },
    { week:10, opponent:"Nebraska",             opponentAdjEM:17.1, result:"W", score:"93-75",  location:"H" },
    { week:11, opponent:"Minnesota",            opponentAdjEM:13.9, result:"W", score:"88-55",  location:"A" },
    { week:11, opponent:"Illinois",             opponentAdjEM:25.6, result:"W", score:"79-70",  location:"A" },
    { week:12, opponent:"Northwestern",         opponentAdjEM:16.2, result:"W", score:"91-76",  location:"H" },
    { week:12, opponent:"Rutgers",              opponentAdjEM:13.5, result:"W", score:"81-55",  location:"A" },
    { week:13, opponent:"Penn St.",             opponentAdjEM:16.9, result:"W", score:"91-71",  location:"A" },
    { week:13, opponent:"Michigan St.",         opponentAdjEM:20.6, result:"L", score:"71-77",  location:"A" },
    { week:14, opponent:"Ohio St.",             opponentAdjEM:19.8, result:"W", score:"87-73",  location:"H" },
    { week:14, opponent:"Indiana",              opponentAdjEM:15.6, result:"W", score:"83-60",  location:"A" },
    { week:15, opponent:"Iowa",                 opponentAdjEM:18.3, result:"W", score:"84-59",  location:"A" },
    { week:15, opponent:"Wisconsin",            opponentAdjEM:19.4, result:"W", score:"72-66",  location:"A" },
    { week:16, opponent:"Michigan",             opponentAdjEM:15.1, result:"W", score:"91-66",  location:"H" },
    { week:16, opponent:"Minnesota",            opponentAdjEM:13.9, result:"W", score:"90-63",  location:"H" },
    { week:17, opponent:"Northwestern",         opponentAdjEM:16.2, result:"W", score:"98-78",  location:"A" },
    { week:17, opponent:"Maryland",             opponentAdjEM:17.8, result:"L", score:"74-75",  location:"H" },
    { week:18, opponent:"Nebraska",             opponentAdjEM:17.1, result:"W", score:"88-66",  location:"N" },
    { week:19, opponent:"Montana St.",          opponentAdjEM:12.5, result:"W", score:"94-55",  location:"N" },
    { week:19, opponent:"Utah St.",             opponentAdjEM:18.1, result:"W", score:"77-71",  location:"N" },
    { week:19, opponent:"Gonzaga",              opponentAdjEM:23.7, result:"W", score:"80-68",  location:"N" },
    { week:19, opponent:"NC State",             opponentAdjEM:17.6, result:"W", score:"63-58",  location:"N" },
    { week:20, opponent:"NC State",             opponentAdjEM:17.6, result:"W", score:"63-50",  location:"N" },
    { week:20, opponent:"UConn",                opponentAdjEM:34.6, result:"L", score:"60-75",  location:"N" },
  ],

  "Houston": [
    { week:1,  opponent:"Lamar",                opponentAdjEM:6.0,  result:"W", score:"86-47",  location:"H" },
    { week:1,  opponent:"UTSA",                 opponentAdjEM:10.0, result:"W", score:"79-58",  location:"H" },
    { week:2,  opponent:"Oregon",               opponentAdjEM:18.2, result:"W", score:"75-65",  location:"N" },
    { week:2,  opponent:"Wisconsin",            opponentAdjEM:19.4, result:"W", score:"72-55",  location:"N" },
    { week:3,  opponent:"South Alabama",        opponentAdjEM:11.2, result:"W", score:"91-58",  location:"H" },
    { week:3,  opponent:"Sam Houston",          opponentAdjEM:8.5,  result:"W", score:"88-52",  location:"H" },
    { week:4,  opponent:"Alabama",              opponentAdjEM:22.8, result:"W", score:"78-71",  location:"N" },
    { week:4,  opponent:"Virginia",             opponentAdjEM:17.4, result:"W", score:"70-61",  location:"N" },
    { week:5,  opponent:"TCU",                  opponentAdjEM:16.2, result:"W", score:"76-55",  location:"H" },
    { week:5,  opponent:"BYU",                  opponentAdjEM:20.1, result:"W", score:"67-58",  location:"A" },
    { week:6,  opponent:"Texas Tech",           opponentAdjEM:19.5, result:"L", score:"65-70",  location:"A" },
    { week:7,  opponent:"Iowa St.",             opponentAdjEM:24.0, result:"W", score:"68-60",  location:"H" },
    { week:7,  opponent:"Kansas",               opponentAdjEM:26.6, result:"W", score:"79-70",  location:"H" },
    { week:8,  opponent:"UCF",                  opponentAdjEM:14.2, result:"W", score:"82-61",  location:"A" },
    { week:9,  opponent:"Texas",                opponentAdjEM:23.1, result:"W", score:"73-66",  location:"H" },
    { week:9,  opponent:"Baylor",               opponentAdjEM:22.5, result:"W", score:"77-64",  location:"A" },
    { week:10, opponent:"Oklahoma",             opponentAdjEM:17.9, result:"W", score:"84-63",  location:"H" },
    { week:10, opponent:"West Virginia",        opponentAdjEM:14.6, result:"W", score:"79-55",  location:"A" },
    { week:11, opponent:"Cincinnati",           opponentAdjEM:15.0, result:"W", score:"78-56",  location:"H" },
    { week:11, opponent:"Kansas St.",           opponentAdjEM:17.3, result:"W", score:"74-60",  location:"A" },
    { week:12, opponent:"Iowa St.",             opponentAdjEM:24.0, result:"W", score:"69-62",  location:"A" },
    { week:12, opponent:"Texas Tech",           opponentAdjEM:19.5, result:"W", score:"75-66",  location:"H" },
    { week:13, opponent:"BYU",                  opponentAdjEM:20.1, result:"W", score:"80-68",  location:"H" },
    { week:13, opponent:"Kansas",               opponentAdjEM:26.6, result:"W", score:"71-65",  location:"A" },
    { week:14, opponent:"UCF",                  opponentAdjEM:14.2, result:"W", score:"85-60",  location:"H" },
    { week:14, opponent:"Texas",                opponentAdjEM:23.1, result:"W", score:"76-68",  location:"A" },
    { week:15, opponent:"Oklahoma St.",         opponentAdjEM:13.4, result:"W", score:"88-59",  location:"H" },
    { week:15, opponent:"TCU",                  opponentAdjEM:16.2, result:"W", score:"79-57",  location:"A" },
    { week:16, opponent:"Baylor",               opponentAdjEM:22.5, result:"L", score:"62-68",  location:"A" },
    { week:16, opponent:"West Virginia",        opponentAdjEM:14.6, result:"W", score:"80-55",  location:"H" },
    { week:17, opponent:"Oklahoma",             opponentAdjEM:17.9, result:"W", score:"83-60",  location:"A" },
    { week:18, opponent:"Kansas St.",           opponentAdjEM:17.3, result:"W", score:"71-60",  location:"N" },
    { week:19, opponent:"Longwood",             opponentAdjEM:10.5, result:"W", score:"86-46",  location:"N" },
    { week:19, opponent:"Texas A&M",            opponentAdjEM:19.8, result:"W", score:"66-54",  location:"N" },
    { week:19, opponent:"Duke",                 opponentAdjEM:27.3, result:"W", score:"54-51",  location:"N" },
    { week:20, opponent:"Connecticut",          opponentAdjEM:34.6, result:"L", score:"62-74",  location:"N" },
  ],

  "Iowa St.": [
    { week:1,  opponent:"Omaha",                opponentAdjEM:5.5,  result:"W", score:"79-52",  location:"H" },
    { week:1,  opponent:"Southern",             opponentAdjEM:4.2,  result:"W", score:"84-43",  location:"H" },
    { week:2,  opponent:"Memphis",              opponentAdjEM:16.2, result:"W", score:"82-67",  location:"H" },
    { week:2,  opponent:"Villanova",            opponentAdjEM:18.9, result:"W", score:"79-65",  location:"N" },
    { week:3,  opponent:"Iowa",                 opponentAdjEM:18.3, result:"W", score:"72-58",  location:"H" },
    { week:3,  opponent:"Creighton",            opponentAdjEM:23.5, result:"W", score:"69-61",  location:"H" },
    { week:4,  opponent:"Kansas",               opponentAdjEM:26.6, result:"W", score:"70-64",  location:"A" },
    { week:4,  opponent:"Oklahoma",             opponentAdjEM:17.9, result:"W", score:"77-62",  location:"H" },
    { week:5,  opponent:"West Virginia",        opponentAdjEM:14.6, result:"L", score:"70-74",  location:"A" },
    { week:6,  opponent:"TCU",                  opponentAdjEM:16.2, result:"W", score:"74-57",  location:"H" },
    { week:6,  opponent:"BYU",                  opponentAdjEM:20.1, result:"W", score:"67-59",  location:"A" },
    { week:7,  opponent:"Houston",              opponentAdjEM:30.7, result:"L", score:"60-68",  location:"A" },
    { week:7,  opponent:"Texas Tech",           opponentAdjEM:19.5, result:"W", score:"71-63",  location:"H" },
    { week:8,  opponent:"Kansas St.",           opponentAdjEM:17.3, result:"W", score:"75-60",  location:"H" },
    { week:8,  opponent:"Baylor",               opponentAdjEM:22.5, result:"W", score:"73-66",  location:"A" },
    { week:9,  opponent:"UCF",                  opponentAdjEM:14.2, result:"W", score:"80-61",  location:"H" },
    { week:9,  opponent:"Cincinnati",           opponentAdjEM:15.0, result:"W", score:"77-54",  location:"A" },
    { week:10, opponent:"Texas",                opponentAdjEM:23.1, result:"W", score:"67-58",  location:"H" },
    { week:10, opponent:"Oklahoma St.",         opponentAdjEM:13.4, result:"W", score:"79-60",  location:"A" },
    { week:11, opponent:"Kansas",               opponentAdjEM:26.6, result:"W", score:"65-60",  location:"H" },
    { week:11, opponent:"Texas Tech",           opponentAdjEM:19.5, result:"W", score:"72-64",  location:"A" },
    { week:12, opponent:"Houston",              opponentAdjEM:30.7, result:"L", score:"62-69",  location:"A" },
    { week:13, opponent:"Oklahoma",             opponentAdjEM:17.9, result:"W", score:"76-55",  location:"H" },
    { week:13, opponent:"Baylor",               opponentAdjEM:22.5, result:"W", score:"73-68",  location:"H" },
    { week:14, opponent:"BYU",                  opponentAdjEM:20.1, result:"W", score:"70-58",  location:"H" },
    { week:15, opponent:"Kansas St.",           opponentAdjEM:17.3, result:"W", score:"74-60",  location:"H" },
    { week:15, opponent:"West Virginia",        opponentAdjEM:14.6, result:"W", score:"81-58",  location:"H" },
    { week:16, opponent:"TCU",                  opponentAdjEM:16.2, result:"W", score:"77-55",  location:"A" },
    { week:17, opponent:"UCF",                  opponentAdjEM:14.2, result:"W", score:"83-65",  location:"A" },
    { week:18, opponent:"Kansas",               opponentAdjEM:26.6, result:"W", score:"74-65",  location:"N" },
    { week:18, opponent:"Houston",              opponentAdjEM:30.7, result:"W", score:"69-61",  location:"N" },
    { week:19, opponent:"South Dakota St.",     opponentAdjEM:13.4, result:"W", score:"82-60",  location:"N" },
    { week:19, opponent:"Washington St.",       opponentAdjEM:15.5, result:"W", score:"68-55",  location:"N" },
    { week:19, opponent:"Illinois",             opponentAdjEM:25.6, result:"W", score:"72-69",  location:"N" },
    { week:19, opponent:"Houston",              opponentAdjEM:30.7, result:"W", score:"66-60",  location:"N" },
  ],

  "NC State": [
    { week:1,  opponent:"Presbyterian",         opponentAdjEM:3.5,  result:"W", score:"79-51",  location:"H" },
    { week:2,  opponent:"Tennessee St.",        opponentAdjEM:7.8,  result:"W", score:"84-55",  location:"H" },
    { week:3,  opponent:"Iowa",                 opponentAdjEM:18.3, result:"W", score:"79-66",  location:"N" },
    { week:4,  opponent:"Georgia Tech",         opponentAdjEM:12.2, result:"W", score:"78-65",  location:"H" },
    { week:5,  opponent:"Wake Forest",          opponentAdjEM:14.8, result:"W", score:"84-72",  location:"A" },
    { week:6,  opponent:"Notre Dame",           opponentAdjEM:14.1, result:"L", score:"66-70",  location:"A" },
    { week:7,  opponent:"Florida St.",          opponentAdjEM:13.5, result:"W", score:"79-60",  location:"H" },
    { week:8,  opponent:"Virginia",             opponentAdjEM:17.4, result:"W", score:"68-62",  location:"A" },
    { week:9,  opponent:"Pittsburgh",           opponentAdjEM:16.1, result:"L", score:"65-70",  location:"A" },
    { week:10, opponent:"Syracuse",             opponentAdjEM:14.0, result:"W", score:"80-67",  location:"H" },
    { week:11, opponent:"Miami (FL)",           opponentAdjEM:17.5, result:"W", score:"76-63",  location:"H" },
    { week:12, opponent:"Clemson",              opponentAdjEM:19.3, result:"L", score:"65-72",  location:"A" },
    { week:13, opponent:"Louisville",           opponentAdjEM:15.7, result:"W", score:"81-70",  location:"H" },
    { week:14, opponent:"Duke",                 opponentAdjEM:27.3, result:"L", score:"58-71",  location:"A" },
    { week:15, opponent:"Virginia Tech",        opponentAdjEM:15.8, result:"W", score:"75-66",  location:"H" },
    { week:16, opponent:"North Carolina",       opponentAdjEM:21.3, result:"W", score:"76-69",  location:"H" },
    { week:17, opponent:"Boston College",       opponentAdjEM:10.0, result:"W", score:"88-62",  location:"A" },
    { week:18, opponent:"Virginia",             opponentAdjEM:17.4, result:"W", score:"72-61",  location:"N" },
    { week:18, opponent:"North Carolina",       opponentAdjEM:21.3, result:"W", score:"84-76",  location:"N" },
    { week:18, opponent:"Duke",                 opponentAdjEM:27.3, result:"W", score:"79-78",  location:"N" },
    { week:19, opponent:"Texas Tech",           opponentAdjEM:19.5, result:"W", score:"80-67",  location:"N" },
    { week:19, opponent:"Oakland",              opponentAdjEM:12.8, result:"W", score:"79-73",  location:"N" },
    { week:19, opponent:"Marquette",            opponentAdjEM:24.6, result:"W", score:"67-58",  location:"N" },
    { week:19, opponent:"Duke",                 opponentAdjEM:27.3, result:"W", score:"76-64",  location:"N" },
    { week:20, opponent:"UConn",                opponentAdjEM:34.6, result:"L", score:"50-63",  location:"N" },
    { week:20, opponent:"Purdue",               opponentAdjEM:31.0, result:"L", score:"50-63",  location:"N" },
  ],

  "Tennessee": [
    { week:1,  opponent:"Tennessee Tech",       opponentAdjEM:8.5,  result:"W", score:"97-54",  location:"H" },
    { week:1,  opponent:"Colorado",             opponentAdjEM:19.5, result:"W", score:"82-68",  location:"H" },
    { week:2,  opponent:"UNLV",                 opponentAdjEM:16.2, result:"W", score:"80-60",  location:"N" },
    { week:3,  opponent:"Purdue",               opponentAdjEM:31.0, result:"L", score:"66-72",  location:"N" },
    { week:3,  opponent:"Colorado",             opponentAdjEM:19.5, result:"W", score:"78-63",  location:"N" },
    { week:4,  opponent:"Alabama",              opponentAdjEM:22.8, result:"W", score:"73-64",  location:"H" },
    { week:4,  opponent:"Arkansas",             opponentAdjEM:17.8, result:"W", score:"77-55",  location:"A" },
    { week:5,  opponent:"Kentucky",             opponentAdjEM:21.6, result:"W", score:"75-68",  location:"H" },
    { week:5,  opponent:"South Carolina",       opponentAdjEM:15.0, result:"W", score:"87-62",  location:"A" },
    { week:6,  opponent:"Vanderbilt",           opponentAdjEM:12.4, result:"W", score:"83-58",  location:"H" },
    { week:7,  opponent:"Missouri",             opponentAdjEM:17.3, result:"L", score:"66-75",  location:"A" },
    { week:8,  opponent:"Ole Miss",             opponentAdjEM:16.1, result:"W", score:"74-58",  location:"H" },
    { week:9,  opponent:"Auburn",               opponentAdjEM:25.1, result:"W", score:"68-61",  location:"H" },
    { week:9,  opponent:"Florida",              opponentAdjEM:19.2, result:"W", score:"76-57",  location:"A" },
    { week:10, opponent:"Georgia",              opponentAdjEM:13.2, result:"W", score:"89-67",  location:"H" },
    { week:10, opponent:"Alabama",              opponentAdjEM:22.8, result:"W", score:"78-70",  location:"A" },
    { week:11, opponent:"Missouri",             opponentAdjEM:17.3, result:"W", score:"81-67",  location:"H" },
    { week:12, opponent:"LSU",                  opponentAdjEM:16.0, result:"W", score:"75-59",  location:"A" },
    { week:12, opponent:"Auburn",               opponentAdjEM:25.1, result:"L", score:"63-72",  location:"A" },
    { week:13, opponent:"South Carolina",       opponentAdjEM:15.0, result:"W", score:"82-61",  location:"H" },
    { week:13, opponent:"Kentucky",             opponentAdjEM:21.6, result:"W", score:"77-65",  location:"A" },
    { week:14, opponent:"Vanderbilt",           opponentAdjEM:12.4, result:"W", score:"88-57",  location:"A" },
    { week:15, opponent:"Florida",              opponentAdjEM:19.2, result:"W", score:"69-55",  location:"H" },
    { week:15, opponent:"Arkansas",             opponentAdjEM:17.8, result:"W", score:"71-58",  location:"H" },
    { week:16, opponent:"Georgia",              opponentAdjEM:13.2, result:"L", score:"60-67",  location:"A" },
    { week:17, opponent:"Ole Miss",             opponentAdjEM:16.1, result:"W", score:"79-63",  location:"H" },
    { week:19, opponent:"Saint Peter's",        opponentAdjEM:8.5,  result:"W", score:"96-52",  location:"N" },
    { week:19, opponent:"Creighton",            opponentAdjEM:23.5, result:"W", score:"82-72",  location:"N" },
    { week:19, opponent:"Illinois",             opponentAdjEM:25.6, result:"L", score:"72-76",  location:"N" },
  ],

  "Duke": [
    { week:1,  opponent:"Army",                 opponentAdjEM:8.0,  result:"W", score:"88-55",  location:"H" },
    { week:2,  opponent:"Arizona",              opponentAdjEM:25.3, result:"W", score:"82-75",  location:"N" },
    { week:3,  opponent:"Kentucky",             opponentAdjEM:21.6, result:"W", score:"74-69",  location:"N" },
    { week:4,  opponent:"Ohio",                 opponentAdjEM:11.5, result:"W", score:"93-66",  location:"H" },
    { week:4,  opponent:"Michigan St.",         opponentAdjEM:20.6, result:"W", score:"77-62",  location:"H" },
    { week:5,  opponent:"Louisville",           opponentAdjEM:15.7, result:"W", score:"85-65",  location:"H" },
    { week:6,  opponent:"NC State",             opponentAdjEM:17.6, result:"W", score:"71-58",  location:"H" },
    { week:7,  opponent:"Wake Forest",          opponentAdjEM:14.8, result:"W", score:"80-66",  location:"A" },
    { week:8,  opponent:"North Carolina",       opponentAdjEM:21.3, result:"L", score:"60-68",  location:"A" },
    { week:9,  opponent:"Notre Dame",           opponentAdjEM:14.1, result:"W", score:"78-62",  location:"H" },
    { week:9,  opponent:"Virginia",             opponentAdjEM:17.4, result:"W", score:"65-52",  location:"H" },
    { week:10, opponent:"Miami (FL)",           opponentAdjEM:17.5, result:"W", score:"80-70",  location:"A" },
    { week:10, opponent:"Clemson",              opponentAdjEM:19.3, result:"W", score:"72-63",  location:"H" },
    { week:11, opponent:"Pittsburgh",           opponentAdjEM:16.1, result:"W", score:"74-61",  location:"H" },
    { week:11, opponent:"Georgia Tech",         opponentAdjEM:12.2, result:"W", score:"82-57",  location:"A" },
    { week:12, opponent:"Syracuse",             opponentAdjEM:14.0, result:"W", score:"87-71",  location:"H" },
    { week:13, opponent:"Virginia Tech",        opponentAdjEM:15.8, result:"W", score:"78-64",  location:"A" },
    { week:14, opponent:"NC State",             opponentAdjEM:17.6, result:"W", score:"71-58",  location:"H" },
    { week:15, opponent:"Florida St.",          opponentAdjEM:13.5, result:"L", score:"64-68",  location:"A" },
    { week:16, opponent:"North Carolina",       opponentAdjEM:21.3, result:"W", score:"74-66",  location:"H" },
    { week:17, opponent:"Wake Forest",          opponentAdjEM:14.8, result:"W", score:"85-64",  location:"H" },
    { week:19, opponent:"Vermont",              opponentAdjEM:12.5, result:"W", score:"91-61",  location:"N" },
    { week:19, opponent:"James Madison",        opponentAdjEM:13.8, result:"W", score:"75-60",  location:"N" },
    { week:19, opponent:"Houston",              opponentAdjEM:30.7, result:"L", score:"51-54",  location:"N" },
  ],

  "Marquette": [
    { week:1,  opponent:"Illinois-Chicago",     opponentAdjEM:5.0,  result:"W", score:"87-58",  location:"H" },
    { week:2,  opponent:"UConn",                opponentAdjEM:34.6, result:"L", score:"71-74",  location:"N" },
    { week:2,  opponent:"Memphis",              opponentAdjEM:16.2, result:"W", score:"81-68",  location:"N" },
    { week:3,  opponent:"Villanova",            opponentAdjEM:18.9, result:"W", score:"77-63",  location:"H" },
    { week:3,  opponent:"Providence",           opponentAdjEM:15.4, result:"W", score:"82-65",  location:"A" },
    { week:4,  opponent:"Seton Hall",           opponentAdjEM:14.0, result:"W", score:"85-70",  location:"H" },
    { week:4,  opponent:"Georgetown",           opponentAdjEM:6.5,  result:"W", score:"97-58",  location:"A" },
    { week:5,  opponent:"DePaul",               opponentAdjEM:4.2,  result:"W", score:"102-62", location:"H" },
    { week:5,  opponent:"Creighton",            opponentAdjEM:23.5, result:"W", score:"73-67",  location:"H" },
    { week:6,  opponent:"Xavier",               opponentAdjEM:16.8, result:"W", score:"80-65",  location:"A" },
    { week:7,  opponent:"Butler",               opponentAdjEM:11.8, result:"W", score:"88-57",  location:"H" },
    { week:8,  opponent:"St. John's",           opponentAdjEM:21.0, result:"W", score:"81-70",  location:"A" },
    { week:9,  opponent:"UConn",                opponentAdjEM:34.6, result:"W", score:"82-80",  location:"H" },
    { week:9,  opponent:"Villanova",            opponentAdjEM:18.9, result:"W", score:"79-63",  location:"A" },
    { week:10, opponent:"DePaul",               opponentAdjEM:4.2,  result:"W", score:"103-59", location:"A" },
    { week:11, opponent:"Seton Hall",           opponentAdjEM:14.0, result:"W", score:"84-61",  location:"H" },
    { week:12, opponent:"Georgetown",           opponentAdjEM:6.5,  result:"W", score:"96-55",  location:"H" },
    { week:13, opponent:"UConn",                opponentAdjEM:34.6, result:"L", score:"68-71",  location:"A" },
    { week:14, opponent:"Providence",           opponentAdjEM:15.4, result:"W", score:"80-62",  location:"H" },
    { week:15, opponent:"Xavier",               opponentAdjEM:16.8, result:"W", score:"78-65",  location:"H" },
    { week:16, opponent:"St. John's",           opponentAdjEM:21.0, result:"W", score:"79-72",  location:"H" },
    { week:16, opponent:"Creighton",            opponentAdjEM:23.5, result:"L", score:"63-68",  location:"A" },
    { week:17, opponent:"Butler",               opponentAdjEM:11.8, result:"W", score:"90-60",  location:"A" },
    { week:19, opponent:"Western Ky.",          opponentAdjEM:9.2,  result:"W", score:"87-69",  location:"N" },
    { week:19, opponent:"Colorado",             opponentAdjEM:19.5, result:"L", score:"71-78",  location:"N" },
  ],
};

// Helper: get games for a team up to (and including) a given week
export function getGamesUpToWeek(team, currentWeek) {
  const games = SCHEDULES[team] || [];
  return games.filter((g) => g.week <= currentWeek);
}

// Helper: get games for a team after a given week
export function getGamesAfterWeek(team, currentWeek) {
  const games = SCHEDULES[team] || [];
  return games.filter((g) => g.week > currentWeek);
}

// Helper: get games in a specific week for a team
export function getGamesForWeek(team, week) {
  const games = SCHEDULES[team] || [];
  return games.filter((g) => g.week === week);
}
